### ISSUE TITLE
eslint fails during build of 2.32.0

### ISSUE THREAD

**Issue by ddevault** [prometheus/prometheus#10020]
* System information: Alpine Linux edge

```
yarn run v1.22.17
$ eslint --fix "src/**/*.{ts,tsx}"
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.4

Please only submit bug reports when using the officially supported version.

=============

Oops! Something went wrong! :(

ESLint: 8.4.1

Error: Rules with suggestions must set the `meta.hasSuggestions` property to `true`. `meta.docs.suggestion` is ignored by ESLint.
Occurred while linting /home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/react-app/src/components/withStatusIndicator.tsx:14
Rule: "@typescript-eslint/no-explicit-any"
    at Object.report (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/linter.js:1056:39)
    at TSAnyKeyword (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-explicit-any.js:183:25)
    at ruleErrorHandler (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/sircmpwn/sources/aports/community/prometheus/src/prometheus-2.32.0/web/ui/node_modules/@typescript-eslint/experimental-utils/node_modules/eslint-utils/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Nexucis** [comment]
Hello @ddevault ,

So far on our side the build is running fine, otherwise we won't be able to build Prometheus on the different platform.

A couple months ago we moved to `npm` (from `yarn`) as a dependency manager. I would suggest to do the same, perhaps it will help to solve your issue.

**Comment by ddevault** [comment]
It's already close to my bandwidth limit trying to keep up packaging this software, as it's primarily designed for the Docker generation and does not pay much heed to the needs of Linux distributions. Would you be prepared to write up some documentation for building and installing Prometheus outside of a Docker container, so I don't have to keep guessing?

**Comment by Nexucis** [comment]
From the README at the root of the repo: 

> You can also clone the repository yourself and build using make build, which will compile in the web assets so that Prometheus can be run from anywhere

https://github.com/prometheus/prometheus#building-from-source

And you can have more information around the frontend specifically here: https://github.com/prometheus/prometheus/tree/main/web/ui

But the section `building from source` should be enough for your needs. You don't have to guess, I think you just have to read the documentation :).
Or if you think there is a miss in the doc, then definitely we can improve it or you can help to improve it.

And hopefully, for linux distributions, the precompiled binaries should be enough.

**Comment by ddevault** [comment]
Sorry, I was in a bit of a bad mood last night and I should have been more polite.

These instructions are helpful, but not exactly what I'm looking for. I am not a user of a Linux distro - I am a representative of one. We package Prometheus so that users can install it on our distro by running `apk install prometheus` in one go. We need a process which essentially produces a binary tarball from source which can be extracted over / to install it.

I'll take some of these docs into account and see if my approach cannot be effectively adapted to use some of these details, though.

**Comment by ddevault** [comment]
Alright, I'm using this build process now and it seems to work adequately:

```
prepare() {
	cd web/ui
	npm install
	sed -i node_modules/codemirror-promql/package.json -e 's/lezer-generator/npx lezer-generator/g'
}

build() {
	GOLDFLAGS="-X github.com/prometheus/common/version.Version=$pkgver
		-X github.com/prometheus/common/version.Revision=AlpineLinux
		-X github.com/prometheus/common/version.Branch=master
		-X github.com/prometheus/common/version.BuildUser=$USER@$HOSTNAME
		-X github.com/prometheus/common/version.BuildDate=$(date -u "+%Y%m%d-%H:%M:%S" ${SOURCE_DATE_EPOCH:+-d @$SOURCE_DATE_EPOCH})
	"
	if [ -n "$LDFLAGS" ]; then
		# LDFLAGS (and only LDFLAGS) should be passed to -extldflags.
		GOLDFLAGS="$GOLDFLAGS -extldflags $LDFLAGS"
	fi

	make assets
	go mod vendor
	go build \
		-trimpath \
		-mod=vendor \
		-ldflags "$GOLDFLAGS" \
		-tags netgo,builtinassets \
		./cmd/prometheus
	go build \
		-trimpath \
		-mod=vendor \
		-ldflags "$GOLDFLAGS" \
		./cmd/promtool
}
```

I will send a patch for the lezer-generator issue. Thanks for your help!
