### ISSUE TITLE
nil deference in TestUpdateRemoteReadConfigs

### ISSUE THREAD

**Issue by charlesxsh** [prometheus/prometheus#10034]
**What did you do?**
trigger Test TestUpdateRemoteReadConfigs
**What did you expect to see?**
PASS
**What did you see instead? Under which circumstances?**

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaecd95]

goroutine 65 [running]:
testing.tRunner.func1.2(0xbbf420, 0x116cce0)
	/usr/local/go/src/testing/testing.go:1143 +0x335
testing.tRunner.func1(0xc000341400)
	/usr/local/go/src/testing/testing.go:1146 +0x4c2
panic(0xbbf420, 0x116cce0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/prometheus/prometheus/storage/remote.NewReadClient(0xc0003382e0, 0x6, 0xc0001b9cc0, 0x20, 0xc0001b9dd8, 0x0, 0x0)
	/repos/prometheus/storage/remote/client.go:125 +0x175
github.com/prometheus/prometheus/storage/remote.(*Storage).ApplyConfig(0xc00030cb40, 0xc0005ffe78, 0x0, 0x0)
	/repos/prometheus/storage/remote/storage.go:113 +0x3e8
github.com/prometheus/prometheus/storage/remote.TestUpdateRemoteReadConfigs(0xc000341400)
	/repos/prometheus/storage/remote/storage_test.go:88 +0x27c
testing.tRunner(0xc000341400, 0xcc03c0)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b5
```

Similar issue with #10033, missing URL in
```
func TestUpdateRemoteReadConfigs(t *testing.T) {
	dir := t.TempDir()

	s := NewStorage(nil, nil, nil, dir, defaultFlushDeadline, nil)

	conf := &config.Config{
		GlobalConfig: config.GlobalConfig{},
                 // URL is missing
	}
	require.NoError(t, s.ApplyConfig(conf))
	require.Equal(t, 0, len(s.queryables))

	conf.RemoteReadConfigs = []*config.RemoteReadConfig{
		&config.DefaultRemoteReadConfig,
	}
```

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by csmarchbanks** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/10935
