### ISSUE TITLE
Possible goroutine leaks at TestScrapeLoopRun

### ISSUE THREAD

**Issue by charlesxsh** [prometheus/prometheus#10058]
**What did you do?**
Using our tool to trigger TestScrapeLoopRun and TestScrapeLoopForcedErr

**What did you expect to see?**

**What did you see instead? Under which circumstances?**
```
func TestScrapeLoopRun(t *testing.T) {
   var (
       signal = make(chan struct{}, 1)
       errc   = make(chan error) // line 1
   ………….
   go func() {
       sl.run(errc) // line 2
       signal <- struct{}{}
   }()
   select {
   case err := <-errc:  // line 3
       if err != context.DeadlineExceeded {
           t.Fatalf("Expected timeout error but got: %s", err)
       }
   case <-time.After(3 * time.Second): // line 5
       t.Fatalf("Expected timeout error but got none")
   }
 

func (sl *scrapeLoop) run(errc chan<- error) {
  For {
     …
   last = sl.scrapeAndReport(last, scrapeTime, errc)

  }
}

func (sl *scrapeLoop) scrapeAndReport(last, appendTime time.Time, errc chan<- error) time.Time {
…
if forcedErr := sl.getForcedError(); forcedErr != nil {
       scrapeErr = forcedErr
       // Add stale markers.
       if _, _, _, err := sl.append(app, []byte{}, "", appendTime); err != nil {
           app.Rollback()
           app = sl.appender(sl.parentCtx)
           level.Warn(sl.l).Log("msg", "Append failed", "err", err)
       }
       if errc != nil {
           errc <- forcedErr  // line 4
       }
 
       return start
   }
…
}
```

The channel is created at line 1, and passed in to function at line 2. Receiver is at line 3.if test failed at line 5, then line 4’s sending operation will be blocked.
```
goroutine 58 [chan send]:
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc00039a200, 0x3b9aca00, 0x5f5e100, 0x0, 0x0, 0x0, 0xc0641f7b9561e3fe, 0x3c3c2212, 0x10dc4a0, 0xc00002a680, ...)
   /repos/prometheus/scrape/scrape.go:1338 +0x12b9
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc00039a200, 0x3b9aca00, 0x5f5e100, 0xc00002a680)
   /repos/prometheus/scrape/scrape.go:1189 +0x590
github.com/prometheus/prometheus/scrape.TestScrapeLoopRun.func4(0xc00000e028, 0xc00002a680, 0xc00002a600)
   /repos/prometheus/scrape/scrape_test.go:1089 +0x4e
created by github.com/prometheus/prometheus/scrape.TestScrapeLoopRun
   /repos/prometheus/scrape/scrape_test.go:1088 +0x6c8
```

Similiar situation also happened in TestScrapeLoopForcedErr
**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
We have tests for go routine leaks. What are we missing, why aren't those tests failing?

**Comment by charlesxsh** [comment]
In normal situation, test will be fine. The test will have goroutine leak if line 5 got triggered.

> We have tests for go routine leaks. What are we missing, why aren't those tests failing?

**Comment by beorn7** [comment]
Hello from the bug scrub!

This problem is still in the code. It's "just in a test", not affecting the actual code (as far as we understand). @machine424 will have a more detailed look how to fix this.

**Comment by machine424** [comment]
Took a look at this and you're right, there is a leak when the test fails. One could argue that a failing test is sufficient to indicate a problem with the test itself, but I opened https://github.com/uber-go/goleak/issues/128 (currently, we only check for leaks when tests pass)

**Comment by machine424** [comment]
Still blocked by https://github.com/uber-go/goleak/pull/132

**Comment by aknuds1** [comment]
Is this now fixed?

**Comment by shilohlee98** [comment]
i think this is fixed in https://github.com/prometheus/prometheus/pull/17554

<img width="1228" height="196" alt="Image" src="https://github.com/user-attachments/assets/cfc3a09d-a3af-420d-9177-13a391562c82" />

**Comment by aknuds1** [comment]
AFAICT it's fixed by #17554 and #17631.
