### ISSUE TITLE
Prometheus bus error code=0x2 crash, loop after working around 5 hours with azure file share like a storage for data

### ISSUE THREAD

**Issue by MrIgorKek** [prometheus/prometheus#10892]
### What did you do?

I created azure container instance with some services (including Prometheus) and mount azure file share (/data) to store here prometheus data (with flag --storage.tsdb.path=/data/prometheus). This set up worked good amount 1.5 years, but after some image update it is become to unstable work and can normally start only after removing prometheus database, but anyway after some hours of work (amount 5 hours) it crashes again.

Now it is can stable work only when I use internal container storage to store prometheus data (with flag --storage.tsdb.path=/var/prometheus)

full log here:
[prometheus (18).log](https://github.com/prometheus/prometheus/files/8940507/prometheus.18.log)

### What did you see instead? Under which circumstances?

So it crashes with such log:
````
unexpected fault address 0x7f9c89847000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f9c89847000 pc=0x227fe5c]

goroutine 410 [running]:
runtime.throw({0x2f1e844?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00da8ec48 sp=0xc00da8ec18 pc=0x4384b1
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:815 +0x125 fp=0xc00da8ec98 sp=0xc00da8ec48 pc=0x44e525
encoding/binary.bigEndian.Uint32(...)
	/usr/local/go/src/encoding/binary/binary.go:113
github.com/prometheus/prometheus/tsdb/chunks.newReader({0xc00dce6640, 0x1, 0x1}, {0xc00dce6630, 0x1, 0x1}, {0x3898110, 0xc000b161e0})
	/app/tsdb/chunks/chunks.go:488 +0x1fc fp=0xc00da8ed68 sp=0xc00da8ec98 pc=0x227fe5c
github.com/prometheus/prometheus/tsdb/chunks.NewDirReader({0xc00e8fea00?, 0x0?}, {0x3898110, 0xc000b161e0})
	/app/tsdb/chunks/chunks.go:528 +0x12e fp=0xc00da8ef40 sp=0xc00da8ed68 pc=0x228018e
github.com/prometheus/prometheus/tsdb.OpenBlock({0x388c200, 0xc000a61d10}, {0xc00dcdc990, 0x2f}, {0x3898110, 0xc000b161e0})
	/app/tsdb/block.go:298 +0x1ce fp=0xc00da8f0d8 sp=0xc00da8ef40 pc=0x22e55ee
github.com/prometheus/prometheus/tsdb.openBlocks({0x388c200, 0xc000a61d10}, {0x7ffe2e2a466d?, 0x203003?}, {0xc00cfccd58, 0x1, 0x442b60?}, {0x3898110, 0xc000b161e0})
	/app/tsdb/db.go:1169 +0x411 fp=0xc00da8f280 sp=0xc00da8f0d8 pc=0x22f6991
github.com/prometheus/prometheus/tsdb.(*DB).reloadBlocks(0xc0006e6000)
	/app/tsdb/db.go:1064 +0x125 fp=0xc00da8fb80 sp=0xc00da8f280 pc=0x22f50c5
github.com/prometheus/prometheus/tsdb.(*DB).compactHead(0xc0006e6000, 0xc00233fd28)
	/app/tsdb/db.go:973 +0x9f fp=0xc00da8fd28 sp=0xc00da8fb80 pc=0x22f45bf
github.com/prometheus/prometheus/tsdb.(*DB).Compact(0xc0006e6000)
	/app/tsdb/db.go:926 +0x2b3 fp=0xc00da8fe78 sp=0xc00da8fd28 pc=0x22f3a73
github.com/prometheus/prometheus/tsdb.(*DB).run(0xc0006e6000)
	/app/tsdb/db.go:828 +0x3ef fp=0xc00da8ffc8 sp=0xc00da8fe78 pc=0x22f322f
github.com/prometheus/prometheus/tsdb.open.func5()
	/app/tsdb/db.go:758 +0x26 fp=0xc00da8ffe0 sp=0xc00da8ffc8 pc=0x22f21e6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00da8ffe8 sp=0xc00da8ffe0 pc=0x46b301
created by github.com/prometheus/prometheus/tsdb.open
	/app/tsdb/db.go:758 +0xd71
````

### System information

FROM ubuntu:20.04

### Prometheus version

```text
prometheus, version 2.36.0 (branch: HEAD, revision: d48f381d9a4e68c83283ce5233844807dfdc5ba5)
  build user:       root@b3126bd1c115
  build date:       20220530-13:56:56
  go version:       go1.18.2
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
I see you are using a CIFS share, which we do not support in Prometheus unfortunately. For performance reasons, Prometheus is currently doing operations such as MMAP which might not work properly on network filesystems.

**Comment by MrIgorKek** [comment]
Is it can be problem with updating of Go-lang version? I can't say which one was earlier but now it is go1.18.2.
