### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by guoshimin** [prometheus/prometheus#1104]
Prometheus gave the following error after running for a few days:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x77e8e6]

goroutine 184 [running]:
github.com/prometheus/prometheus/retrieval/discovery.(*ConsulDiscovery).watchServices(0xc208451320, 0xc224c14120, 0xc22d0e90e0)
        /app/.build/root/gopath/src/github.com/prometheus/prometheus/retrieval/discovery/consul.go:200 +0x1f6
created by github.com/prometheus/prometheus/retrieval/discovery.(*ConsulDiscovery).Run
        /app/.build/root/gopath/src/github.com/prometheus/prometheus/retrieval/discovery/consul.go:151 +0xbe
```

**Comment by guoshimin** [comment]
The commit hash is 9a70ee7

**Comment by fabxc** [comment]
Thanks, that was a pretty clear one unfortunately.
Really time to put some though in either proper integration tests or doing or putting effort into some relatively complex mocking...
