### ISSUE TITLE
Flaky TestMarathonSDRunAndStop test hangs sometimes

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1142]
My automated build system got a test failure last night in the Marathon tests in TestMarathonSDRunAndStop:

```
SIGQUIT: quit
PC=0x45f681 m=0

goroutine 0 [idle]:
runtime.futex(0xb5b4f0, 0x0, 0x0, 0x0, 0x0, 0xb5ab00, 0x0, 0x0, 0x40e1d4, 0xb5b4f0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:288 +0x21
runtime.futexsleep(0xb5b4f0, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:39 +0x53
runtime.notesleep(0xb5b4f0)
	/usr/local/go/src/runtime/lock_futex.go:142 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1128 +0x112
runtime.findrunnable(0xc82001ea00, 0x0)
	/usr/local/go/src/runtime/proc1.go:1530 +0x69e
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1639 +0x267
runtime.park_m(0xc820118180)
	/usr/local/go/src/runtime/proc1.go:1698 +0x18b
runtime.mcall(0x7ffe0d133530)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [chan receive]:
testing.RunTests(0x9d0f88, 0xb564c0, 0x7, 0x7, 0xc82005d501)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200bfee8, 0x9d28a0)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/prometheus/prometheus/retrieval/discovery/_test/_testmain.go:66 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 48 [chan send]:
github.com/prometheus/prometheus/retrieval/discovery.(*MarathonDiscovery).updateServices(0xc820172680, 0xc820182d80, 0x0, 0x0)
	/var/lib/jenkins/jobs/prometheus-deb-amd64-precise/workspace/gopath/src/github.com/prometheus/prometheus/retrieval/discovery/marathon.go:80 +0x119
github.com/prometheus/prometheus/retrieval/discovery.(*MarathonDiscovery).Run(0xc820172680, 0xc820182d80, 0xc820182e40)
	/var/lib/jenkins/jobs/prometheus-deb-amd64-precise/workspace/gopath/src/github.com/prometheus/prometheus/retrieval/discovery/marathon.go:64 +0x133
github.com/prometheus/prometheus/retrieval/discovery.TestMarathonSDRunAndStop(0xc82016e750)
	/var/lib/jenkins/jobs/prometheus-deb-amd64-precise/workspace/gopath/src/github.com/prometheus/prometheus/retrieval/discovery/marathon_test.go:174 +0x297
testing.tRunner(0xc82016e750, 0xb56550)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xb5b4f0
rsi    0x0
rbp    0x1
rsp    0x7ffe0d133388
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0x9cd9bd
r14    0x9
r15    0x8
rip    0x45f681
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/prometheus/prometheus/retrieval/discovery	600.044s
?   	github.com/prometheus/prometheus/retrieval/discovery/kubernetes	[no test files]
?   	github.com/prometheus/prometheus/retrieval/discovery/marathon	[no test files]
```

**Comment by brian-brazil** [comment]
I haven't seen one of these in a good while and that code has changed a bit, so presuming it's been fixed for now.
