### ISSUE TITLE
Panic when supplying malformed URL for -external.web-path

### ISSUE THREAD

**Issue by bluecmd** [prometheus/prometheus#1229]
When I tried to use -external.web-path in 0.16.1 I got the following panic:
```
wildcards must be named with a non-empty name in path '/'https://url/prometheus'/'
```
This turns out to be because I erroneously supplied extra quotes, but as @fabxc says it probably shouldn't panic but just print an error message.

**Comment by fabxc** [comment]
Mh, could you provide the exact input and maybe the panic stack trace. I'm not quite sure where we would be throwing a panic.

**Comment by bluecmd** [comment]
```
bluecmd@dhmon:~/prometheus-0.16.1.linux-amd64$ ./prometheus -web.external-url="'http://test/ads'" 
prometheus, version 0.16.1 (branch: release-0.16.1, revision: 968ee35)
  build user:       fabianreinartz@macpro
  build date:       20151016-13:19:57
  go version:       1.5
panic: wildcards must be named with a non-empty name in path '/'http://test/ads'/'

goroutine 1 [running]:
github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter.(*node).insertChild(0xc82008da40, 0x1, 0xc8201130c1, 0x12, 0xc8201130c0, 0x13, 0xc8201c42b0)
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter/tree.go:233 +0x46b
github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter.(*node).addRoute(0xc82008da40, 0xc8201130c1, 0x12, 0xc8201c42b0)
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter/tree.go:185 +0xb21
github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter.(*Router).Handle(0xc82018f140, 0xdcf208, 0x3, 0xc8201130c0, 0x13, 0xc8201c42b0)
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter/router.go:229 +0x22b
github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter.(*Router).GET(0xc82018f140, 0xc8201130c0, 0x13, 0xc8201c42b0)
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter/router.go:173 +0x54
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route.(*Router).Get(0xc8201130a0, 0xdcde10, 0x1, 0xc8201c42a0)
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route/route.go:75 +0xa5
github.com/prometheus/prometheus/web.New(0x7f7405dd9080, 0xc8201043c0, 0xc82018f100, 0xc820089620, 0xc820089680, 0x1351858, 0xc820112fc0)
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/web/web.go:164 +0x608
main.Main(0x0)
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:110 +0xa55
main.main()
	/Users/fabianreinartz/repos/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:46 +0x18

goroutine 30 [syscall]:
os/signal.loop()
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by juliusv** [comment]
Ok, so the problem is that github.com/julienschmidt/httprouter panics when an invalid path is provided, and that `url.Parse` in https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/config.go#L263 sets the path to the entire provided string if it's in quotes.

So unless we want to swap out the underlying HTTP library, we'll have to sanity-check the path / external URL by ourselves somehow.
