### ISSUE TITLE
concurrent map iteration and map write in remote storage

### ISSUE THREAD

**Issue by roastiek** [prometheus/prometheus#12747]
### What did you do?

Invalid rules got deployed because of #12663 that resulted in infinite reload config cycle (caused by helper component). That cycle lead to crash of the busiest instance with `fatal error: concurrent map iteration and map write`.

From logs I'm suppecting race in acces to https://github.com/prometheus/prometheus/blob/cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0/storage/remote/write.go#L67 between https://github.com/prometheus/prometheus/blob/cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0/storage/remote/storage.go#L80
and https://github.com/prometheus/prometheus/blob/cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0/storage/remote/write.go#L174

### What did you see instead? Under which circumstances?

Reload of config should never crash prometheus.

### System information

linux, kubernetes

### Prometheus version

```text
version 2.46.0
```

### Logs

```text
fatal error: concurrent map iteration and map write

goroutine 2720823602 [running]:
github.com/prometheus/prometheus/storage/remote.(*Storage).Notify(0xc730b772c0?)
	github.com/prometheus/prometheus/storage/remote/storage.go:80 +0x71
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0xc730b772c0)
	github.com/prometheus/prometheus/tsdb/head_append.go:846 +0xc3
github.com/prometheus/prometheus/tsdb.dbAppender.Commit({{0x3ee6b40?, 0xc730b772c0?}, 0xc000f17e00?})
	github.com/prometheus/prometheus/tsdb/db.go:1084 +0x35
github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0xcab54460c0)
	github.com/prometheus/prometheus/storage/fanout.go:206 +0x3f
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1()
	github.com/prometheus/prometheus/scrape/scrape.go:1336 +0x45
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc2c1aa63c0, {0xedc780473?, 0x59aeac0?, 0x59aeac0?}, {0xedc780473?, 0x59aeac0?, 0x59aeac0?}, 0x0)
	github.com/prometheus/prometheus/scrape/scrape.go:1407 +0xef0
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc2c1aa63c0, 0x41a192a264000000?)
	github.com/prometheus/prometheus/scrape/scrape.go:1289 +0x353
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	github.com/prometheus/prometheus/scrape/scrape.go:631 +0xade

goroutine 283 [runnable]:
gopkg.in/yaml%2ev2.(*encoder).emitScalar(0xc7371db340, {0xc503be9ed0, 0x4}, {0x0?, 0x0?}, {0x0, 0x0}, 0x1)
	gopkg.in/yaml.v2@v2.4.0/encode.go:386 +0x228
gopkg.in/yaml%2ev2.(*encoder).intv(0x2cc9920?, {0x0, 0x0}, {0x2cc9920?, 0xc649035188?, 0xc7371db340?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:349 +0xb1
gopkg.in/yaml%2ev2.(*encoder).marshal(0x2c4a680?, {0x0, 0x0}, {0x2cc9920?, 0xc649035188?, 0x59e0658?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:174 +0x6ff
gopkg.in/yaml%2ev2.(*encoder).structv.func1()
	gopkg.in/yaml.v2@v2.4.0/encode.go:226 +0x248
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc7371db340, {0x0?, 0x0}, 0xcce26d0b90)
	gopkg.in/yaml.v2@v2.4.0/encode.go:256 +0x143
gopkg.in/yaml%2ev2.(*encoder).structv(0xc7371db340, {0x0, 0x0}, {0x344f480?, 0xc649035170?, 0x1c?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:213 +0xef
gopkg.in/yaml%2ev2.(*encoder).marshal(0x2b2283d?, {0x0, 0x0}, {0x344f480?, 0xc649035170?, 0x0?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:160 +0x9f9
gopkg.in/yaml%2ev2.(*encoder).structv.func1()
	gopkg.in/yaml.v2@v2.4.0/encode.go:226 +0x248
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc7371db340, {0x0?, 0x0}, 0xcce26d0f30)
	gopkg.in/yaml.v2@v2.4.0/encode.go:256 +0x143
gopkg.in/yaml%2ev2.(*encoder).structv(0xc7371db340, {0x0, 0x0}, {0x352c080?, 0xc649035040?, 0x6?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:213 +0xef
gopkg.in/yaml%2ev2.(*encoder).marshal(0x2fc5c60?, {0x0, 0x0}, {0x352c080?, 0xc649035040?, 0x0?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:160 +0x9f9
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc7371db340?, {0x0, 0x0}, {0x2fc5c60?, 0xc649035040?, 0xcce26d11f0?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:154 +0x855
gopkg.in/yaml%2ev2.(*encoder).marshalDoc(0xc7371db340, {0x0, 0x0}, {0x2fc5c60?, 0xc649035040?, 0x40ed6a?})
	gopkg.in/yaml.v2@v2.4.0/encode.go:93 +0xe5
gopkg.in/yaml%2ev2.Marshal({0x2fc5c60?, 0xc649035040})
	gopkg.in/yaml.v2@v2.4.0/yaml.go:203 +0x379
github.com/prometheus/prometheus/storage/remote.toHash({0x2fc5c60?, 0xc649035040?})
	github.com/prometheus/prometheus/storage/remote/storage.go:221 +0x27
github.com/prometheus/prometheus/storage/remote.(*WriteStorage).ApplyConfig(0xc00062e780, 0xc71d11b200)
	github.com/prometheus/prometheus/storage/remote/write.go:138 +0x1f1
github.com/prometheus/prometheus/storage/remote.(*Storage).ApplyConfig(0xc0004f5b40, 0xc71d11b200)
	github.com/prometheus/prometheus/storage/remote/storage.go:91 +0xd3
main.reloadConfig({0x7ffd49c451bc, 0x1f}, 0x1?, 0x1, {0x3eb2420, 0xc00065d9c0}, 0xc0005252c0, {0xc000b27680, 0xa, 0xa})
	github.com/prometheus/prometheus/cmd/prometheus/main.go:1256 +0x437
main.main.func20()
	github.com/prometheus/prometheus/cmd/prometheus/main.go:973 +0x1b3
github.com/oklog/run.(*Group).Run.func1({0xc00099ed80?, 0xc000523d70?})
	github.com/oklog/run@v1.1.0/group.go:38 +0x2f
created by github.com/oklog/run.(*Group).Run
	github.com/oklog/run@v1.1.0/group.go:37 +0x69
```

**Comment by timur-ND** [comment]
Probably we got almost the same error in docker. Prometheus version 2.47.0. How it can be fixed and what is the reason of such behaviour?

`ts=2023-10-06T04:55:06.620Z caller=main.go:1229 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
fatal error: concurrent map iteration and map write

goroutine 28846 [running]:
github.com/prometheus/prometheus/storage/remote.(*Storage).Notify(0xc4e715dcc0?)
	/app/storage/remote/storage.go:80 +0x4f
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0xc4e715dcc0)
	/app/tsdb/head_append.go:841 +0xbe
github.com/prometheus/prometheus/tsdb.dbAppender.Commit({{0x3e2bda0?, 0xc4e715dcc0?}, 0xc0002a5d00?})
	/app/tsdb/db.go:1086 +0x2f
github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0xc5157cd600)
	/app/storage/fanout.go:206 +0x33
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1()
	/app/scrape/scrape.go:1342 +0x3f
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc143394f00, {0xedcb18a29?, 0x5967560?, 0x5967560?}, {0xedcb18a29?, 0x5967560?, 0x5967560?}, 0x0)
	/app/scrape/scrape.go:1413 +0xee6
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc143394f00, 0x18af3031a70?)
	/app/scrape/scrape.go:1295 +0x336
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync in goroutine 20030
	/app/scrape/scrape.go:642 +0xafd

goroutine 1 [chan receive, 4539 minutes]:
github.com/oklog/run.(*Group).Run(0xc000e29850)
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:43 +0x155
main.main()
	/app/cmd/prometheus/main.go:1163 +0xa98c

goroutine 100 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0006c7400)
	/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

goroutine 215 [select]:
github.com/prometheus/prometheus/util/logging.(*Deduper).run(0xc001104040)
	/app/util/logging/dedupe.go:75 +0xdc
created by github.com/prometheus/prometheus/util/logging.Dedupe in goroutine 1
	/app/util/logging/dedupe.go:61 +0x10a

goroutine 223 [select]:
github.com/prometheus/prometheus/storage/remote.(*WriteStorage).run(0xc0009f2b40)
	/app/storage/remote/write.go:115 +0xc5
created by github.com/prometheus/prometheus/storage/remote.NewWriteStorage in goroutine 1
	/app/storage/remote/write.go:107 +0x44d

goroutine 360 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
	/usr/local/go/src/os/signal/signal.go:151 +0x1f`

**Comment by machine424** [comment]
I pushed a test that reproduces this (apparently it's not the first time an `ApplyConfig` is part of a race confition) here https://github.com/prometheus/prometheus/pull/13135

I'll push a fix as well.
