### ISSUE TITLE
panic: runtime error: index out of range with native histograms

### ISSUE THREAD

**Issue by krajorama** [prometheus/prometheus#12837]
### What did you do?

See bug report in Mimir. Reproduced with Prometheus clean.
https://github.com/grafana/mimir/issues/5576

### What did you expect to see?

No panic during WAL reload

### What did you see instead? Under which circumstances?

Panic.

### System information

Linux 5.15.0-82-generic #91~20.04.1-Ubuntu SMP Fri Aug 18 16:24:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Prometheus version

```text
version=2.47.0, branch=main, revision=4419399e4e831052bc9b8b4f26a8e7cf337091b0)
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s

scrape_configs:
```

### Logs

```text
$ ~/go/github.com/krajorama/prometheus/prometheus --enable-feature native-histograms --config.file=prometheus.yml --storage.tsdb.path=`pwd`/db
ts=2023-09-13T09:55:38.993Z caller=main.go:206 level=info msg="Experimental native histogram support enabled."
ts=2023-09-13T09:55:38.993Z caller=main.go:539 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2023-09-13T09:55:38.993Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.47.0, branch=main, revision=4419399e4e831052bc9b8b4f26a8e7cf337091b0)"
ts=2023-09-13T09:55:38.993Z caller=main.go:588 level=info build_context="(go=go1.20.8, platform=linux/amd64, user=krajo@hpkrajo, date=20230913-09:47:33, tags=netgo,builtinassets,stringlabels)"
ts=2023-09-13T09:55:38.993Z caller=main.go:589 level=info host_details="(Linux 5.15.0-82-generic #91~20.04.1-Ubuntu SMP Fri Aug 18 16:24:39 UTC 2023 x86_64 hpkrajo (none))"
ts=2023-09-13T09:55:38.993Z caller=main.go:590 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2023-09-13T09:55:38.993Z caller=main.go:591 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-09-13T09:55:38.995Z caller=web.go:566 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2023-09-13T09:55:38.997Z caller=main.go:1024 level=info msg="Starting TSDB ..."
ts=2023-09-13T09:55:38.999Z caller=tls_config.go:274 level=info component=web msg="Listening on" address=[::]:9090
ts=2023-09-13T09:55:38.999Z caller=tls_config.go:277 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2023-09-13T09:55:39.003Z caller=head.go:600 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2023-09-13T09:55:39.003Z caller=head.go:681 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=4.26µs
ts=2023-09-13T09:55:39.003Z caller=head.go:689 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2023-09-13T09:55:39.568Z caller=head.go:725 level=info component=tsdb msg="WAL checkpoint loaded"
ts=2023-09-13T09:55:40.507Z caller=head.go:760 level=info component=tsdb msg="WAL segment loaded" segment=858 maxSegment=870
ts=2023-09-13T09:55:41.780Z caller=head.go:760 level=info component=tsdb msg="WAL segment loaded" segment=859 maxSegment=870
ts=2023-09-13T09:55:42.775Z caller=head.go:760 level=info component=tsdb msg="WAL segment loaded" segment=860 maxSegment=870
panic: runtime error: index out of range [26] with length 26

goroutine 494 [running]:
github.com/prometheus/prometheus/tsdb/chunkenc.counterResetInAnyBucket({0xc01625d380?, 0x0?, 0x7f05fd752d00?}, {0xc014367860, 0x1a, 0x80?}, {0xc0172a0c18, 0x3, 0x0?}, {0xc01590c2b0, ...})
	/home/krajo/go/github.com/krajorama/prometheus/tsdb/chunkenc/histogram.go:394 +0x23e
github.com/prometheus/prometheus/tsdb/chunkenc.(*HistogramAppender).appendable(0xc00a7f8000, 0xc017699b00)
	/home/krajo/go/github.com/krajorama/prometheus/tsdb/chunkenc/histogram.go:300 +0x225
github.com/prometheus/prometheus/tsdb/chunkenc.(*HistogramAppender).AppendHistogram(0xc00a7f8000, 0x18a8ad99576?, 0xc008f54f02?, 0xc017699b00, 0x0)
	/home/krajo/go/github.com/krajorama/prometheus/tsdb/chunkenc/histogram.go:637 +0x8e
github.com/prometheus/prometheus/tsdb.(*memSeries).appendHistogram(0xc007ed5380, 0x18a8ad99576, 0xc017699b00, 0x0, {0xc0001985a0?, 0x0?, 0x0?})
	/home/krajo/go/github.com/krajorama/prometheus/tsdb/head_append.go:1178 +0xdd
github.com/prometheus/prometheus/tsdb.(*walSubsetProcessor).processWALSamples(0xc00e631848, 0xc000053800, 0x0?, 0x0?)
	/home/krajo/go/github.com/krajorama/prometheus/tsdb/head_wal.go:623 +0x675
github.com/prometheus/prometheus/tsdb.(*Head).loadWAL.func2(0x0?)
	/home/krajo/go/github.com/krajorama/prometheus/tsdb/head_wal.go:106 +0x4d
created by github.com/prometheus/prometheus/tsdb.(*Head).loadWAL
	/home/krajo/go/github.com/krajorama/prometheus/tsdb/head_wal.go:105 +0x31f
```
```

**Comment by krajorama** [comment]
Debugger stopped before bug:

![image](https://github.com/prometheus/prometheus/assets/13435893/d0bf9663-0bd2-43ff-bcd8-d47bd62b5fde)

**Comment by krajorama** [comment]
Requirement: both histogram and float histogram chunks write the layout first which contains the spans first. Then comes the buckets and subsequent writes do not write the spans, only the buckets. So adding / removing empty spans is ok, as long as the offsets of buckets doesn't change.
