### ISSUE TITLE
Inaccessible data disk may cause prometheus panic

### ISSUE THREAD

**Issue by onlyangelss** [prometheus/prometheus#13560]
### What did you do?

In my environment, Prometheus(2.49.1 version) uses CEPH to store data. I first construct an inaccessible exception for ceph storage, and then use PromQL to query metrics data within a 3-hour range.

### What did you expect to see?
When there is a storage exception, I expect Prometheus not to exit.

### What did you see instead? Under which circumstances?

When storage is inaccessible, querying historical metrics data can cause Prometheus panic.

I debugged the coredump file and found the code that caused the panic issue.  （remarks：I pasted the stack log below）.

not checking for invalid values returned by the  encoding.NewDecbufAt()  function. 
- For example, this call that occurred at line 1691 of /app/tsdb/index/index.go (prometheus 2.49.1 version).
```
d2 := encoding.NewDecbufAt(r.b, int(postingsOff), castagnoliTable)
_, p, err := r.dec.Postings(d2.Get())
```
-  Function encoding.NewDecbufAt()  may return invalid data
```
// function defined in file：github.com/prometheus/prometheus/tsdb/encoding.NewDecbufAt 
func NewDecbufAt(bs ByteSlice, off int, castagnoliTable *crc32.Table) Decbuf {
        ...
	...
	...
	if bs.Len() < off+4+l+4 {
		return Decbuf{E: ErrInvalidSize}
	}
	...
	...
	...
}
```
-  Always check the return value of function encoding.NewDecbufAt()
```
if d2.Err() != nil {
	// do something
}
```

### System information

Linux 3.10.0-1127.19.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.49.1 (branch: HEAD, revision: 43e14844a33b65e2a396e3944272af8b3a494071)
  build user:       root@iZj6cbd6whuz6nectxzcczZ
  build date:       20240208-01:25:40
  go version:       go1.20.14
  platform:         linux/amd64
  tags:             unknown
```

### Logs

- log
```
unexpected fault address 0x7f13c1f6d0ec
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f13c1f6d0ec pc=0x26bf660]

goroutine 75898 [running]:
runtime.throw({0x35f7806?, 0x1000?})
	/usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0xc04120b428 sp=0xc04120b3f8 pc=0x43b2bc
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:858 +0x116 fp=0xc04120b488 sp=0xc04120b428 pc=0x451ff6
encoding/binary.bigEndian.Uint32(...)
	/usr/local/go/src/encoding/binary/binary.go:158
github.com/prometheus/prometheus/tsdb/encoding.NewDecbufAt({0x3f4fee8, 0xc0018fc990}, 0x5b540ec, 0xc000158400)
	/app/tsdb/encoding/encoding.go:126 +0xa0 fp=0xc04120b528 sp=0xc04120b488 pc=0x26bf660
github.com/prometheus/prometheus/tsdb/index.(*Reader).Postings(0xc0018c5ec0, {0x3f6e2e0, 0xc041d646f0?}, {0x35fce75?, 0x1?}, {0xc04165df60, 0x1, 0x1})
	/app/tsdb/index/index.go:1691 +0xd25 fp=0xc04120b7a0 sp=0xc04120b528 pc=0x26cde45
github.com/prometheus/prometheus/tsdb.blockIndexReader.Postings({{0x3f80e50?, 0xc0018c5ec0?}, 0xc0019642c0?}, {0x3f6e2e0?, 0xc041d646f0?}, {0x35fce75?, 0x1?}, {0xc04165df60, 0x1, 0x1})
	/app/tsdb/block.go:504 +0x7f fp=0xc04120b8d0 sp=0xc04120b7a0 pc=0x2733eff
github.com/prometheus/prometheus/tsdb.(*blockIndexReader).Postings(0x0?, {0x3f6e2e0?, 0xc041d646f0?}, {0x35fce75?, 0xc00c7dc968?}, {0xc04165df60?, 0x1?, 0xc00c7dc980?})
	<autogenerated>:1 +0x6a fp=0xc04120b930 sp=0xc04120b8d0 pc=0x2799f2a
github.com/prometheus/prometheus/tsdb.postingsForMatcher({0x3f6e2e0, 0xc041d646f0}, {0x3f80eb8, 0xc04105bf38}, 0xc041d644e0)
	/app/tsdb/querier.go:374 +0x1c7 fp=0xc04120b9c0 sp=0xc04120b930 pc=0x2779a07
github.com/prometheus/prometheus/tsdb.PostingsForMatchers({0x3f6e2e0, 0xc041d646f0}, {0x3f80eb8, 0xc04105bf38}, {0xc001bddfa8?, 0x1, 0x1})
	/app/tsdb/querier.go:338 +0x92a fp=0xc04120bc40 sp=0xc04120b9c0 pc=0x277906a
github.com/prometheus/prometheus/tsdb.(*blockQuerier).Select(0xc001bddfb8, {0x3f6e2e0?, 0xc041d646f0?}, 0x1, 0xc041d2afc0, {0xc001bddfa8?, 0x453289?, 0x40?})
	/app/tsdb/querier.go:135 +0x85 fp=0xc04120bd38 sp=0xc04120bc40 pc=0x27777c5
github.com/prometheus/prometheus/storage.(*genericQuerierAdapter).Select(0xc0397297e8?, {0x3f6e2e0?, 0xc041d646f0?}, 0xaf?, 0xc01145ddc0?, {0xc001bddfa8?, 0x4a4c67?, 0x4a549e?})
	/app/storage/generic.go:66 +0x37 fp=0xc04120bd98 sp=0xc04120bd38 pc=0x268e557
github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Select(0xc041d64870, {0x3f6e2e0?, 0xc041d646f0}, 0x4?, 0xc041d2afc0, {0xc001bddfa8?, 0x1, 0x1})
	/app/storage/merge.go:114 +0x5a2 fp=0xc04120be78 sp=0xc04120bd98 pc=0x2690362
github.com/prometheus/prometheus/storage.(*querierAdapter).Select(0x0?, {0x3f6e2e0?, 0xc041d646f0?}, 0x80?, 0x408e40?, {0xc001bddfa8?, 0xc01145df38?, 0x408897?})
	/app/storage/generic.go:92 +0x2d fp=0xc04120bed8 sp=0xc04120be78 pc=0x268e6ed
github.com/prometheus/prometheus/storage.(*genericQuerierAdapter).Select(0xc01145dfd0?, {0x3f6e2e0?, 0xc041d646f0?}, 0x80?, 0xc077cb4d10?, {0xc001bddfa8?, 0x0?, 0x404e0014ceccb401?})
	/app/storage/generic.go:66 +0x37 fp=0xc04120bf38 sp=0xc04120bed8 pc=0x268e557
github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Select.func2({0x3f6eb30?, 0xc041d648d0?})
	/app/storage/merge.go:133 +0x8a fp=0xc04120bfc0 sp=0xc04120bf38 pc=0x26906aa
github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Select.func5()
	/app/storage/merge.go:134 +0x2b fp=0xc04120bfe0 sp=0xc04120bfc0 pc=0x26905eb
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc04120bfe8 sp=0xc04120bfe0 pc=0x471281
created by github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Select in goroutine 75875
	/app/storage/merge.go:129 +0x185
```

- stack log （debug the coredump file）
```
(dlv) bt
 0  0x0000000000472b21 in runtime.raise
    at /usr/local/go/src/runtime/sys_linux_amd64.s:154
 1  0x0000000000452325 in runtime.dieFromSignal
    at /usr/local/go/src/runtime/signal_unix.go:903
 2  0x0000000000452a26 in runtime.sigfwdgo
    at /usr/local/go/src/runtime/signal_unix.go:1108
 3  0x0000000000451025 in runtime.sigtrampgo
    at /usr/local/go/src/runtime/signal_unix.go:432
 4  0x0000000000472b21 in runtime.raise
    at /usr/local/go/src/runtime/sys_linux_amd64.s:153
 5  0x0000000000452325 in runtime.dieFromSignal
    at /usr/local/go/src/runtime/signal_unix.go:903
 6  0x000000000043b67a in runtime.crash
    at /usr/local/go/src/runtime/signal_unix.go:985
 7  0x000000000043b67a in runtime.fatalthrow.func1
    at /usr/local/go/src/runtime/panic.go:1174
 8  0x000000000046f48a in runtime.systemstack
    at /usr/local/go/src/runtime/asm_amd64.s:509
 9  0x000000000046f428 in runtime.systemstack_switch
    at /usr/local/go/src/runtime/asm_amd64.s:474
10  0x000000000043b5c5 in runtime.fatalthrow
    at /usr/local/go/src/runtime/panic.go:1163
11  0x000000000043b2bc in runtime.throw
    at /usr/local/go/src/runtime/panic.go:1077
12  0x0000000000451ff6 in runtime.sigpanic
    at /usr/local/go/src/runtime/signal_unix.go:858
13  0x00000000026bf660 in github.com/prometheus/prometheus/tsdb/encoding.NewDecbufAt
    at /app/tsdb/encoding/encoding.go:128
14  0x00000000026cde45 in github.com/prometheus/prometheus/tsdb/index.(*Reader).Postings
    at /app/tsdb/index/index.go:1691
15  0x0000000002733eff in github.com/prometheus/prometheus/tsdb.blockIndexReader.Postings
    at /app/tsdb/block.go:504
16  0x0000000002799f2a in github.com/prometheus/prometheus/tsdb.(*blockIndexReader).Postings
    at <autogenerated>:1
17  0x0000000002779a07 in github.com/prometheus/prometheus/tsdb.postingsForMatcher
    at /app/tsdb/querier.go:374
18  0x000000000277906a in github.com/prometheus/prometheus/tsdb.PostingsForMatchers
    at /app/tsdb/querier.go:338
19  0x00000000027777c5 in github.com/prometheus/prometheus/tsdb.(*blockQuerier).Select
    at /app/tsdb/querier.go:135
20  0x000000000268e557 in github.com/prometheus/prometheus/storage.(*genericQuerierAdapter).Select
    at /app/storage/generic.go:66
21  0x0000000002690362 in github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Select
    at /app/storage/merge.go:114
22  0x000000000268e6ed in github.com/prometheus/prometheus/storage.(*querierAdapter).Select
    at /app/storage/generic.go:92
23  0x000000000268e557 in github.com/prometheus/prometheus/storage.(*genericQuerierAdapter).Select
    at /app/storage/generic.go:66
24  0x00000000026906aa in github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Select.func2
    at /app/storage/merge.go:133
25  0x00000000026905eb in github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Select.func5
    at /app/storage/merge.go:134
26  0x0000000000471281 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1650
```
```

**Comment by roidelapluie** [comment]
Thanks for your issue. This is kinda expected. Prometheus is a database that needs to write to disk. All bets are off when the storage is not reliable, and it is better to crash than to keep running in a very unknown state. Therefore I am closing this issue.
