### ISSUE TITLE
Random scrape targets get stock

### ISSUE THREAD

**Issue by eskytthe** [prometheus/prometheus#13619]
### What did you do?

Running 3 independent prometheus instances on 3 hosts. From prometheus version  2.49.0 we are facing random scrape targets get stock on one of the servers. Restarting the prometheus service on the stock server resolve the problem. 

Looks like prometheus is getting stock in some goroutines Lock issue. Include debug log further down in this issue. 

### What did you expect to see?

No stock scrape targets 

### What did you see instead? Under which circumstances?

00:45 (Denmark GMT+1) this morning we have random stock scrape targets on one of our 3 prometheus servers

One example of stock scrape targets: 
![Screenshot from 2024-02-21 07-48-39](https://github.com/prometheus/prometheus/assets/2544204/742acb55-ca11-4de1-a8e6-d905ae215601)

Prometheus service did hang on subsequently restart:
```
Feb 21 09:02:50 prometheus-p101 prometheus[256640]: ts=2024-02-21T08:02:50.738Z caller=main.go:874 level=warn msg="Received SIGTERM, exiting gracefully..."
Feb 21 09:02:50 prometheus-p101 prometheus[256640]: ts=2024-02-21T08:02:50.738Z caller=main.go:898 level=info msg="Stopping scrape discovery manager..."
Feb 21 09:02:50 prometheus-p101 prometheus[256640]: ts=2024-02-21T08:02:50.738Z caller=main.go:912 level=info msg="Stopping notify discovery manager..."
Feb 21 09:02:50 prometheus-p101 prometheus[256640]: ts=2024-02-21T08:02:50.738Z caller=manager.go:160 level=info component="rule manager" msg="Stopping rule manager..."
Feb 21 09:02:50 prometheus-p101 prometheus[256640]: ts=2024-02-21T08:02:50.738Z caller=main.go:908 level=info msg="Notify discovery manager stopped"
Feb 21 09:02:50 prometheus-p101 prometheus[256640]: ts=2024-02-21T08:02:50.738Z caller=main.go:894 level=info msg="Scrape discovery manager stopped"
Feb 21 09:02:50 prometheus-p101 systemd[1]: Stopping prometheus.service...
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: State 'stop-sigterm' timed out. Killing.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256640 (prometheus) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256651 (prometheus) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256653 (n/a) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256654 (n/a) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256658 (n/a) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256659 (prometheus) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256660 (n/a) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 256661 (n/a) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 257000 (n/a) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 279274 (n/a) with signal SIGKILL.
Feb 21 09:04:20 prometheus-p101 systemd[1]: prometheus.service: Killing process 512787 (n/a) with signal SIGKILL.
Feb 21 09:04:23 prometheus-p101 systemd[1]: prometheus.service: Main process exited, code=killed, status=9/KILL
Feb 21 09:04:23 prometheus-p101 systemd[1]: prometheus.service: Failed with result 'timeout'.
Feb 21 09:04:23 prometheus-p101 systemd[1]: Stopped prometheus.service.
Feb 21 09:04:23 prometheus-p101 systemd[1]: prometheus.service: Consumed 1d 16h 52min 39.470s CPU time, read 693.5K from disk, written 0B to disk, received 222.3G IP traffic, sent 5.5G IP traffic.
Feb 21 09:04:23 prometheus-p101 systemd[1]: Started prometheus.service.


### System information

Linux 6.1.77 x86_64

### Prometheus version

```text
prometheus, version 2.49.0 (branch: unknown, revision: unknown)
  build user:       nix@nixpkgs
  build date:       unknown
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             builtinassets
```

**Comment by eskytthe** [comment]
Log from log from debug/pprof/goroutine?debug=2 - taken 9:00 oclock GMT+1 today
[prometheus-debug-9oclock.txt](https://github.com/prometheus/prometheus/files/14357467/prometheus-debug-9oclock.txt)

**Comment by roidelapluie** [comment]
Here is an example goroutine that is stuck:

```
goroutine 3439 [sync.RWMutex.RLock, 495 minutes]:
sync.runtime_SemacquireRWMutexR(0x2ec45c0?, 0x60?, 0x2559?)
	runtime/sema.go:82 +0x25
sync.(*RWMutex).RLock(...)
	sync/rwmutex.go:71
github.com/prometheus/prometheus/tsdb.(*stripeSeries).getByID(0xc000749ce0, 0x255a)
	github.com/prometheus/prometheus/tsdb/head.go:1925 +0x75
github.com/prometheus/prometheus/tsdb.(*headAppender).Append(0xc14d44d040, 0x1000080010000?, {0xc2d3c3e5a0, 0x5, 0x5}, 0x18dc8e8b310, 0x0)
	github.com/prometheus/prometheus/tsdb/head_append.go:320 +0xf2
github.com/prometheus/prometheus/storage.(*fanoutAppender).Append(0xc203b898c0, 0x2?, {0xc2d3c3e5a0, 0x5, 0x5}, 0xc2d3fb97e0?, 0x0?)
	github.com/prometheus/prometheus/storage/fanout.go:150 +0x4b
github.com/prometheus/prometheus/scrape.(*timeLimitAppender).Append(0xc2d3c3e5a0?, 0xc065271ce0?, {0xc2d3c3e5a0?, 0x4a?, 0xc045f9d62d?}, 0x5?, 0x69e865?)
	github.com/prometheus/prometheus/scrape/target.go:353 +0x2a
github.com/prometheus/prometheus/scrape.(*scrapeLoop).append(0xc19c45a600, {0x3f8ad08, 0xc203b898c0}, {0xc045f8e000, 0x2f7ab, 0x3b538}, {0xc0caef7770, 0x28}, {0x35ecf2ca, 0xedd673085, ...})
	github.com/prometheus/prometheus/scrape/scrape.go:1567 +0x1195
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc19c45a600, {0xedd673085?, 0x5b34d80?, 0x5b34d80?}, {0xedd673085?, 0x5b34d80?, 0x5b34d80?}, 0x0)
	github.com/prometheus/prometheus/scrape/scrape.go:1285 +0xb9f
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc19c45a600, 0xc0028f2ae0?)
	github.com/prometheus/prometheus/scrape/scrape.go:1180 +0x336
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync in goroutine 3350
	github.com/prometheus/prometheus/scrape/scrape.go:492 +0xbfd
```

@bboreham @jesusvazquez any idea?

**Comment by bboreham** [comment]
You say the problem started with 2.49.0; what was the last version where you didn't see the problem?

**Comment by bboreham** [comment]
I wonder about this: https://github.com/prometheus/prometheus/commit/ce4e757704866ad16bd456e1140cdfe45b380601#diff-d9f058bd14a07ebec78d70aaa8d6e8e705bc09086e338b74b12666e7ac121605R1826

**Comment by bboreham** [comment]
Changed my mind - that is in a local function, so the `defer` executes almost immediately.

**Comment by bboreham** [comment]
Anything earlier in the log, signs of a panic, say?

**Comment by eskytthe** [comment]
> Anything earlier in the log, signs of a panic, say?

No unfortunately not. Have tried also to look at other services then prometheus, and  looking after warnings and errors - nothing.

**Comment by bboreham** [comment]
Would you be willing to run the build produced by the Prometheus project for a while, as a comparison?

**Comment by eskytthe** [comment]
> Would you be willing to run the build produced by the Prometheus project for a while, as a comparison?

Yes maybe - but will be away for ~ 2 weeks from today -  will look about it is possible when returning.

**Comment by eskytthe** [comment]
Btw another observation:

Every time we have seen the problem, do scraping from our kube-stabte-metrics hang - https://github.com/kubernetes/kube-state-metrics. We run ~ 3000 pod in our k8s cluster this give ~ 300K lines of data to read from the kube-state-metrics exporter. 

Last time also most of our kafka targets did hang ~ 14k lines for every kafka host - https://github.com/prometheus/jmx_exporter

So  the bug seems to be connected with targes  with a larger amount of data.

**Comment by krajorama** [comment]
I wrote a little python code to find the go routines that are around 500 minutes stuck form the provided profile.

```
import re

p = re.compile('.* ([0-9]+) minutes]:')


def stateStart(line):
    m = p.match(line)
    if m is None:
        return False
    minutes = int(m.group(1))
    if minutes > 1000 or minutes < 400:
        return False
    print("")
    print(line, end='')
    return True

def stateKeep(line):
    if len(line.strip()) == 0:
        return False
    print(line, end='')
    return True

f = open("prometheus-debug-9oclock.txt", "r")
lines = f.readlines()
f.close()
keep = False
for line in lines:
    if keep:
        keep = stateKeep(line)
    else:
        keep = stateStart(line)
```

[prometheus-debug-9oclock-stuck.txt.gz](https://github.com/user-attachments/files/19845430/prometheus-debug-9oclock-stuck.txt.gz)

**Comment by krajorama** [comment]
There's a single goroutine doing TSDB Append that's waiting for the write lock for `Head.series.locks[i]` which is the ith stripe of series. It's trying to create a new series. All others doing append are waiting on the read lock to check if they need to create a series  - which will be blocked until the [writer finishes](https://pkg.go.dev/sync#RWMutex). So something is holding a read/write lock already to the ith stripeseries.
```
goroutine 3785 [sync.RWMutex.Lock, 495 minutes]:
sync.runtime_SemacquireRWMutex(0x1149a55a?, 0xc0?, 0x94cde480?)
        runtime/sema.go:87 +0x25
sync.(*RWMutex).Lock(0xc000e95240?)
        sync/rwmutex.go:152 +0x6a
github.com/prometheus/prometheus/tsdb.(*stripeSeries).getOrSet(0xc000749ce0, 0x4a04a50bc70b20c9, {0xc094cde480, 0xc, 0xc}, 0xc347ccd3c0)
        github.com/prometheus/prometheus/tsdb/head.go:1977 +0x24b
github.com/prometheus/prometheus/tsdb.(*Head).getOrCreateWithID(0xc00009f400, 0x1149a55a, 0xc094cde480?, {0xc094cde480, 0xc, 0xc})
        github.com/prometheus/prometheus/tsdb/head.go:1659 +0x8e
github.com/prometheus/prometheus/tsdb.(*Head).getOrCreate(0xc00009f400, 0xc?, {0xc094cde480, 0xc, 0xc})
        github.com/prometheus/prometheus/tsdb/head.go:1655 +0x75
github.com/prometheus/prometheus/tsdb.(*headAppender).Append(0xc22e2d37c0, 0x0?, {0xc094cde480, 0xc, 0xc}, 0x18dc8e89870, 0x0)
        github.com/prometheus/prometheus/tsdb/head_append.go:334 +0x78d
github.com/prometheus/prometheus/storage.(*fanoutAppender).Append(0xc2a50a9480, 0xc19bce7580?, {0xc094cde480, 0xc, 0xc}, 0xb?, 0x0?)
        github.com/prometheus/prometheus/storage/fanout.go:150 +0x4b
github.com/prometheus/prometheus/scrape.(*timeLimitAppender).Append(0xc094cde480?, 0xc?, {0xc094cde480?, 0xc0e299bcc8?, 0xc2e357ea6f?}, 0x5?, 0x69e865?)
        github.com/prometheus/prometheus/scrape/target.go:353 +0x2a
github.com/prometheus/prometheus/scrape.(*scrapeLoop).append(0xc19da2b400, {0x3f8ad08, 0xc2a50a9480}, {0xc2e3080000, 0x5d38f4, 0x641ce8}, {0xc0abcec7b0, 0x28}, {0x3813152e, 0xedd673
081, ...})
        github.com/prometheus/prometheus/scrape/scrape.go:1567 +0x1195
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc19da2b400, {0xedd673081?, 0x5b34d80?, 0x5b34d80?}, {0xedd673081?, 0x5b34d80?, 0x5b34d80?}, 0x0)
        github.com/prometheus/prometheus/scrape/scrape.go:1285 +0xb9f
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc19da2b400, 0xc157204c60?)
        github.com/prometheus/prometheus/scrape/scrape.go:1180 +0x336
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync in goroutine 3073
        github.com/prometheus/prometheus/scrape/scrape.go:492 +0xbfd
```

**Comment by krajorama** [comment]
And this is the stack trace that has been waiting the longest:
```
goroutine 2255 [sync.Mutex.Lock, 510 minutes]:
sync.runtime_SemacquireMutex(0xc0004e1400?, 0x3?, 0xffffffffffffffff?)
        runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc0a3409a40)
        sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
        sync/mutex.go:90
sync.(*RWMutex).Lock(0xc358b35df8?)
        sync/rwmutex.go:147 +0x31
github.com/prometheus/prometheus/tsdb.(*Head).mmapHeadChunks(0xc00009f400)
        github.com/prometheus/prometheus/tsdb/head.go:1696 +0x1b9
github.com/prometheus/prometheus/tsdb.(*DB).run(0xc0006a4800, {0x3f855b8, 0xc000626d20})
        github.com/prometheus/prometheus/tsdb/db.go:995 +0x372
created by github.com/prometheus/prometheus/tsdb.open in goroutine 257
        github.com/prometheus/prometheus/tsdb/db.go:929 +0x1405
```

Code:
```
func (h *Head) mmapHeadChunks() {
	var count int
	for i := 0; i < h.series.size; i++ {
		h.series.locks[i].RLock()
		for _, series := range h.series.series[i] {
			series.Lock()  // <--- waiting here
			count += series.mmapChunks(h.chunkDiskMapper)
			series.Unlock()
		}
		h.series.locks[i].RUnlock()
	}
	h.metrics.mmapChunksTotal.Add(float64(count))
}
```

**Comment by eskytthe** [comment]
Status from our prometheus installation: Have not see the problem since my last reporting https://github.com/prometheus/prometheus/issues/13619#issuecomment-1996874841. We are running ver. 2.55.0 for now ( will update to ver. 3.1.0 soon)
