### ISSUE TITLE
OOO: Panic in out of order query code

### ISSUE THREAD

**Issue by krajorama** [prometheus/prometheus#14822]
### What did you do?

Run queries against latest Prometheus TSDB.
Out of order is enabled and there are out of order samples.

### What did you expect to see?

No panic

### What did you see instead? Under which circumstances?

```
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:650 +0x112
2024-09-03 09:06:01.136	created by google.golang.org/grpc.(*Server).initServerWorkers in goroutine 1
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:637 +0x25
2024-09-03 09:06:01.136	google.golang.org/grpc.(*Server).serverWorker(0xc002eba000)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1029 +0x8b
2024-09-03 09:06:01.136	google.golang.org/grpc.(*Server).serveStreams.func2.1()
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1794 +0xe3a
2024-09-03 09:06:01.136	google.golang.org/grpc.(*Server).handleStream(0xc002eba000, {0x3f4f920, 0xc03ca6b200}, 0xc07d576a20)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1680 +0x11e7
2024-09-03 09:06:01.136	google.golang.org/grpc.(*Server).processStreamingRPC(0xc002eba000, {0x3f29fe0, 0xc073df9590}, {0x3f4f920, 0xc03ca6b200}, 0xc07d576a20, 0xc000e6a0c0, 0x5a73280, 0x0)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1516 +0x85
2024-09-03 09:06:01.136	google.golang.org/grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2({0x357ca00, 0xc0022f61a0}, {0x3f35ce8, 0xc07daae000}, 0xc099b2d6f8, 0xc098ec5ee0?)
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/dskit/middleware/grpc_logging.go:87 +0xab
2024-09-03 09:06:01.136	github.com/grafana/dskit/middleware.GRPCServerLog.StreamServerInterceptor({{0x3efd660?, 0xc000010498?}, 0x60?, 0x1d?}, {0x357ca00, 0xc0022f61a0}, {0x3f35ce8, 0xc07daae000}, 0xc099b2d6f8, 0xc0ed310f00)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1525 +0xb2
2024-09-03 09:06:01.136	google.golang.org/grpc.getChainStreamHandler.func1({0x357ca00, 0xc0022f61a0}, {0x3f35ce8, 0xc07daae000})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/opentracing-contrib/go-grpc/server.go:114 +0x34a
2024-09-03 09:06:01.136	github.com/opentracing-contrib/go-grpc.OpenTracingStreamServerInterceptor.func1({0x357ca00, 0xc0022f61a0}, {0x3f35ce8, 0xc07daae000}, 0xc099b2d6f8, 0xc0ed310f40)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1525 +0xb2
2024-09-03 09:06:01.136	google.golang.org/grpc.getChainStreamHandler.func1({0x357ca00, 0xc0022f61a0}, {0x3f364c8, 0xc0d62029c0})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/dskit/middleware/grpc_instrumentation.go:57 +0xbd
2024-09-03 09:06:01.136	github.com/grafana/dskit/middleware.StreamServerInstrumentInterceptor.func1({0x357ca00, 0xc0022f61a0}, {0x3f364c8, 0xc0d62029c0}, 0xc099b2d6f8, 0xc0ed311100)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1525 +0xb2
2024-09-03 09:06:01.136	google.golang.org/grpc.getChainStreamHandler.func1({0x357ca00, 0xc0022f61a0}, {0x3f364c8, 0xc0d62029c0})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/mimir/pkg/querier/api/consistency.go:151 +0x1f9
2024-09-03 09:06:01.136	github.com/grafana/mimir/pkg/querier/api.ReadConsistencyServerStreamInterceptor({0x357ca00, 0xc0022f61a0}, {0x3f364c8, 0xc0d62029c0}, 0xc099b2d6f8?, 0xc0ed311140)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1525 +0xb2
2024-09-03 09:06:01.136	google.golang.org/grpc.getChainStreamHandler.func1({0x357ca00, 0xc0022f61a0}, {0x3f35508, 0xc0d62029e0})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/mimir/pkg/util/noauth/no_auth.go:40 +0x9c
2024-09-03 09:06:01.136	github.com/grafana/mimir/pkg/util/noauth.SetupAuthMiddleware.func2({0x357ca00, 0xc0022f61a0}, {0x3f35508, 0xc0d62029e0}, 0xc099b2d6f8, 0xc0ed311180)
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/dskit/middleware/grpc_auth.go:53 +0xb2
2024-09-03 09:06:01.136	github.com/grafana/dskit/middleware.StreamServerUserHeaderInterceptor({0x357ca00, 0xc0022f61a0}, {0x3f35508, 0xc0d62029e0}, 0x7a782fde4368?, 0xc0ed311180)
2024-09-03 09:06:01.136	/drone/src/vendor/google.golang.org/grpc/server.go:1525 +0xb2
2024-09-03 09:06:01.136	google.golang.org/grpc.getChainStreamHandler.func1({0x357ca00, 0xc0022f61a0}, {0x3f36090, 0xc0d6202a00})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/mimir/pkg/mimir/tracing.go:25 +0xcf
2024-09-03 09:06:01.136	github.com/grafana/mimir/pkg/mimir.ThanosTracerStreamInterceptor({0x357ca00, 0xc0022f61a0}, {0x3f36090, 0xc0d6202a00}, 0xc0d6202a00?, 0x399a8e8)
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/client/ingester.pb.go:3702 +0x107
2024-09-03 09:06:01.136	github.com/grafana/mimir/pkg/ingester/client._Ingester_QueryStream_Handler({0x357ca00, 0xc0022f61a0}, {0x3f34c58, 0xc0d6202a20})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/ingester_activity.go:44 +0xdc
2024-09-03 09:06:01.136	github.com/grafana/mimir/pkg/ingester.(*ActivityTrackerWrapper).QueryStream(0xc0022f61a0, 0xc073df9ce0, {0x3f3cf40, 0xc104700060})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/ingester.go:2123 +0x4db
2024-09-03 09:06:01.136	github.com/grafana/mimir/pkg/ingester.(*Ingester).QueryStream(0xc00329c008, 0xc073df9ce0, {0x3f3cf40, 0xc104700060})
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/ingester.go:2361 +0x438
2024-09-03 09:06:01.136	github.com/grafana/mimir/pkg/ingester.(*Ingester).executeStreamingQuery(0xc00329c008, {0x3f29fe0, 0xc0700ca030}, 0xc000bd9900, 0x191b60be6d8, 0x191b673ad40, {0xc012382b48, 0x1, 0x1}, 0xc0d77ce030, ...)
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/prometheus/prometheus/storage/merge.go:284 +0xa2
2024-09-03 09:06:01.136	github.com/prometheus/prometheus/storage.(*mergeGenericQuerier).Close(0xc0700ca2a0)
2024-09-03 09:06:01.136	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go:605 +0x31
2024-09-03 09:06:01.136	github.com/prometheus/prometheus/tsdb.(*HeadAndOOOChunkQuerier).Close(0xc08ce15ea0)
2024-09-03 09:06:01.136	goroutine 265 [running]:
2024-09-03 09:06:01.136		
2024-09-03 09:06:01.136	[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1c376d1]
2024-09-03 09:06:01.136	panic: runtime error: invalid memory address or nil pointer dereference
```

### System information

Linux

### Prometheus version

```text
ee2b7fdf9d4d4a7fa8d1d9eccae55e5dc802213c
```

**Comment by bboreham** [comment]
Closed by #14831
