### ISSUE TITLE
Flaky `TestDelayedCompaction` test

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#14855]
In the CI step for `Run make GOOPTS=--tags=stringlabels GO_ONLY=1 SKIP_GOLANGCI_LINT=1`, I just got this test failure with a panic in compaction:

```
--- FAIL: TestDelayedCompaction (2.68s)
    compact_test.go:2042: 
        	Error Trace:	/__w/prometheus/prometheus/tsdb/compact_test.go:1965
        	            				/__w/prometheus/prometheus/tsdb/compact_test.go:2042
        	Error:      	"1.982065514s" is not less than "1s"
        	Test:       	TestDelayedCompaction
    --- FAIL: TestDelayedCompaction/delayed_compaction_not_enabled (2.68s)
panic: test executed panic(nil) or runtime.Goexit

goroutine 6180 [running]:
testing.tRunner.func1.2({0x1562940, 0x229b970})
	/usr/local/go/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1635 +0x6b6
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:629 +0x5e
testing.(*common).FailNow(0xc00062e1a0)
	/usr/local/go/src/testing/testing.go:1006 +0x85
github.com/stretchr/testify/require.Less({0x1b27f70, 0xc00062e1a0}, {0x1645680, 0xc0027ec1e8}, {0x1645680, 0xc0027ec1f8}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/require/require.go:1188 +0x107
github.com/prometheus/prometheus/tsdb.TestDelayedCompaction.func2(0xc00064c000)
	/__w/prometheus/prometheus/tsdb/compact_test.go:1965 +0x10a
github.com/prometheus/prometheus/tsdb.TestDelayedCompaction.func3(0xc00062e340)
	/__w/prometheus/prometheus/tsdb/compact_test.go:2042 +0x626
testing.tRunner(0xc00062e340, 0xc001a38270)
	/usr/local/go/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 6179
	/usr/local/go/src/testing/testing.go:1743 +0x826
```

**Comment by juliusv** [comment]
@machine424

**Comment by machine424** [comment]
I'm not seeing any failures on main in last couple of weeks, I think this was a result of the `on space left on device` issue as for https://github.com/prometheus/prometheus/issues/14857
I think we can close this.

**Comment by juliusv** [comment]
It could also generally have been related to the race detector being enabled in tests, which we disabled temporarily (and still have disabled now) to make CI tests pass. I guess it's ok to close for now, but it could very well be that it resurfaces once the race detector is enabled again.
