### ISSUE TITLE
`TestReadyAndHealthy` CI test flaky

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#15071]
### What did you do?

-

### What did you see instead? Under which circumstances?

The `TestReadyAndHealthy` test failed in CI, seems flaky:

```
--- FAIL: TestReadyAndHealthy (0.02s)
panic: Unable to start web listeners: listen tcp :38639: bind: address already in use [recovered]
	panic: Unable to start web listeners: listen tcp :38639: bind: address already in use

goroutine 133 [running]:
testing.tRunner.func1.2({0x12cf780, 0xc000620b90})
	/usr/local/go/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1635 +0x35e
panic({0x12cf780?, 0xc000620b90?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/prometheus/prometheus/web.TestReadyAndHealthy(0xc000032b60)
	/__w/prometheus/prometheus/web/web_test.go:106 +0x108b
testing.tRunner(0xc000032b60, 0x159b7b0)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1743 +0x390
FAIL	github.com/prometheus/prometheus/web	10.078s
```

**Comment by juliusv** [comment]
The problem here is that this and other tests run in parallel and all use `testutil.RandomUnprivilegedPort(t)` to get a random port, but that has a race condition because two tests may get the same free port number assigned if they run in parallel.
