### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by Tusenka** [prometheus/prometheus#15091]
### What did you do?

I run 
`make build`

### What did you expect to see?

the roject is buikding

### What did you see instead? Under which circumstances?

/home/cas12/prometheus-main/web/ui/node_modules/rollup/dist/bin/rollup:1342
                valueString ??= String(value);
                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @prometheus-io/lezer-promql@0.300.0-beta.0 
npm ERR!   at location: /home/cas12/prometheus-main/web/ui/module/lezer-promql 
make: *** [Makefile:64: ui-build] Error 1
Time: 0h:00m:23s                         

### System information

Linux 6.8.0-45-generic x86_64

### Prometheus version

```text
prometheus, version 2.43.0 (branch: HEAD, revision: edfc3bcd025dd6fe296c167a14a216cab1e552ee)
  build user:       root@8a0ee342e522
  build date:       20230321-12:56:07
  go version:       go1.19.7
  platform:         linux/amd64
  tags:             netgo,builtinassets
```

**Comment by prathamjagga** [comment]
which version of Nodejs are you using. Make sure you use v16 or greater

**Comment by machine424** [comment]
Contributions to have such deps versions constraints checks done in the `Makefile` e.g. are welcome.

**Comment by prathamjagga** [comment]
> Contributions to have such deps versions constraints checks done in the `Makefile` e.g. are welcome.

#15106 I added a makefile target to check for correct versions of Nodejs, Go and NPM before building the app.

**Comment by krajorama** [comment]
Hello from the bug scrub!

My recent builds have been working and we have the requirements specified in the README now: https://github.com/prometheus/prometheus/?tab=readme-ov-file#building-from-source. We always welcome improvements to the docs and processes.
