### ISSUE TITLE
Prometheus is using the NOVA os-floating-ips call which is deprecated and shouldn't use , it should call the neutron-apis instead.

### ISSUE THREAD

**Issue by david-hill** [prometheus/prometheus#15151]
### What did you do?

Configure prometheus SD service for openstack

### What did you expect to see?

floating IPS (I guess)

### What did you see instead? Under which circumstances?

Internal Server Error because openstack nova API uses neutron-client which limits the URI to 8192 characters, on tenants with 816 VMs, this lamentably fails to work

### System information

RHEL 9.2

### Prometheus version

```text
All releases are affected by this.
```

### Prometheus configuration file

```yaml
openstack_sd_configs:
    - identity_endpoint: "https://hello_world:13000/v3"
      password: ""
      region: "regionOne"
      role: "instance"
      domain_name: "Default"
      project_id: "project_id"
      tls_config:
        insecure_skip_verify: true
      username: "deployment.user"
      refresh_interval: 1m
```

### Logs

```text
~~~
2024-10-10 18:01:44.865 22 INFO nova.api.openstack.requestlog [req-557b6861-a124-4cda-b42e-cadabd0b0279 26643756065940a58d8d6382d9a776f3 d1fee70642f54845a28043eca630f16b - default default] 10.10.10.10 "GET /v2.1/os-floating-ips" status:
 500 len: 223 microversion: 2.1 time: 1.012708
~~~

And in nova logs :
~~~
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi [req-9b433b5f-9aec-4a67-8e4b-def66cd576cb 26643756065940a58d8d6382d9a776f3 d1fee70642f54845a28043eca630f16b - default default] Unexpected exception in API method: neutronclient.comm
on.exceptions.RequestURITooLong: An unknown exception occurred.
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi Traceback (most recent call last):
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/api/openstack/wsgi.py", line 658, in wrapped
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     return f(*args, **kwargs)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/api/openstack/compute/floating_ips.py", line 111, in index
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     floating_ips = self.network_api.get_floating_ips_by_project(context)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/network/neutron.py", line 2677, in get_floating_ips_by_project
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     networks = {net['id']: net for net in self._get_available_networks(
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/network/neutron.py", line 458, in _get_available_networks
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     nets = neutron.list_networks(**search_opts).get('networks', [])
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/network/neutron.py", line 182, in wrapper
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     ret = obj(*args, **kwargs)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/v2_0/client.py", line 844, in list_networks
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     return self.list('networks', self.networks_path, retrieve_all,
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/network/neutron.py", line 182, in wrapper
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     ret = obj(*args, **kwargs)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/v2_0/client.py", line 368, in list
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     for r in self._pagination(collection, path, **params):
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/v2_0/client.py", line 383, in _pagination
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     res = self.get(path, params=params)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/network/neutron.py", line 182, in wrapper
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     ret = obj(*args, **kwargs)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/v2_0/client.py", line 352, in get
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     return self.retry_request("GET", action, body=body,
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/network/neutron.py", line 182, in wrapper
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     ret = obj(*args, **kwargs)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/v2_0/client.py", line 329, in retry_request
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     return self.do_request(method, action, body=body,
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/nova/network/neutron.py", line 182, in wrapper
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     ret = obj(*args, **kwargs)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/v2_0/client.py", line 280, in do_request
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     resp, replybody = self.httpclient.do_request(action, method, body=body,
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/client.py", line 339, in do_request
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     self._check_uri_length(url)
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi   File "/usr/lib/python3.9/site-packages/neutronclient/client.py", line 334, in _check_uri_length
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi     raise exceptions.RequestURITooLong(
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi neutronclient.common.exceptions.RequestURITooLong: An unknown exception occurred.
2024-10-10 18:05:52.446 27 ERROR nova.api.openstack.wsgi 
2024-10-10 18:05:52.447 27 INFO nova.api.openstack.wsgi [req-9b433b5f-9aec-4a67-8e4b-def66cd576cb 26643756065940a58d8d6382d9a776f3 d1fee70642f54845a28043eca630f16b - default default] HTTP exception thrown: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
<class 'neutronclient.common.exceptions.RequestURITooLong'>
~~~
```

**Comment by paulojmdias** [comment]
@david-hill i think this were fixed in https://github.com/prometheus/prometheus/pull/14367 and released in v3.2.0.

Can you please check if it is now working as expected with version v3.2.0?

**Comment by krajorama** [comment]
Hello from the bug scrub!

We assume this is indeed fixed by #14367 . Closing as completed.
