### ISSUE TITLE
Promethues crash with abort 

### ISSUE THREAD

**Issue by yogeshdeshmukh-1408** [prometheus/prometheus#15211]
### What did you do?

deleted all the files under Prometheus directory and sent a exit request, crash was seen during exit

### What did you see instead? Under which circumstances?

we saw Prometheus abort when exit is triggered via http request

**Comment by machine424** [comment]
More details are welcome, what do you mean by "crash"?

**Comment by yogeshdeshmukh-1408** [comment]
what do you mean by "crash"?
Ans: The term "crash" in this context refers to an "abort core".

Backtrace logs

(gdb) bt
#0  runtime.raise () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:154
#1  0x0000000000459d25 in runtime.dieFromSignal (sig=6) at /usr/lib/golang/src/runtime/signal_unix.go:923
#2  0x000000000045a426 in runtime.sigfwdgo (sig=6, info=<optimized out>, ctx=<optimized out>, ~r0=<optimized out>)
    at /usr/lib/golang/src/runtime/signal_unix.go:1128
#3  0x0000000000458945 in runtime.sigtrampgo (sig=0, info=0x0, ctx=0x47d861 <runtime.raise+33>)
    at /usr/lib/golang/src/runtime/signal_unix.go:432
#4  0x000000000047db66 in runtime.sigtramp () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:352
#5  <signal handler called>
#6  runtime.raise () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:154
#7  0x0000000000459d25 in runtime.dieFromSignal (sig=6) at /usr/lib/golang/src/runtime/signal_unix.go:923
#8  0x0000000000441545 in runtime.crash () at /usr/lib/golang/src/runtime/signal_unix.go:1005
#9  runtime.fatalpanic (msgs=<optimized out>) at /usr/lib/golang/src/runtime/panic.go:1244
#10 0x00000000004404b8 in runtime.gopanic (e=...) at /usr/lib/golang/src/runtime/panic.go:779
#11 0x0000000002b2173c in github.com/prometheus/prometheus/tsdb.handleChunkWriteError (err=...)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/tsdb/head_append.go:1493
#12 0x0000000002850191 in github.com/prometheus/prometheus/tsdb/chunks.(*ChunkDiskMapper).WriteChunk (cdm=0xc000e92000,
    seriesRef=2087, mint=1728778127546, maxt=1728778427546, chk=..., isOOO=false, callback={void (error)} 0xc001568910,
    chkRef=<optimized out>, chkRef=<optimized out>)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go:469
#13 0x0000000002b21585 in github.com/prometheus/prometheus/tsdb.(*memSeries).mmapChunks (s=0xc0011d9800,
    chunkDiskMapper=0xc000e92000, count=<optimized out>)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/tsdb/head_append.go:1475
#14 0x0000000002b15deb in github.com/prometheus/prometheus/tsdb.(*Head).mmapHeadChunks (h=0xc000a81408)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/tsdb/head.go:1741
#15 0x0000000002b15596 in github.com/prometheus/prometheus/tsdb.(*Head).Close (h=0xc000a81408, ~r0=..., ~r0=...)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/tsdb/head.go:1660
#16 0x0000000002b033bf in github.com/prometheus/prometheus/tsdb.(*DB).Close (db=0xc0004dc100, ~r0=..., ~r0=...)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/tsdb/db.go:1869
#17 0x0000000002bac9c2 in main.(*readyStorage).Close (s=<optimized out>, ~r0=...)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:1583
#18 0x000000000285aa13 in github.com/prometheus/prometheus/storage.(*fanout).Close (f=0xc00053cb80, ~r0=...)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/storage/fanout.go:136
#19 0x0000000002ba746f in main.main.func26 (err=...)
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:1191
#20 0x00000000009cff7d in github.com/oklog/run.(*Group).Run (g=0xc001569498, ~r0=...)
    at /build/distro/work/x86_64/prometheus-2.53.0/pkg/mod/github.com/oklog/run@v1.1.0/group.go:47
#21 0x0000000002ba638c in main.main ()
    at /build/distro/work/x86_64/prometheus-2.53.0/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:1288

**Comment by bboreham** [comment]
Hello from the bug-scrub!

There should be a line in the log that starts "Panic:", and this line will include the error message that caused the abort.
If you still have the logs, please could you get that.

From the stack dump, this happened while trying to write out metrics data to disk.
