### ISSUE TITLE
Error querying page data 

### ISSUE THREAD

**Issue by datamuc** [prometheus/prometheus#15335]
### What did you do?

Started fresh Prometheus instance from quay.io:

docker run -d -p 9090:9090 quay.io/prometheus/prometheus:v3.0.0-rc.0

Into the query field I wrote

```
sum(rate(prometheus_http_requests_total[5m]))
```

### What did you expect to see?

The query result

### What did you see instead? Under which circumstances?

Brave shows this error:

```
Error querying page data
Error: Cannot read properties of undefined (reading 'replace')
```

Firefox shows this error:

```
Error querying page data
Error: t is undefined
```

### Prometheus version

```text
prometheus, version 3.0.0-rc.0 (branch: HEAD, revision: 1ac3ca952858f329b280a0bf549ec6bc24726ee0)
  build user:       root@e94c57d5bd21
  build date:       20241104-13:42:54
  go version:       go1.23.2
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
The containers default
```

### Alertmanager version

```text
n/a
```

### Alertmanager configuration file

```yaml
n/a
```

### Logs

```text
TypeError: Cannot read properties of undefined (reading 'replace')
    at rc (index-D7XxjOAv.js:454:11615)
    at r (index-D7XxjOAv.js:490:6976)
    at Rf (index-D7XxjOAv.js:490:7636)
    at zI (index-D7XxjOAv.js:38:17030)
    at u5 (index-D7XxjOAv.js:40:44098)
    at o5 (index-D7XxjOAv.js:40:39820)
    at Aee (index-D7XxjOAv.js:40:39747)
    at yv (index-D7XxjOAv.js:40:39597)
    at N1 (index-D7XxjOAv.js:40:35959)
    at R2 (index-D7XxjOAv.js:40:36764) {componentStack: '\n    at Rf (http://workstation.example.com:9090/assets/…example.com:9090/assets/index-D7XxjOAv.js:403:2889)'}
```

**Comment by martialblog** [comment]
Hi, 

ran into something similar while testing prometheus:v3.0.0-rc.0. A simple `prometheus_http_requests_total` query works as expected, however, when using `sum(rate(prometheus_http_requests_total[5m]))`:

![screenshot_2024-11-05-110155](https://github.com/user-attachments/assets/fc1fb508-e5c5-4cde-80ef-4791a66b7a8a)

```
Uncaught error: TypeError: t is undefined
    rc http://localhost:9090/assets/index-D7XxjOAv.js:454
    r http://localhost:9090/assets/index-D7XxjOAv.js:490
    Rf http://localhost:9090/assets/index-D7XxjOAv.js:490
    zI http://localhost:9090/assets/index-D7XxjOAv.js:38
    u5 http://localhost:9090/assets/index-D7XxjOAv.js:40
    o5 http://localhost:9090/assets/index-D7XxjOAv.js:40
    Aee http://localhost:9090/assets/index-D7XxjOAv.js:40
    yv http://localhost:9090/assets/index-D7XxjOAv.js:40
    N1 http://localhost:9090/assets/index-D7XxjOAv.js:40
    i5 http://localhost:9090/assets/index-D7XxjOAv.js:40
    y http://localhost:9090/assets/index-D7XxjOAv.js:25
    L http://localhost:9090/assets/index-D7XxjOAv.js:25
 
Object { componentStack: "\nRf@http://localhost:9090/assets/index-D7XxjOAv.js:490:6801\ntd\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nKu/r<@http://localhost:9090/assets/index-D7XxjOAv.js:83:202693\ntr\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nKu/r<@http://localhost:9090/assets/index-D7XxjOAv.js:83:202693\ntbody\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nKu/r<@http://localhost:9090/assets/index-D7XxjOAv.js:83:202693\ntable\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\n_i/<@http://localhost:9090/assets/index-D7XxjOAv.js:80:4871\nV<@http://localhost:9090/assets/index-D7XxjOAv.js:83:204920\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nzt<@http://localhost:9090/assets/index-D7XxjOAv.js:83:199006\nbwe@http://localhost:9090/assets/index-D7XxjOAv.js:490:13151\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nzt<@http://localhost:9090/assets/index-D7XxjOAv.js:83:199006\nSwe@http://localhost:9090/assets/index-D7XxjOAv.js:490:15915\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\njM<@http://localhost:9090/assets/index-D7XxjOAv.js:83:206771\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\n_i/<@http://localhost:9090/assets/index-D7XxjOAv.js:80:4871\nHi<@http://localhost:9090/assets/index-D7XxjOAv.js:83:208968\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nzt<@http://localhost:9090/assets/index-D7XxjOAv.js:83:199006\nQwe@http://localhost:9090/assets/index-D7XxjOAv.js:490:179754\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nzt<@http://localhost:9090/assets/index-D7XxjOAv.js:83:199006\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nxX@http://localhost:9090/assets/index-D7XxjOAv.js:490:182750\ndb@http://localhost:9090/assets/index-D7XxjOAv.js:500:92669\nCue@http://localhost:9090/assets/index-D7XxjOAv.js:386:3870\nCF@http://localhost:9090/assets/index-D7XxjOAv.js:386:7701\nSuspense\nxRe@http://localhost:9090/assets/index-D7XxjOAv.js:474:5103\nEh@http://localhost:9090/assets/index-D7XxjOAv.js:474:5542\nmain\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\nQD<@http://localhost:9090/assets/index-D7XxjOAv.js:83:120486\ndiv\nY5<@http://localhost:9090/assets/index-D7XxjOAv.js:83:15955\n_i/<@http://localhost:9090/assets/index-D7XxjOAv.js:80:4871\nys<@http://localhost:9090/assets/index-D7XxjOAv.js:83:127452\nfde@http://localhost:9090/assets/index-D7XxjOAv.js:395:38379\nP5@http://localhost:9090/assets/index-D7XxjOAv.js:80:31122\nU5@http://localhost:9090/assets/index-D7XxjOAv.js:83:1686\nXj@http://localhost:9090/assets/index-D7XxjOAv.js:492:926\noPe@http://localhost:9090/assets/index-D7XxjOAv.js:501:3960\nwAe@http://localhost:9090/assets/index-D7XxjOAv.js:492:1125\nMue@http://localhost:9090/assets/index-D7XxjOAv.js:386:7162\n$ue@http://localhost:9090/assets/index-D7XxjOAv.js:395:935\nvPe@http://localhost:9090/assets/index-D7XxjOAv.js:501:11941\nVde@http://localhost:9090/assets/index-D7XxjOAv.js:403:2881" }
index-D7XxjOAv.js:83:580

```

**Comment by juliusv** [comment]
On it! I did a stupid mistake in https://github.com/prometheus/prometheus/pull/15244 and the regex checking metric names for the new UTF-8 characters doesn't match empty metric names.

> EDIT: Great work on the new UI though! (just need to mention it somewhere)

Thank you 😊
