### ISSUE TITLE
New armel test failure (panic: runtime error: index out of range)

### ISSUE THREAD

**Issue by TheTincho** [prometheus/prometheus#2206]
Me again :-)

Yesterday I uploaded a new release of 1.2.3 to Debian (I haven't uploaded 1.3 due to the kubernetes chain of dependencies), and I got this error during tests in armel.

It is worth noting that the previous release had the same source code, and was not failing, the only difference is that some dependencies got updated (oauth2 and logrus), but I don't see how those could be related..

```
=== RUN   TestDropMetrics
time="2016-11-18T02:42:54Z" level=info msg="Loading series map and head chunks..." source="storage.go:354" 
time="2016-11-18T02:42:54Z" level=info msg="0 series loaded." source="storage.go:359" 
time="2016-11-18T02:43:04Z" level=info msg="Maintenance loop stopped." source="storage.go:1224" 
panic: runtime error: index out of range

goroutine 655 [running]:
panic(0x423540, 0x10928028)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x33c
github.com/prometheus/prometheus/storage/local.(*memorySeries).maybeCloseHeadChunk(0x11b7a050, 0x618714)
	/«BUILDDIR»/prometheus-1.2.3+ds2/build/src/github.com/prometheus/prometheus/storage/local/series.go:280 +0x290
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).maintainMemorySeries(0x10998600, 0x94b33977, 0x2ee1b8f2, 0x341bb166, 0xfffffe7a, 0xfffffd00)
	/«BUILDDIR»/prometheus-1.2.3+ds2/build/src/github.com/prometheus/prometheus/storage/local/storage.go:1327 +0x1d4
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).loop(0x10998600)
	/«BUILDDIR»/prometheus-1.2.3+ds2/build/src/github.com/prometheus/prometheus/storage/local/storage.go:1252 +0x400
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Start
	/«BUILDDIR»/prometheus-1.2.3+ds2/build/src/github.com/prometheus/prometheus/storage/local/storage.go:370 +0x3e8
exit status 2
FAIL	github.com/prometheus/prometheus/storage/local	12.879s
```

**Comment by TheTincho** [comment]
It turns out it is some kind of flaky test. Most of the time, it runs fine, but sometimes there will be a panic. I haven't yet reproduced this in another architecture, but maybe it is just a timing issue.

Consistently, the `"Maintenance loop stopped."` message appears just before the panic, without a `"Stopping maintenance loop..."`.

Any ideas?

**Comment by brian-brazil** [comment]
Is this still happening?

**Comment by TheTincho** [comment]
According to the latest armel logs, no.. Somewhere along the way it got fixed
