### ISSUE TITLE
Prometheus 1.6 crashes

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2635]
It seems like 1.6 reliably crashes after startup – I only saw this happen on a server that had no targets from the beginning.

Did not dig into the code but I suspect `rand.Intn` is being called with a 0 here.

@beorn7 

```
panic: invalid argument to Intn

goroutine 242 [running]:
math/rand.(*Rand).Intn(0xc42007a090, 0x0, 0x0)
       	/usr/local/Cellar/go/1.8/libexec/src/math/rand/rand.go:141 +0xc7
math/rand.Intn(0x0, 0x343b5a0)
       	/usr/local/Cellar/go/1.8/libexec/src/math/rand/rand.go:276 +0x37
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).cycleThroughMemoryFingerprints.func1(0xc4202654a0, 0xc42036a000)
       	/Users/fabxc/repos/src/github.com/prometheus/prometheus/storage/local/storage.go:1348 +0x440
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).cycleThroughMemoryFingerprints
       	/Users/fabxc/repos/src/github.com/prometheus/prometheus/storage/local/storage.go:1377 +0x67
```

**Comment by beorn7** [comment]
Fix will be in 1.6.1.
