### ISSUE TITLE
Prometheus 2.0: panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by iobestar** [prometheus/prometheus#3108]
**What did you do?**
Nothing special.
**What did you expect to see?**
That Prometheus keep running.
**What did you see instead? Under which circumstances?**
Prometheus crashes.
**Prometheus version:**
prometheus, version 2.0.0-beta.1 (branch: HEAD, revision: 4dcb465)
build user: root@d3f9974fac5a
build date: 20170811-12:16:25
go version: go1.8.3

**Logs:**
```
panic: runtime error: integer divide by zero

goroutine 40 [running]:
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*LeveledCompactor).Plan(0xc42043ce40, 0x7fff2ee183f6, 0x10, 0x0, 0xa, 0x10, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/compact.go:173 +0x621
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).compact(0xc42010a460, 0xc420135a01, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:406 +0x2c5
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).run(0xc42010a460)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:281 +0x3c6
created by github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.Open
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:250 +0x488
```

**Comment by onorua** [comment]
Was fixed with https://github.com/prometheus/tsdb/pull/120, please update to beta2
