### ISSUE TITLE
panic: invalid mem or nil pointer (discovery.go)

### ISSUE THREAD

**Issue by Jonnymcc** [prometheus/prometheus#3757]
**What did you do?**
Nothing, came in after weekend and it was down.

**What did you expect to see?**
A more useful error message.

**What did you see instead? Under which circumstances?**
Last logged message before panic was...
```
ESC[34mINFOESC[0m[403927] Checkpointing in-memory metrics and chunks...  ESC[34msourceESC[0m=persistence.go:633
ESC[34mINFOESC[0m[403929] Done checkpointing in-memory metrics and chunks in 1.369818718s.  ESC[34msourceESC[0m=persistence.go:665
```

**Environment**

* System information:

`Linux 3.13.0-121-generic x86_64`

* Prometheus version:

```
prometheus, version 1.6.2 (branch: master, revision: b38e977fd8cc2a0d13f47e7f0e17b82d1a908a9a)
  build user:       root@c99d9d650cf4
  build date:       20170511-12:59:13
  go version:       go1.8.1
```

* Logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa52f19]

goroutine 323 [running]:
github.com/prometheus/prometheus/discovery/ec2.(*Discovery).refresh.func2(0xc44aca3b20, 0x1, 0x0)
        /go/src/github.com/prometheus/prometheus/discovery/ec2/ec2.go:193 +0x619
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeInstancesPages.func1(0x18c16a0, 0xc44aca3b20, 0x1, 0xc44aca3b40)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go:6785 +0x49
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).EachPage(0xc4202baa80, 0xc448c05b88, 0x2, 0x2)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/request/request_pagination.go:98 +0x90
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeInstancesPages(0xc4385ee658, 0x0, 0xc448c05ca8, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go:6786 +0x124
github.com/prometheus/prometheus/discovery/ec2.(*Discovery).refresh(0xc42b699d40, 0xc44c8e0870, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/discovery/ec2/ec2.go:199 +0x319
github.com/prometheus/prometheus/discovery/ec2.(*Discovery).Run(0xc42b699d40, 0x7f13a3831060, 0xc42c346540, 0xc42c342ae0)
        /go/src/github.com/prometheus/prometheus/discovery/ec2/ec2.go:114 +0x19d
created by github.com/prometheus/prometheus/discovery.(*TargetSet).updateProviders
        /go/src/github.com/prometheus/prometheus/discovery/discovery.go:239 +0x283
```

**Comment by Gouthamve** [comment]
Hi this is a very old version of Prometheus. Could you please upgrade to 2.1 to see if this has been fixed?

Closing this right now, feel free to re-open if you think I missed something.
