### ISSUE TITLE
remote_write: send on closed channel

### ISSUE THREAD

**Issue by iksaif** [prometheus/prometheus#4262]
## Bug Report

Running Prometheus 2.3.0 with graphite-remote-adapter and stopping it:
```
level=info ts=2018-06-13T06:49:24.26401728Z caller=queue_manager.go:258 component=remote queue="0:http://prometheus-meta-graphite-remote-adapter/write?graphite.default-prefix=sre.network.services.prometheus." msg="Stopping remote storage..."
level=info ts=2018-06-13T06:49:25.680587091Z caller=queue_manager.go:266 component=remote queue="0:http://prometheus-meta-graphite-remote-adapter/write?graphite.default-prefix=sre.network.services.prometheus." msg="Remote storage stopped."
level=info ts=2018-06-13T06:49:25.680647131Z caller=manager.go:464 component="rule manager" msg="Stopping rule manager..."
panic: send on closed channel

goroutine 932 [running]:
github.com/prometheus/prometheus/storage/remote.(*shards).enqueue(0xc42017b0e0, 0xc42e688c00, 0x5)
        /go/src/github.com/prometheus/prometheus/storage/remote/queue_manager.go:438 +0x8b
github.com/prometheus/prometheus/storage/remote.(*QueueManager).Append(0xc4202e41e0, 0xc439343918, 0x8, 0xc437844090)
        /go/src/github.com/prometheus/prometheus/storage/remote/queue_manager.go:222 +0x26e
github.com/prometheus/prometheus/storage/remote.(*Storage).Add(0xc420193420, 0xc429089100, 0x5, 0x8, 0x163f7e7f3cc, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/storage/remote/write.go:32 +0x11a
github.com/prometheus/prometheus/storage.(*fanoutAppender).Add(0xc426cafa40, 0xc429089100, 0x5, 0x8, 0x163f7e7f3cc, 0x0, 0x1c85b, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/storage/fanout.go:140 +0x131
github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0x1decdc0, 0xc420042118, 0x275dbd39, 0xed2b2b573, 0x2afd680, 0xc4208fa870, 0x10, 0x1df69e0, 0xc42109fcc0)
        /go/src/github.com/prometheus/prometheus/rules/manager.go:365 +0x6f8
github.com/prometheus/prometheus/rules.(*Group).Eval(0xc4208fa870, 0x1decdc0, 0xc420042118, 0x275dbd39, 0xed2b2b573, 0x2afd680)
        /go/src/github.com/prometheus/prometheus/rules/manager.go:406 +0xad
github.com/prometheus/prometheus/rules.(*Group).run.func1()
        /go/src/github.com/prometheus/prometheus/rules/manager.go:206 +0xc0
github.com/prometheus/prometheus/rules.(*Group).run(0xc4208fa870, 0x1decdc0, 0xc420042118)
        /go/src/github.com/prometheus/prometheus/rules/manager.go:235 +0x2e6
github.com/prometheus/prometheus/rules.(*Manager).Update.func1.1(0xc420179340, 0xc4208fa870)
        /go/src/github.com/prometheus/prometheus/rules/manager.go:509 +0x60
created by github.com/prometheus/prometheus/rules.(*Manager).Update.func1
        /go/src/github.com/prometheus/prometheus/rules/manager.go:504 +0x56
```

**Environment**

```
Linux 4.13.0-45-generic x86_64
prometheus, version 2.3.0 (branch: HEAD, revision: 290d71791a507a5057b9a099c9d48703d86dc941)
  build user:       root@d539e167976a
  build date:       20180607-08:46:54
  go version:       go1.10.2
```

**Comment by jojohappy** [comment]
I predict that the `Remote storage` is stopped before `scrapeManager`. It is only closed the queue in the `QueueManager`, but it does not prevent new sample appended into `QueueManager`.

So should Prometheus make sure that `scrapeManager` must be stopped before all components?

**Comment by brian-brazil** [comment]
Yes, scrapes and rules should be shutdown before storage.

**Comment by codwu** [comment]
@jojohappy  As the log shows, this issue is caused by ruleManager. It did not stop rule evaluation after remote storage is stopped.

**Comment by jojohappy** [comment]
@codwu Yes, It is. As @brian-brazil said, both `scrapeManager` and `ruleManager` should be stopped before storage. I will try to fix this bug.

**Comment by brian-brazil** [comment]
This sounds like it might be the same cause as #4133

**Comment by codwu** [comment]
https://github.com/prometheus/prometheus/blob/2bd510a63e48ac6bf4971d62199bdb1045c93f1a/vendor/github.com/oklog/oklog/pkg/group/group.go#L46-L48

The managers stop in sequence, so the ruleManager receives the stopping signal after storage. I think we can fix this by adding ruleManager into groups before storage
