### ISSUE TITLE
Prometheus crashes when service discovery configuration is nil/null

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/prometheus#4902]
Prometheus panics with the following configuration snippets:

```yaml
- job_name: foo
  azure_sd_configs:
  - 
```

```yaml
- job_name: bar
  kubernetes_sd_configs:
  - null
```

Logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8f0589]

goroutine 180 [running]:
github.com/prometheus/prometheus/discovery/azure.NewDiscovery(0x0, 0x1e2c580, 0xc005756690, 0x2)                                                                                             
        /home/simon/workspace/src/github.com/prometheus/prometheus/discovery/azure/azure.go:120 +0x109                                                                                       
github.com/prometheus/prometheus/discovery.(*Manager).registerProviders.func12(0x18c5320, 0x0, 0x17ef620, 0xc000525390)                                                                      
        /home/simon/workspace/src/github.com/prometheus/prometheus/discovery/manager.go:394 +0xba                                                                                            
github.com/prometheus/prometheus/discovery.(*Manager).registerProviders.func1(0x18c5320, 0x0, 0xc005754b00)                                                                                  
        /home/simon/workspace/src/github.com/prometheus/prometheus/discovery/manager.go:326 +0x229                                                                                           
github.com/prometheus/prometheus/discovery.(*Manager).registerProviders(0xc000374a00, 0xc003222428, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                             
        /home/simon/workspace/src/github.com/prometheus/prometheus/discovery/manager.go:393 +0xd5a                                                                                           
github.com/prometheus/prometheus/discovery.(*Manager).ApplyConfig(0xc000374a00, 0xc00573fb30, 0x0, 0x0)                                                                                      
        /home/simon/workspace/src/github.com/prometheus/prometheus/discovery/manager.go:191 +0x335                                                                                           
main.main.func2(0xc00323af00, 0x0, 0x0)
        /home/simon/workspace/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:346 +0x18a                                                                                         
main.reloadConfig(0x1bc01f6, 0xe, 0x1e2c580, 0xc0005559e0, 0xc000171b40, 0x7, 0x7, 0x0, 0x0)
        /home/simon/workspace/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:653 +0x228                                                                                         
main.main.func16(0x0, 0x0)
        /home/simon/workspace/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:527 +0x17e                                                                                         
github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0000a4f60, 0xc0000a4f00, 0xc00003b070)                                                        
        /home/simon/workspace/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27                                                                 
created by github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run                                                                                             
        /home/simon/workspace/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe   
```

**Comment by juliusv** [comment]
The same happens for an empty `scrape_config` section and probably other sections as well.

**Comment by juliusv** [comment]
Heads-up: I'm fixing all the slice-of-pointers config `nil` pointer crashes in one go, so this will be covered by that.
