### ISSUE TITLE
Flake in TestHandlerQueueing

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#4935]
```
2018/11/30 06:52:31 http: panic serving 127.0.0.1:44936: Fail in goroutine after TestHandlerQueueing has completed
goroutine 90 [running]:
net/http.(*conn).serve.func1(0xc0005e50e0)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/server.go:1746 +0x17c
panic(0x17a02a0, 0xc00044c960)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/panic.go:513 +0x1b9
testing.(*common).Fail(0xc000121b00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:546 +0x1c6
testing.(*common).FailNow(0xc000121b00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:568 +0x39
testing.(*common).Fatalf(0xc000121b00, 0x194857c, 0x1f, 0xc00044c940, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:634 +0x95
github.com/prometheus/prometheus/util/testutil.Ok(0x1b62000, 0xc000121b00, 0x1b58a20, 0xc000054060)
	/home/travis/gopath/src/github.com/prometheus/prometheus/util/testutil/testing.go:49 +0xde
github.com/prometheus/prometheus/notifier.TestHandlerQueueing.func1(0x1b6fe20, 0xc00037c540, 0xc000120e00)
	/home/travis/gopath/src/github.com/prometheus/prometheus/notifier/notifier_test.go:319 +0x268
net/http.HandlerFunc.ServeHTTP(0xc000570540, 0x1b6fe20, 0xc00037c540, 0xc000120e00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/server.go:1964 +0x52
net/http.serverHandler.ServeHTTP(0xc0002051e0, 0x1b6fe20, 0xc00037c540, 0xc000120e00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/server.go:2741 +0xc5
net/http.(*conn).serve(0xc0005e50e0, 0x1b72f60, 0xc000537080)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/server.go:1847 +0x80b
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/server.go:2851 +0x4c6
FAIL
FAIL	github.com/prometheus/prometheus/notifier	0.226s
```

Observed here: https://travis-ci.org/prometheus/prometheus/builds/461645082

**Comment by brian-brazil** [comment]
We've looked at this as part of our bug scrub, and this no longer flakes.
