### ISSUE TITLE
Nil pointer panic on starting up 

### ISSUE THREAD

**Issue by intenseFrog** [prometheus/prometheus#5562]
## Bug Report
**What did you do?**
I was running prometheus as a pod in my kubernetes cluster. I removed the old pod and redeploy the same pod under same datapath
**What did you expect to see?**
Prometheus spin up without problem
**What did you see instead? Under which circumstances?**
Pod was in the state of "CrashLoopBackOff".  Seems to be a nil pointer deference on starting when old data is present. See logs below for reference
**Environment**
I run promethues in a docker container
* System information:

* Prometheus version:
Starting Prometheus" version="(version=2.9.2, branch=HEAD, revision=d3245f15022551c6fc8281766ea62db4d71e2747)

* Prometheus configuration file:
I don't think the configuration file here is relevant in this case.

* Logs:
```
level=info ts=2019-05-13T21:54:31.809Z caller=main.go:321 msg="Starting Prometheus" version="(version=2.9.2, branch=HEAD, revision=d3245f15022551c6fc8281766ea62db4d71e2747)"
level=info ts=2019-05-13T21:54:31.810Z caller=main.go:322 build_context="(go=go1.12.4, user=root@1d43b6951e8f, date=20190424-15:32:31)"
level=info ts=2019-05-13T21:54:31.810Z caller=main.go:323 host_details="(Linux 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 prometheus-deployment-7fdbc467b9-bjlh8 (none))"
level=info ts=2019-05-13T21:54:31.810Z caller=main.go:324 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-05-13T21:54:31.810Z caller=main.go:325 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-05-13T21:54:31.812Z caller=main.go:640 msg="Starting TSDB ..."
level=info ts=2019-05-13T21:54:31.813Z caller=web.go:416 component=web msg="Start listening for connections" address=0.0.0.0:9090
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18f83d7]

goroutine 148 [running]:
github.com/prometheus/tsdb.(*Head).chunkRewrite(0xc000b56000, 0x6cda, 0xc005f1e090, 0x1, 0x1, 0x0, 0x0)
	/app/vendor/github.com/prometheus/tsdb/head.go:937 +0x77
github.com/prometheus/tsdb.(*Head).loadWAL.func2(0x6cda, 0xc005f1e090, 0x1, 0x1, 0x0, 0x0)
	/app/vendor/github.com/prometheus/tsdb/head.go:448 +0x52
github.com/prometheus/tsdb.(*memTombstones).Iter(0xc0000a9400, 0xc0009efaa8, 0x0, 0x0)
	/app/vendor/github.com/prometheus/tsdb/tombstones.go:198 +0x116
github.com/prometheus/tsdb.(*Head).loadWAL(0xc000b56000, 0xc000c00000, 0x0, 0x0)
	/app/vendor/github.com/prometheus/tsdb/head.go:447 +0x144f
github.com/prometheus/tsdb.(*Head).Init(0xc000b56000, 0x8000000000000000, 0x0, 0x0)
	/app/vendor/github.com/prometheus/tsdb/head.go:497 +0x243
github.com/prometheus/tsdb.Open(0x7ffdf0f186eb, 0x13, 0x257cca0, 0xc00081fb60, 0x25aaa20, 0xc000146280, 0xc0000d1580, 0x2, 0xc00081c100, 0xc)
	/app/vendor/github.com/prometheus/tsdb/db.go:325 +0x5b4
github.com/prometheus/prometheus/storage/tsdb.Open(0x7ffdf0f186eb, 0x13, 0x257cca0, 0xc00081fb60, 0x25aaa20, 0xc000146280, 0xc00014c1b8, 0x0, 0x0, 0x0)
	/app/storage/tsdb/tsdb.go:191 +0x28f
main.main.func19(0x0, 0x0)
	/app/cmd/prometheus/main.go:646 +0x338
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0001259e0, 0xc0000d1500, 0xc00081fa10)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
```

**Comment by brian-brazil** [comment]
That looks like a tombstone referencing a series we don't know about when we're loading the WAL.

**Comment by intenseFrog** [comment]
I manage to spin up the prometheus Pod by removing the WAL from data path. This issue only seems to happen occasionally
