### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by aixeshunter** [prometheus/prometheus#5660]
### Bug report

* panic: runtime error: slice bounds out of range

```
prometheus-k8s-0                              2/3       CrashLoopBackOff   146        15h
```

* log
```
level=info ts=2019-06-14T02:46:43.006146409Z caller=main.go:238 msg="Starting Prometheus" version="(version=2.4.3, branch=HEAD, revision=167a4b4e73a8eca8df648d2d2043e21bdb9a7449)"
level=info ts=2019-06-14T02:46:43.006488783Z caller=main.go:239 build_context="(go=go1.11.1, user=root@1e42b46043e9, date=20181004-08:42:02)"
level=info ts=2019-06-14T02:46:43.006571898Z caller=main.go:240 host_details="(Linux 3.10.0-957.12.2.el7.x86_64 #1 SMP Mon May 20 08:41:20 EDT 2019 x86_64 prometheus-k8s-0 (none))"
level=info ts=2019-06-14T02:46:43.006645658Z caller=main.go:241 fd_limits="(soft=65536, hard=65536)"
level=info ts=2019-06-14T02:46:43.006715449Z caller=main.go:242 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-06-14T02:46:43.008630154Z caller=main.go:554 msg="Starting TSDB ..."
level=info ts=2019-06-14T02:46:43.008809486Z caller=web.go:397 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-06-14T02:46:43.013703717Z caller=repair.go:35 component=tsdb msg="found healthy block" mint=1560420000000 maxt=1560427200000 ulid=01DD8MSZ25T2KGCYGYRY4H35YN
panic: runtime error: slice bounds out of range

goroutine 186 [running]:
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.(*Reader).next(0xc000dce000, 0xc00022f0e0, 0xc000227bf0)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal/wal.go:739 +0x9a6
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.(*Reader).Next(0xc000dce000, 0xc000227bf0)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal/wal.go:706 +0x2f
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*Head).loadWAL(0xc00033f3f0, 0xc000dce000, 0xc0001ba880, 0x1d1e5a0)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/head.go:304 +0x266
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*Head).Init(0xc00033f3f0, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/head.go:411 +0x28d
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.Open(0x7fff26c5da11, 0xb, 0x1d1d600, 0xc000748480, 0x1d30ec0, 0xc00012a680, 0xc0007484b0, 0xc0006cbc00, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:268 +0x55a
github.com/prometheus/prometheus/storage/tsdb.Open(0x7fff26c5da11, 0xb, 0x1d1d600, 0xc000748480, 0x1d30ec0, 0xc00012a680, 0xc0003fe518, 0x0, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:143 +0x285
main.main.func20(0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:555 +0x1e6
github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc000743f80, 0xc0001bb2c0, 0xc0007483f0)
        /go/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run
        /go/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
```

The prometheus tsdb was stored data in glusterfs.

* kernel
```
Linux fusion1 3.10.0-957.12.2.el7.x86_64 #1 SMP Mon May 20 08:41:20 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* version: 

```
prometheus v2.4.3
glusterfs: 6.1
```

**Comment by simonpasquier** [comment]
v2.4.3 is quite old now. Could you update to the latest version of Prometheus?

**Comment by aixeshunter** [comment]
@simonpasquier OK, I'll try it.

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team. 

Based on the lack of follow-up, we assume this issue is fixed.
