### ISSUE TITLE
Race condition in TestHandlerQueueing

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#5977]
appeared  in this test run.

https://circleci.com/gh/prometheus/prometheus/15247?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by krasi-georgiev** [comment]
full logs

```
==================
WARNING: DATA RACE
Read at 0x00c000016543 by goroutine 120:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:629 +0x132
  testing.(*common).Fatalf()
      /usr/local/go/src/testing/testing.go:614 +0x90
  testing.(*T).Fatalf()
      <autogenerated>:1 +0x75
  github.com/prometheus/prometheus/util/testutil.Ok()
      /home/circleci/project/util/testutil/testing.go:50 +0xdd
  github.com/prometheus/prometheus/notifier.TestHandlerQueueing.func1()
      /home/circleci/project/notifier/notifier_test.go:324 +0x262
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1995 +0x51
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2774 +0xce
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1878 +0x811

Previous write at 0x00c000016543 by main goroutine:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:856 +0x354
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:869 +0x17f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:60 +0x222

Goroutine 120 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:2884 +0x4c4
  net/http/httptest.(*Server).goServe.func1()
      /usr/local/go/src/net/http/httptest/server.go:298 +0xac
==================
FAIL
2019/08/29 16:24:53 http: panic serving 127.0.0.1:45854: Log in goroutine after TestHandlerQueueing has completed
goroutine 242 [running]:
net/http.(*conn).serve.func1(0xc0004da000)
	/usr/local/go/src/net/http/server.go:1769 +0x147
panic(0x1e3e040, 0xc0005e4060)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
testing.(*common).logDepth(0xc000016d00, 0xc0005e9b90, 0x2b, 0x3)
	/usr/local/go/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
	/usr/local/go/src/testing/testing.go:614
testing.(*common).Fatalf(0xc000016d00, 0x20807a8, 0x1f, 0xc0005e4050, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:671 +0x91
github.com/prometheus/prometheus/util/testutil.Ok(0x2410e60, 0xc000016d00, 0x2400960, 0xc0000f4040)
	/home/circleci/project/util/testutil/testing.go:50 +0xde
github.com/prometheus/prometheus/notifier.TestHandlerQueueing.func1(0x242ea80, 0xc000702000, 0xc0006dc400)
	/home/circleci/project/notifier/notifier_test.go:324 +0x263
net/http.HandlerFunc.ServeHTTP(0xc00019b590, 0x242ea80, 0xc000702000, 0xc0006dc400)
	/usr/local/go/src/net/http/server.go:1995 +0x52
net/http.serverHandler.ServeHTTP(0xc0003c49c0, 0x242ea80, 0xc000702000, 0xc0006dc400)
	/usr/local/go/src/net/http/server.go:2774 +0xcf
net/http.(*conn).serve(0xc0004da000, 0x24341c0, 0xc0006f4040)
	/usr/local/go/src/net/http/server.go:1878 +0x812
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x4c5
FAIL	github.com/prometheus/prometheus/notifier	0.489s
```

**Comment by simonpasquier** [comment]
I had https://github.com/prometheus/prometheus/pull/5430 which I need to rebase.
