### ISSUE TITLE
Prometheus for ARM on Docker (from Docker Hub) is crashing

### ISSUE THREAD

**Issue by Sincasios** [prometheus/prometheus#6105]
## Bug Report
**What did you do?**
I updated my prometheus docker image from Docker Hub on my Raspberry Pi 2.

**What did you expect to see?**
Prometheus runing

**What did you see instead? Under which circumstances?**
This backtrace:
```
prometheus_1  | level=info ts=2019-10-05T09:51:23.035Z caller=main.go:296 msg="no time or size retention was set so using the default time retention" duration=15d
prometheus_1  | level=info ts=2019-10-05T09:51:23.036Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.0, branch=HEAD, revision=6ea4252299f542669aca11860abc2192bdc7bede)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.037Z caller=main.go:333 build_context="(go=go1.13.1, user=root@f30bdad2c3fd, date=20191004-12:23:30)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.038Z caller=main.go:334 host_details="(Linux 4.14.78-4-osmc #1 SMP PREEMPT Wed Dec 12 17:58:11 UTC 2018 armv7l e8bfc40ea4d5 osmc.tv)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.039Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.040Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
prometheus_1  | level=info ts=2019-10-05T09:51:23.058Z caller=main.go:657 msg="Starting TSDB ..."
prometheus_1  | level=info ts=2019-10-05T09:51:23.059Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus_1  | level=info ts=2019-10-05T09:51:23.114Z caller=head.go:512 component=tsdb msg="replaying WAL, this may take awhile"
prometheus_1  | panic: runtime error: invalid memory address or nil pointer dereference
prometheus_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12464]
prometheus_1  | 
prometheus_1  | goroutine 210 [running]:
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).MinTime(...)
prometheus_1  |     /app/tsdb/head.go:1172
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).updateMinMaxTime(0x445a580, 0xffffffff, 0x7fffffff, 0x0, 0x80000000)
prometheus_1  |     /app/tsdb/head.go:306 +0x2c
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).processWALSamples(0x445a580, 0x0, 0x80000000, 0x4486900, 0x4486840, 0x0, 0x0)
prometheus_1  |     /app/tsdb/head.go:299 +0x484
prometheus_1  | github.com/prometheus/prometheus/tsdb.(*Head).loadWAL.func2(0x445a580, 0x4230238, 0x4230240, 0x4486900, 0x4486840)
prometheus_1  |     /app/tsdb/head.go:359 +0x3c
prometheus_1  | created by github.com/prometheus/prometheus/tsdb.(*Head).loadWAL
prometheus_1  |     /app/tsdb/head.go:358 +0x160
```

On x86_64 is working fine.

Versión 2.12 is working fine in ARM: image: prom/prometheus:v2.12.0

**Environment**

* System information:
Linux 4.14.78-4-osmc armv7l
But using docker!

```
services:
    prometheus:
        image: prom/prometheus
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus-storage:/prometheus
```
I tried with a new "prometheus-storage" (like a clean install) but it crash too.

**Comment by brian-brazil** [comment]
Does it work if you compile 2.13.0 with go 1.12?

**Comment by Sincasios** [comment]
I don't know. I don't compile prometheus, I get images from Docker Hub.

**Comment by brian-brazil** [comment]
I'd guess that this is an unaligned access to Head.minTime.

**Comment by protik77** [comment]
First grafana and now prometheus.

**Comment by brian-brazil** [comment]
What's this Grafana issue?

**Comment by protik77** [comment]
Grafana went to alpine as their base OS for their docker image for ARM and broke it.

**Comment by brian-brazil** [comment]
That seems unrelated then.

**Comment by unixlab** [comment]
> Does it work if you compile 2.13.0 with go 1.12?

No, I compiled git tag v2.13.0 for arm7 with go1.12.10 and see the same behavior.

**Comment by brian-brazil** [comment]
Can you try it before/after #5999?

**Comment by unixlab** [comment]
Seems related to #5999.
Works before (build with commit 8744afdd) but not after (build with commit 3344bb5c).

**Comment by csmarchbanks** [comment]
I reproduced and fixed this in #6110, @unixlab would you be willing to check that it works for you as well?

**Comment by AlekSi** [comment]
Any ETA for 2.13.1 release with this fix?

**Comment by simonpasquier** [comment]
@krasi-georgiev is the release shepherd. If I'm correct, this should go out soon.

**Comment by krasi-georgiev** [comment]
not sure why this didn't close with merging https://github.com/prometheus/prometheus/issues/6105

will try to make the new Prom release today.
