### ISSUE TITLE
helm chart: prometheus-server container fs permission error

### ISSUE THREAD

**Issue by torsina** [prometheus/prometheus#6524]
## Bug Report
**What did you do?**
installed the helm chart for prometheus via helm 3 on docker desktop for windows
`helm install test stable/prometheus`, version used is: 9.7.2
**What did you expect to see?**
all pods running
**What did you see instead? Under which circumstances?**
all pods and containers running, except for the `prometheus-server` pod crashing in loop

* Logs:
prometheus-server container:
```
level=info ts=2019-12-27T00:07:34.420Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2019-12-27T00:07:34.421Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2019-12-27T00:07:34.421Z caller=main.go:334 host_details="(Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 test-prometheus-server-f8695649b-n2csk (none))"
level=info ts=2019-12-27T00:07:34.421Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-12-27T00:07:34.421Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2019-12-27T00:07:34.421Z caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7fffb619c8e7, 0x5, 0x14, 0x29db1e0, 0xc0006f7bf0, 0x29db1e0)
        /app/promql/query_logger.go:115 +0x48c
main.main()
        /app/cmd/prometheus/main.go:364 +0x5229
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
