### ISSUE TITLE
Panic when calling time(0)

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6939]
**What did you do?**

Run `time(0)`

**What did you expect to see?**

```
Error executing query: invalid parameter 'query': 1:8: parse error: expected 0 argument(s) in call to "time", got 1
```

**What did you see instead? Under which circumstances?**
```
Error executing query: invalid parameter 'query': unexpected error
```

Panic:

```
parser panic: runtime error: index out of range [-1]                                                                                       goroutine 402 [running]:
github.com/prometheus/prometheus/promql/parser.(*parser).recover(0xc0023fa000, 0xc00068d000)         
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/promql/parser/parse.go:269 +0x122
panic(0x2378480, 0xc0008803e0)                                                                                                             
        /home/roidelapluie/godist/go/src/runtime/panic.go:967 +0x15d                                                                       
github.com/prometheus/prometheus/promql/parser.(*parser).checkAST(0xc0023fa000, 0x37f3b80, 0xc00061be30, 0x37f3b80, 0xc00061be30)
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/promql/parser/parse.go:549 +0x28d1                             
github.com/prometheus/prometheus/promql/parser.ParseExpr(0xc0023d4158, 0x8, 0x382be40, 0xc00061be30, 0x0, 0x0)
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/promql/parser/parse.go:119 +0x1e6                           
github.com/prometheus/prometheus/promql.(*Engine).NewInstantQuery(0xc000185c20, 0x7f82d87646e8, 0xc000052dc0, 0xc0023d4158, 0x8, 0x25317c00
, 0xed5f578bd, 0x4a837e0, 0x4a837e0, 0x0, ...)                                                                                             
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/promql/engine.go:365 +0x3f
github.com/prometheus/prometheus/web/api/v1.(*API).query(0xc000139b30, 0xc0006f2c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/web/api/v1/api.go:338 +0x1f4
github.com/prometheus/prometheus/web/api/v1.(*API).Register.func1.1(0x3817480, 0xc0023da280, 0xc0006f2c00)
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/web/api/v1/api.go:251 +0x8e              
net/http.HandlerFunc.ServeHTTP(0xc0000aca80, 0x3817480, 0xc0023da280, 0xc0006f2c00)                                                                /home/roidelapluie/godist/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP(0x37e06a0, 0xc0000aca80, 0x7f82d8498a50, 0xc0023dc280, 0xc0006f
2c00)                                                                                                                                      
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/util/httputil/compression.go:90 +0x7c
github.com/prometheus/prometheus/web.(*Handler).testReady.func1(0x7f82d8498a50, 0xc0023dc280, 0xc0006f2c00)
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/web/web.go:489 +0x55
net/http.HandlerFunc.ServeHTTP(0xc0000acae0, 0x7f82d8498a50, 0xc0023dc280, 0xc0006f2c00)
        /home/roidelapluie/godist/go/src/net/http/server.go:2012 +0x44               
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x7f82d8498a50, 0xc0023dc230, 0xc0006f2c00)
        /home/roidelapluie/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrumen
t_server.go:196 +0xea                                                                                                                      
net/http.HandlerFunc.ServeHTTP(0xc0001e1770, 0x7f82d8498a50, 0xc0023dc230, 0xc0006f2c00)
        /home/roidelapluie/godist/go/src/net/http/server.go:2012 +0x44 

```

**Environment**

prometheus, master (branch: master, revision: 84b00564f4df8477d59ac275e7c62972664c2926)
  build user:       roidelapluie@oxygen
  build date:       20200307-11:11:49
  go version:       go1.14rc1

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
cc @slrtbtfs
