### ISSUE TITLE
build failed when building React app

### ISSUE THREAD

**Issue by crazyss** [prometheus/prometheus#7330]
**What did you do?**
build prometheus in a centos-like distro

**What did you expect to see?**
#make build
cd web/ui/react-app && yarn --frozen-lockfile
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "babel-eslint@10.x".
[4/4] Building fresh packages...
Done in 19.90s.
>> building React app
building React app
yarn run v1.22.4
$ react-scripts build
/home/jinnan.wjn/web/ui/react-app/node_modules/react-scripts/config/webpack.config.js:305
        ...(isEnvProductionProfile && {
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jinnan.wjn/web/ui/react-app/node_modules/react-scripts/scripts/build.js:38:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [web/ui/static/react] Error 1

**Comment by crazyss** [comment]
seems like build environment issue
