### ISSUE TITLE
Prometheus crashing on 32bit Arm - tsdb structures not 64bit aligned?

### ISSUE THREAD

**Issue by bvarner** [prometheus/prometheus#7350]
**What did you do?**
I build prometheus from master, targeting an arm1176jzfshf (RaspberryPi zero W)

**What did you expect to see?**
I expected it to work. ;-)

**What did you see instead? Under which circumstances?**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x97d2a8]
goroutine 206 [running]:
runtime/internal/atomic.goStore64(0x5aca1c4, 0x8, 0x0)
         /usr/lib/go/src/runtime/internal/atomic/atomic_arm.go:144 +0x1c
github.com/prometheus/prometheus/tsdb/chunks.(*ChunkDiskMapper).cut(0x5aca1b0, 0x0, 0x0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go:343 +0x114
github.com/prometheus/prometheus/tsdb/chunks.(*ChunkDiskMapper).WriteChunk(0x5aca1b0, 0x1, 0x0, 0x8559439e, 0x172, 0x855ccdde, 0x172, 0x2c385b0, 0x5fbdd40, 0x0, ...)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go:242 +0xd0
 github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk(0x5dbe000, 0x5aca1b0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/tsdb/head.go:1988 +0x6c
 github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk(0x5dbe000, 0x855cd5ae, 0x172, 0x5aca1b0, 0x0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/tsdb/head.go:1962 +0x24
 github.com/prometheus/prometheus/tsdb.(*memSeries).append(0x5dbe000, 0x855cd5ae, 0x172, 0x0, 0x0, 0x119, 0x0, 0x5aca1b0, 0x5c7a0f0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/tsdb/head.go:2118 +0x3ac
 github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0x617abe0, 0x0, 0x0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/tsdb/head.go:1197 +0x1f8
 github.com/prometheus/prometheus/tsdb.dbAppender.Commit(0x2c32620, 0x617abe0, 0x5a7d300, 0x0, 0x21799e0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/tsdb/db.go:703 +0x24
 github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0x5db1560, 0x0, 0x5b2f9b0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/storage/fanout.go:162 +0x28
 github.com/prometheus/prometheus/scrape.(*scrapeLoop).report.func1(0x5862dd0, 0x2c323a0, 0x5afe2b0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/scrape/scrape.go:1293 +0x34
 github.com/prometheus/prometheus/scrape.(*scrapeLoop).report(0x5c7b040, 0x4fa38c36, 0xbfaebb5e, 0xf7bcd63d, 0x38, 0x3f255c8, 0x11af903, 0x0, 0x0, 0x0, ...)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/scrape/scrape.go:1311 +0x4b0
 github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0x5c7b040, 0x77359400, 0x0, 0x77359400, 0x0, 0x0)
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/scrape/scrape.go:986 +0x58c
 created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
         /opt/yocto/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/prometheus/1.0-r0/build/src/github.com/prometheus/prometheus/scrape/scrape.go:422 +0x3f8
```

**Environment**
yocto poky, dunfell branch, RaspberryPi Zero W

* System information:

`Linux 4.19.120 armv6l`

* Prometheus version:
My bitbake recipe isn't populating this yet... but it was built from master @ 6ff4814a492ae6f9e3f5cf7b022a823b631b7a95

prometheus, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.14.1

* Prometheus configuration file:
```
global:
  scrape_interval: 10s
  external_labels:
    monitor: 'pidroponics-monitor'
scrape_configs:
  - job_name: 'system'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'pidroponics'
    scrape_interval: 2s
    static_configs: 
      - targets: ['localhost:443']
```

**Comment by codesome** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/7365
