### ISSUE TITLE
Prometheus panic with file already closed

### ISSUE THREAD

**Issue by unixlab** [prometheus/prometheus#7378]
**What did you do?**
Updated Prometheus from 2.18.1 to 2.19.0 and started it

**What did you expect to see?**
Prometheus running without panicking

**What did you see instead? Under which circumstances?**
Prometheus crashed with `write /data/prometheus/data/chunks_head/000001: file already closed` after a bit more than 3.5 hours after the update.

**Workaround**
Going back to 2.18.1 seems to work for me

**Environment**
Prometheus 2.19.0 on arm7

* System information:
```
$ uname -srm
Linux 4.19.118-v7+ armv7l
```

* Prometheus version:
```
$ ./prometheus --version
prometheus, version 2.19.0 (branch: HEAD, revision: 5d7e3e970602c755855340cb190a972cebdd2ebf)
  build user:       root@d4cf5c7e268d
  build date:       20200609-11:35:36
  go version:       go1.14.4
```
* Logs:
```
Jun 09 22:11:43 prometheus-server systemd[1]: Started Prometheus Service.
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.627Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.0, branch=HEAD, revision=5d7e3e970602c755855340cb190a972cebdd2ebf)"
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.628Z caller=main.go:338 build_context="(go=go1.14.4, user=root@d4cf5c7e268d, date=20200609-11:35:36)"
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.628Z caller=main.go:339 host_details="(Linux 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l prometheus-server (none))"
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.628Z caller=main.go:340 fd_limits="(soft=1024, hard=524288)"
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.628Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.638Z caller=main.go:678 msg="Starting TSDB ..."
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.638Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.641Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1574640000000 maxt=1576389600000 ulid=01DW4CJKG2762A602JZB9SW4M1
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.643Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1576389600000 maxt=1578139200000 ulid=01DY3MC0F2A56WPGK2S6EYSXSS
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.643Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1578139200000 maxt=1578722400000 ulid=01DY9XA8MXS0SHJBBMBKGB5XC0
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.644Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1578722400000 maxt=1579305600000 ulid=01DYZQSQ8Z9F1KR9RTYQZD4QNB
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.645Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1579305600000 maxt=1579888800000 ulid=01E11CF4ANKRS8D31YZXABJ9PQ
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.645Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1579888800000 maxt=1580472000000 ulid=01E11CF4RXP64T6Y4NKFDGC084
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.646Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1580472000000 maxt=1581055200000 ulid=01E11CF57KEP88N2THMGE7WP2E
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.647Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1581055200000 maxt=1581638400000 ulid=01E11CF5P0E1H1QYFRFSBATGYJ
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.648Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1581638400000 maxt=1582221600000 ulid=01E1J6DD6G2VSQ7MWB4ZW55VDE
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.648Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1582221600000 maxt=1582804800000 ulid=01E23JK7RBXZF4C4RQA30RMX61
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.649Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1582804800000 maxt=1583388000000 ulid=01E2MYS3KC80Q2CQFXF0C4F86X
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.650Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1583388000000 maxt=1583971200000 ulid=01E36AYYFV9TCTKRCEN5N21ZDH
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.650Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1583971200000 maxt=1584554400000 ulid=01E3QQ4QH6236J019B36RZXDCH
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.651Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1584554400000 maxt=1585137600000 ulid=01E493AMC4XP367PQ0Z2ZNC15J
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.652Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1585137600000 maxt=1585720800000 ulid=01E4TFGFMW1V4BWQJTBFGS5YQ9
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.652Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1585720800000 maxt=1586304000000 ulid=01E5BVPB8QA6QX8YY4REHS3J6N
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.653Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1586304000000 maxt=1586887200000 ulid=01E5X7W6JGH1W6G02CYYS3C935
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.654Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1586887200000 maxt=1587470400000 ulid=01E6EM1ZF0F58NZZD3EKT54MMV
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.654Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1587470400000 maxt=1588053600000 ulid=01E7007TASB9KEARS2Z1Z5VWRM
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.655Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1588053600000 maxt=1588636800000 ulid=01E7HCDRMVF4CTPMF3MKSTVXVC
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.656Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1588636800000 maxt=1589220000000 ulid=01E82RKMGMYQRGAP55R6SN6CGQ
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.656Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1589220000000 maxt=1589803200000 ulid=01E8M4SEMKM4YS8BB3CJXKS260
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.657Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1589803200000 maxt=1590386400000 ulid=01E95GYZRBWWJMSD01YPJ6B2JW
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.658Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1590386400000 maxt=1590969600000 ulid=01E9PX4TZ1FJF4WGP32Y6NK8SD
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.658Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1590969600000 maxt=1591552800000 ulid=01EA89AQJC0VW5MEQ9GW4CEKW1
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.659Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591552800000 maxt=1591617600000 ulid=01EAA747JNZ830S1VN6YDQBWM9
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.659Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591617600000 maxt=1591682400000 ulid=01EAC4XRGXFJ622828T6CFRZRH
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.659Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591682400000 maxt=1591704000000 ulid=01EACSGYEHNMV5QKE0EAYQPAN2
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.660Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591725600000 maxt=1591732800000 ulid=01EADE439CN9TXG0C1XQTDXJMD
Jun 09 22:11:43 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:43.660Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591704000000 maxt=1591725600000 ulid=01EADE43N9PSFN76Z6MBMNFZA5
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.229Z caller=head.go:645 component=tsdb msg="Replaying WAL and on-disk memory mappable chunks if any, this may take a while"
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.296Z caller=head.go:682 component=tsdb msg="WAL checkpoint loaded"
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.504Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=4126 maxSegment=4130
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.641Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=4127 maxSegment=4130
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.817Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=4128 maxSegment=4130
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.838Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=4129 maxSegment=4130
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.839Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=4130 maxSegment=4130
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.839Z caller=head.go:709 component=tsdb msg="WAL replay completed" duration=609.632544ms
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.856Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.856Z caller=main.go:695 msg="TSDB started"
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.857Z caller=main.go:799 msg="Loading configuration file" filename=/data/prometheus/prometheus.yml
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.868Z caller=main.go:827 msg="Completed loading of configuration file" filename=/data/prometheus/prometheus.yml
Jun 09 22:11:44 prometheus-server prometheus[18034]: level=info ts=2020-06-09T21:11:44.868Z caller=main.go:646 msg="Server is ready to receive web requests."
Jun 10 00:00:14 prometheus-server prometheus[18034]: level=info ts=2020-06-09T23:00:14.247Z caller=compact.go:495 component=tsdb msg="write block" mint=1591732800000 maxt=1591740000000 ulid=01EADN030B9J7ZJCNZBE14DG8Z duration=284.446449ms
Jun 10 00:00:14 prometheus-server prometheus[18034]: level=info ts=2020-06-09T23:00:14.323Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=17.37865ms
Jun 10 00:00:14 prometheus-server prometheus[18034]: level=error ts=2020-06-09T23:00:14.351Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: mmap: cannot allocate memory"
Jun 10 02:00:14 prometheus-server prometheus[18034]: level=info ts=2020-06-10T01:00:14.247Z caller=compact.go:495 component=tsdb msg="write block" mint=1591740000000 maxt=1591747200000 ulid=01EADVVT8H43C3VPND6RBHAZQC duration=277.471134ms
Jun 10 02:00:14 prometheus-server prometheus[18034]: level=info ts=2020-06-10T01:00:14.309Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=13.146225ms
Jun 10 02:00:14 prometheus-server prometheus[18034]: level=error ts=2020-06-10T01:00:14.310Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: write /data/prometheus/data/chunks_head/000001: file a
Jun 10 02:00:17 prometheus-server prometheus[18034]: panic: write /data/prometheus/data/chunks_head/000001: file already closed
Jun 10 02:00:17 prometheus-server prometheus[18034]: goroutine 273 [running]:
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk(0x4a82000, 0x3ce59e0)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/tsdb/head.go:1991 +0x22c
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk(0x4a82000, 0x9bbdf789, 0x172, 0x3ce59e0, 0x0)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/tsdb/head.go:1962 +0x24
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/tsdb.(*memSeries).append(0x4a82000, 0x9bbdf789, 0x172, 0xd84f037, 0x3f0f1338, 0x11d9, 0x0, 0x3ce59e0, 0x0)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/tsdb/head.go:2118 +0x3a4
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0x4faa780, 0x0, 0x0)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/tsdb/head.go:1197 +0x1ec
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/tsdb.dbAppender.Commit(0x2406c28, 0x4faa780, 0x3cd3280, 0x1634d8c, 0x1953c07)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/tsdb/db.go:703 +0x24
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0x48c08e0, 0x0, 0x0)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/storage/fanout.go:162 +0x28
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/scrape.(*scrapeLoop).append.func1(0x4855dd4, 0x24069a8, 0x41ea930, 0x48be460, 0x4a10000, 0xe3c5, 0x13c68)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/scrape/scrape.go:1091 +0x34
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/scrape.(*scrapeLoop).append(0x48be460, 0x4a10000, 0xe3c5, 0x13c68, 0x48f7080, 0x28, 0x682b4027, 0xbfb02a08, 0x1b77906b, 0xc79, ...)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/scrape/scrape.go:1224 +0xa04
Jun 10 02:00:17 prometheus-server prometheus[18034]: github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0x48be460, 0xfc23ac00, 0x6, 0x540be400, 0x2, 0x0)
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/scrape/scrape.go:970 +0x47c
Jun 10 02:00:17 prometheus-server prometheus[18034]: created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
Jun 10 02:00:17 prometheus-server prometheus[18034]:         /app/scrape/scrape.go:422 +0x3c4
Jun 10 02:00:17 prometheus-server systemd[1]: prometheus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 10 02:00:17 prometheus-server systemd[1]: prometheus.service: Failed with result 'exit-code'.
```

**Comment by brian-brazil** [comment]
The first error is `head truncate failed: truncate chunks.HeadReadWriter: mmap: cannot allocate memory` so it sounds like you ran out of memory.

**Comment by unixlab** [comment]
Oh, I totally overlooked that. Sorry for the noise.
Than it's maybe not related to the update.
I'll close this issue and monitor if this happens again.
