### ISSUE TITLE
3G memory free yet still panic: mmap: cannot allocate memory

### ISSUE THREAD

**Issue by alevchuk** [prometheus/prometheus#7450]
**What did you do?**

Ran Prometheus for many month. It started crashing with unable to allocate memory.

```
~/gocode/src/github.com/prometheus/prometheus/prometheus --storage.tsdb.retention 5y
```

**What did you see instead? Under which circumstances?**

It crashes after ~1 hour of running. Then it crashes with instantly on start. Every time this the same error:
> panic: mmap: cannot allocate memory

if I delete WAL it runs for another 1 hour.  There is 3GB+ of free memory at all times (even after the crash, ~80% of free memory is linux page cache, yet that's trivially reclaimable)

i tried updating to latest prometheus, yet that does not help:

**Environment**

* System information:

	Linux 4.19.118-v8+ aarch64

* Prometheus version:

  prometheus, version 2.19.1 (branch: master, revision: 153f859b7499d23fc0300e97adf21110e349fcd2)
  build user:       prometheus@bl5
  build date:       20200623-15:48:56
  go version:       go1.13.1

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: 'node3'
  static_configs:
          - targets: ['a:123', 'b:234', 'c:345']
```

* Logs:
```
level=info ts=2020-06-24T11:29:32.106Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=6.219504ms
level=info ts=2020-06-24T11:29:32.121Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=44 last=45 duration=14.875294ms
level=info ts=2020-06-24T11:29:32.183Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=6.845589ms
level=info ts=2020-06-24T11:29:32.241Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=6.642739ms
level=info ts=2020-06-24T11:29:32.256Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=46 last=47 duration=14.692185ms
level=info ts=2020-06-24T11:29:32.316Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=6.27691ms
level=info ts=2020-06-24T11:29:32.373Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=6.267502ms
level=info ts=2020-06-24T11:29:32.387Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=48 last=49 duration=14.325485ms
level=info ts=2020-06-24T11:29:32.917Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1592546400000 maxt=1592568000000 ulid=01EBK1E5QH36EC9MXJTWJD01HH sourc
es="[01EB5WWTQJYFFEC1P2TWBNBAQH 01EB63RHZP1GJ5FDJJSP732GZC 01EB6AM97NDRBCY6X0NFKNQQ2Z]" duration=516.355204ms
level=error ts=2020-06-24T11:29:32.940Z caller=db.go:679 component=tsdb msg="compaction failed" err="reload blocks: corrupted block 01EBK1E5QH36EC9MXJTWJD01HH: mmap files: mmap: ca
nnot allocate memory"
level=info ts=2020-06-24T11:29:34.698Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1592546400000 maxt=1592568000000 ulid=01EBK1E77WVRMD3D3DEZGRX3S8 sourc
es="[01EB5WWTQJYFFEC1P2TWBNBAQH 01EB63RHZP1GJ5FDJJSP732GZC 01EB6AM97NDRBCY6X0NFKNQQ2Z]" duration=750.238495ms
level=error ts=2020-06-24T11:29:34.722Z caller=db.go:679 component=tsdb msg="compaction failed" err="reload blocks: corrupted block 01EBK1E77WVRMD3D3DEZGRX3S8: mmap files: mmap: ca
nnot allocate memory"


level=info ts=2020-06-24T11:30:39.617Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1592546400000 maxt=1592568000000 ulid=01EBK1G6GRVSDCD2H3CKQV2DNC sourc
es="[01EB5WWTQJYFFEC1P2TWBNBAQH 01EB63RHZP1GJ5FDJJSP732GZC 01EB6AM97NDRBCY6X0NFKNQQ2Z]" duration=873.483238ms
level=error ts=2020-06-24T11:30:39.645Z caller=db.go:679 component=tsdb msg="compaction failed" err="reload blocks: corrupted block 01EBK1G6GRVSDCD2H3CKQV2DNC: mmap files: mmap: ca
nnot allocate memory"


level=info ts=2020-06-24T11:54:45.514Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1592546400000 maxt=1592568000000 ulid=01EBK2WATXK84CN8AXEJ8HZBZ6 sourc
es="[01EB5WWTQJYFFEC1P2TWBNBAQH 01EB63RHZP1GJ5FDJJSP732GZC 01EB6AM97NDRBCY6X0NFKNQQ2Z]" duration=557.462005ms
level=error ts=2020-06-24T11:54:45.543Z caller=db.go:679 component=tsdb msg="compaction failed" err="reload blocks: corrupted block 01EBK2WATXK84CN8AXEJ8HZBZ6: mmap files: mmap: ca
nnot allocate memory"
level=info ts=2020-06-24T11:57:46.133Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1592546400000 maxt=1592568000000 ulid=01EBK31V6Q6JWQPNV5W9V912E3 sourc
es="[01EB5WWTQJYFFEC1P2TWBNBAQH 01EB63RHZP1GJ5FDJJSP732GZC 01EB6AM97NDRBCY6X0NFKNQQ2Z]" duration=573.828861ms
level=error ts=2020-06-24T11:57:46.158Z caller=db.go:679 component=tsdb msg="compaction failed" err="reload blocks: corrupted block 01EBK31V6Q6JWQPNV5W9V912E3: mmap files: mmap: ca
nnot allocate memory"
panic: mmap: cannot allocate memory

goroutine 615 [running]:
github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk(0x62d6630, 0x54b0090)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/tsdb/head.go:1991 +0x22c
github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk(0x62d6630, 0xe6330235, 0x172, 0x54b0090, 0x2000)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/tsdb/head.go:1962 +0x24
github.com/prometheus/prometheus/tsdb.(*memSeries).append(0x62d6630, 0xe6330235, 0x172, 0x0, 0x0, 0xf46, 0x0, 0x54b0090, 0x7bb14)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/tsdb/head.go:2118 +0x3a0
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0x61e6730, 0x0, 0x0)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/tsdb/head.go:1197 +0x230
github.com/prometheus/prometheus/tsdb.dbAppender.Commit(0x2513908, 0x61e6730, 0x55b5a00, 0x0, 0x16df44c)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/tsdb/db.go:707 +0x24
github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0x6c24700, 0x6511cb8, 0xc)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/storage/fanout.go:162 +0x28
github.com/prometheus/prometheus/scrape.(*scrapeLoop).report.func1(0x6511dbc, 0x2513568, 0x61e2500)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/scrape/scrape.go:1293 +0x34
github.com/prometheus/prometheus/scrape.(*scrapeLoop).report(0x6013950, 0x8609de4a, 0xbfb4edf0, 0x8c906ab5, 0x1ac, 0x362c360, 0x1df296f, 0x0, 0x0, 0x0, ...)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/scrape/scrape.go:1311 +0x45c
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0x6013950, 0x7e11d600, 0x3, 0x540be400, 0x2, 0x0)
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/scrape/scrape.go:986 +0x58c
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
        /home/prometheus/gocode/src/github.com/prometheus/prometheus/scrape/scrape.go:422 +0x3c8


```

**Comment by alevchuk** [comment]
it seems i was able to fix this by migrating 64-bit binaries and updating node

my hardware is 64-bit raspberry pi, yet raspbian operating system is 32-bit

i was able to setup a 64-bit binaries evironment by using `schroot` and `debootstrap` like this https://github.com/alevchuk/minibank/blob/first/grafana/README.md#chroot-for-64-bit-environment

also being in 32-bit i was forced to use node version no higher than  v13.7.0, now i upgraded that as well

the world has moved to 64-bit so i accept that this is a proper fix 

i'll let this run for another day, and close it if i confirm this fix works permanently

**Comment by beorn7** [comment]
Yeah, 32bit only works for tiny setups as a lot got mmap'd by Prometheus.

**Comment by alevchuk** [comment]
yep, works perfectly now!

It's an invisible trap. I ran into this issue for several years and though it's just because Prometheus is not reliable.
Should we print warning logs (e.g. after each compaction) if running in 32-bit mode?

**Comment by codesome** [comment]
> Should we continuously print warning logs (e.g. before each compaction) if running in 32-bit mode?

That would be noise and 32-bit version is not always an issue depending on the use-case.
