### ISSUE TITLE
Prometheus: fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by jirib** [prometheus/prometheus#7547]
**What did you do?**

A user was creating a report in Grafana with range > 1 d.

**What did you expect to see?**

Prometheus not failing.

**What did you see instead? Under which circumstances?**

fatal error: runtime: out of memory

**Environment**

* System information:

`Linux 4.14.154-128.181.amzn2.x86_64 x86_64`

* Prometheus version:

```
# docker-compose exec prometheus prometheus --version
prometheus, version 2.19.1 (branch: HEAD, revision: eba3fdcbf0d378b66600281903e3aab515732b39)
  build user:       root@62700b3d0ef9
  build date:       20200618-16:35:26
  go version:       go1.14.4
```
```
services:
  prometheus:
    image: "prom/prometheus:v2.19.1"
    environment:
      TZ: "Europe/Prague"
    ports:
      - 9090:9090
    volumes:
      - /opt/tm/central_monitor/configs/prometheus:/etc/prometheus/
      - /data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=365d'
      - '--web.external-url=https://monitoring.example.com/prometheus/'
      - '--web.enable-admin-api'
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:514"
        syslog-format: "rfc3164"
        tag: "prometheus-{{.ID}}"
```

* Prometheus configuration file:
```
# Details the meanings of different sections can be found at
# https://prometheus.io/docs/prometheus/latest/configuration/configuration
global:
  scrape_interval:     29s
  evaluation_interval: 29s
  scrape_timeout: 25s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: "/alertmanager"
      static_configs:
      - targets:
        - "alertmanager:9093"

scrape_configs:
  - job_name: 'federate'

    # So we keep customer's labels
    honor_labels: true
    # does not matter with curent implementation
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~".+"}'

    static_configs:
      - targets:
        # Has to be in same docker network/DNS resolvable
        - 'listener:9098'

  - job_name: 'soc'
    static_configs:
      - targets:
        - 'soc2.example.com:9144'
        - 'soc2.example.com:9145'

  - job_name: 'blackbox-external-slsp-prod-js-federated-login'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://c115.example.com:8043/application/federated-login/get-js|http_afs_js
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-prod-js-federated-login'
        target_label: instance
      - target_label: target
        replacement: 'js'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'prod'

  - job_name: 'blackbox-external-slsp-prod-api'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://c115.example.com:8053/v2/status/health|http_afs_api_slsp_prod
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-prod-api'
        target_label: instance
      - target_label: target
        replacement: 'api'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'prod'

  - job_name: 'blackbox-external-slsp-uat1-js-federated-login'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8043/application/federated-login/get-js|http_afs_js
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-uat1-js-federated-login'
        target_label: instance
      - target_label: target
        replacement: 'js'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'uat1'

  - job_name: 'blackbox-external-slsp-uat1-api'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8053/v2/status/health|http_afs_api_slsp_nonprod
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-uat1-api'
        target_label: instance
      - target_label: target
        replacement: 'api'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'uat1'

  - job_name: 'blackbox-external-slsp-uat1-web'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://c111.example.com|http_afs_web
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-uat1-web'
        target_label: instance
      - target_label: target
        replacement: 'web'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'uat1'

  - job_name: 'blackbox-external-slsp-uat2-js-federated-login'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8043/application/federated-login/get-js|http_afs_js
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-uat2-js-federated-login'
        target_label: instance
      - target_label: target
        replacement: 'js'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'uat2'

  - job_name: 'blackbox-external-slsp-uat2-api'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8053/v2/status/health|http_afs_api_slsp_nonprod
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-uat2-api'
        target_label: instance
      - target_label: target
        replacement: 'api'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'uat2'

  - job_name: 'blackbox-external-slsp-uat2-web'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://c110.example.com|http_afs_web
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-uat2-web'
        target_label: instance
      - target_label: target
        replacement: 'web'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'uat2'

  - job_name: 'blackbox-external-slsp-perf-js-federated-login'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8043/application/federated-login/get-js|http_afs_js
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-perf-js-federated-login'
        target_label: instance
      - target_label: target
        replacement: 'js'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'perf'

  - job_name: 'blackbox-external-slsp-perf-api'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8053/v2/status/health|http_afs_api_slsp_nonprod
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-perf-api'
        target_label: instance
      - target_label: target
        replacement: 'api'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'perf'

  - job_name: 'blackbox-external-slsp-perf-web'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://c112.example.com|http_afs_web
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-perf-web'
        target_label: instance
      - target_label: target
        replacement: 'web'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'perf'

  - job_name: 'blackbox-external-slsp-asseco-js-federated-login'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8043/application/federated-login/get-js|http_afs_js
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-asseco-js-federated-login'
        target_label: instance
      - target_label: target
        replacement: 'js'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'asseco'

  - job_name: 'blackbox-external-slsp-asseco-api'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://1.1.1.1:8053/v2/status/health|http_afs_api_slsp_nonprod
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-asseco-api'
        target_label: instance
      - target_label: target
        replacement: 'api'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'asseco'

  - job_name: 'blackbox-external-slsp-asseco-web'
    metrics_path: /probe
    static_configs:
    - targets:
      - https://c113.example.com|http_afs_web
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*?)\|(.*)
        target_label: __param_module
        replacement: ${2}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    metric_relabel_configs:
      - source_labels: [instance]
        replacement: 'slsp-asseco-web'
        target_label: instance
      - target_label: target
        replacement: 'web'
      - target_label: external
        replacement: 'true'
      - target_label: deployment
        replacement: 'slsp'
      - target_label: environment
        replacement: 'asseco'
```

* Logs:
```
Jul 10 09:52:05 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: level=error ts=2020-07-10T07:52:04.941Z caller=api.go:1451 component=web msg="error writing response" bytesWritten=0 err="write tcp 172.20.0.5:9090->172.20.0.6:48002: write: broken pipe"
Jul 10 09:52:14 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: level=error ts=2020-07-10T07:52:14.373Z caller=api.go:1451 component=web msg="error writing response" bytesWritten=0 err="write tcp 172.20.0.5:9090->172.20.0.6:48216: write: broken pipe"
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: fatal error: runtime: out of memory
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime stack:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.throw(0x275fa66, 0x16)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/panic.go:1116 +0x72
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.sysMap(0xc8bc000000, 0x18000000, 0x43341f8)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.(*mheap).sysAlloc(0x431f2a0, 0x18000000, 0x431f2a8, 0xbe10)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/malloc.go:715 +0x1cd
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.(*mheap).grow(0x431f2a0, 0xbe10, 0x0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/mheap.go:1286 +0x11c
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.(*mheap).allocSpan(0x431f2a0, 0xbe10, 0x420100, 0x4334208, 0x200000000)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/mheap.go:1124 +0x6a0
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.(*mheap).alloc.func1()
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/mheap.go:871 +0x64
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.(*mheap).alloc(0x431f2a0, 0xbe10, 0x460101, 0x431f2a0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/mheap.go:865 +0x81
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.largeAlloc(0x17c1e618, 0x101, 0x431f2a0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/malloc.go:1152 +0x92
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.mallocgc.func1()
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/malloc.go:1047 +0x46
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.systemstack(0x0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.mstart()
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/proc.go:1041
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 1079 [running]:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.systemstack_switch()
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0f8a71808 sp=0xc0f8a71800 pc=0x4656e0
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.mallocgc(0x17c1e618, 0x21a1400, 0x1, 0x334250)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/malloc.go:1046 +0x895 fp=0xc0f8a718a8 sp=0xc0f8a71808 pc=0x40cc25
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.makeslice(0x21a1400, 0x17c1e618, 0x17c1e618, 0xc0664e81c0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc0f8a718d8 sp=0xc0f8a718a8 pc=0x44c6cc
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: bytes.makeSlice(0x17c1e618, 0x0, 0x0, 0x0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/bytes/buffer.go:229 +0x73 fp=0xc0f8a71918 sp=0xc0f8a718d8 pc=0x546c23
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: bytes.(*Buffer).grow(0xc83b39cbd0, 0x200, 0x97345)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/bytes/buffer.go:142 +0x15b fp=0xc0f8a71968 sp=0xc0f8a71918 pc=0x54656b
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: bytes.(*Buffer).ReadFrom(0xc83b39cbd0, 0x2f3e900, 0xc0664e8200, 0x7fe72b46b9f0, 0xc83b39cbd0, 0x709b01)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/bytes/buffer.go:202 +0x48 fp=0xc0f8a719d8 sp=0xc0f8a71968 pc=0x546a18
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: io.copyBuffer(0x2f3b1c0, 0xc83b39cbd0, 0x2f3e900, 0xc0664e8200, 0x0, 0x0, 0x0, 0x0, 0x8, 0x0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/io/io.go:391 +0x2fc fp=0xc0f8a71a50 sp=0xc0f8a719d8 pc=0x4d044c
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: io.Copy(...)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/io/io.go:364
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: github.com/prometheus/prometheus/scrape.(*targetScraper).scrape(0xc03f9dbfb0, 0x2f8d020, 0xc84a27c660, 0x2f3b1c0, 0xc83b39cbd0, 0x0, 0x0, 0x0, 0x0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/scrape/scrape.go:564 +0x231 fp=0xc0f8a71c40 sp=0xc0f8a71a50 pc=0x1e7fd31
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc0403befa0, 0x6c088e200, 0x5d21dba00, 0x0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/scrape/scrape.go:950 +0x49f fp=0xc0f8a71fc0 sp=0xc0f8a71c40 pc=0x1e828ef
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: runtime.goexit()
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0f8a71fc8 sp=0xc0f8a71fc0 pc=0x467671
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/scrape/scrape.go:422 +0x532
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 1 [chan receive, 5 minutes]:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: github.com/oklog/run.(*Group).Run(0xc0005b5b78, 0xc00060a620, 0x8)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/vendor/github.com/oklog/run/group.go:43 +0xed
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: main.main()
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/cmd/prometheus/main.go:757 +0x6be5
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 31 [select]:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: go.opencensus.io/stats/view.(*worker).start(0xc0000913b0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: created by go.opencensus.io/stats/view.init.0
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 33 [chan receive]:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: k8s.io/klog/v2.(*loggingT).flushDaemon(0x43066c0)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/vendor/k8s.io/klog/v2/klog.go:1107 +0x8b
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: created by k8s.io/klog/v2.init.0
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/vendor/k8s.io/klog/v2/klog.go:416 +0xd6
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 64 [select]:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: github.com/prometheus/prometheus/pkg/logging.(*Deduper).run(0xc00004ee80)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/pkg/logging/dedupe.go:75 +0x1db
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: created by github.com/prometheus/prometheus/pkg/logging.Dedupe
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/pkg/logging/dedupe.go:61 +0xcf
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 70 [select]:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: github.com/prometheus/prometheus/discovery.(*Manager).sender(0xc0003d9360)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/discovery/manager.go:263 +0x117
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: created by github.com/prometheus/prometheus/discovery.(*Manager).Run
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/discovery/manager.go:170 +0x43
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 86 [chan receive]:
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: github.com/prometheus/prometheus/storage/remote.(*WriteStorage).run(0xc00076c680)
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/storage/remote/write.go:84 +0xb2
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: created by github.com/prometheus/prometheus/storage/remote.NewWriteStorage
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: #011/app/storage/remote/write.go:77 +0x19a
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: 
Jul 10 09:52:18 customer-monitoring0.example.com prometheus-497f3ddf023b[330]: goroutine 121 [syscall, 5 minutes]:
...
```

Full log here: https://gist.github.com/jirib/a467ceb0fe5f65c39718b1deb68e7b58

**Comment by arj22** [comment]
@jirib what was the solution to this issue? I'm running into the same error

**Comment by jirib** [comment]
> @jirib what was the solution to this issue? I'm running into the same error

IIRC increased memory.
