### ISSUE TITLE
memSeries: Iterator panic.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7548]
Something we seen on our production:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f941a]

goroutine 473896 [running]:
github.com/prometheus/prometheus/tsdb.(*memSeries).iterator(0xc0d7afeb60, 0x0, 0xc1b6b7cfc0, 0xc000bd0180, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200629082805-315564210816/tsdb/head.go:2202 +0x84a
github.com/prometheus/prometheus/tsdb.(*safeChunk).Iterator(0xc1b76208d0, 0x0, 0x0, 0x41d7bcbe6a800001, 0xc1b761bd40)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200629082805-315564210816/tsdb/head.go:1513 +0x76
github.com/prometheus/prometheus/tsdb.(*chunkSeriesIterator).resetCurIterator(0xc1b761bd40)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200629082805-315564210816/tsdb/querier.go:1090 +0x6b
github.com/prometheus/prometheus/tsdb.newChunkSeriesIterator(...)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200629082805-315564210816/tsdb/querier.go:1083
github.com/prometheus/prometheus/tsdb.(*chunkSeries).Iterator(0xc1b761ba40, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200629082805-315564210816/tsdb/querier.go:891 +0xf6
github.com/prometheus/prometheus/tsdb.(*chainedSeriesIterator).Next(0xc1b76209c0, 0x1730c9725b8)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200629082805-315564210816/tsdb/querier.go:952 +0xaa
github.com/thanos-io/thanos/pkg/store.(*TSDBStore).encodeChunks(0xc0467bc040, 0x266ade0, 0xc1b76209c0, 0xffff, 0xc000af1880, 0x3, 0x4, 0xc1b7441c20, 0xf)
	/go/src/github.com/thanos-io/thanos/pkg/store/tsdb.go:167 +0x130
github.com/thanos-io/thanos/pkg/store.(*TSDBStore).Series(0xc0467bc040, 0xc1b6374cc0, 0x2685f80, 0xc1b6374d80, 0x0, 
0x0)
	/go/src/github.com/thanos-io/thanos/pkg/store/tsdb.go:128 +0x8c5
github.com/thanos-io/thanos/pkg/store.(*tenantSeriesSetServer).Series.func1(0x266a520, 0xc1b6b7ce70)
	/go/src/github.com/thanos-io/thanos/pkg/store/multitsdb.go:120 +0x51
github.com/thanos-io/thanos/pkg/tracing.DoInSpan(0x266a520, 0xc1b6b7ce10, 0x21af9c3, 0x17, 0xc284cb0f48, 0x0, 0x0, 0x0)
	/go/src/github.com/thanos-io/thanos/pkg/tracing/tracing.go:72 +0xcc
github.com/thanos-io/thanos/pkg/store.(*tenantSeriesSetServer).Series(0xc1b6374d80, 0xc0467bc040, 0xc1b6374cc0)
	/go/src/github.com/thanos-io/thanos/pkg/store/multitsdb.go:119 +0xeb
github.com/thanos-io/thanos/pkg/store.(*MultiTSDBStore).Series.func1.2(0xc1088eaa10, 0xc1b6374d80, 0xc0467bc040, 0xc1b6374cc0)
	/go/src/github.com/thanos-io/thanos/pkg/store/multitsdb.go:203 +0x6b
created by github.com/thanos-io/thanos/pkg/store.(*MultiTSDBStore).Series.func1
	/go/src/github.com/thanos-io/thanos/pkg/store/multitsdb.go:201 +0x419
```

TSDB version (go mod): `20200629082805-315564210816`

```
                // mmappedChunks does not contain the last chunk. Hence check it separately.
		if len(s.mmappedChunks) < ix {
			previousSamples += s.headChunk.chunk.NumSamples()
		} else {
			totalSamples += s.headChunk.chunk.NumSamples()   <---- panic
		}
```

cc @pracucci

**Comment by codesome** [comment]
We faced this as well in Cortex. There was a WAL corruption due to the disk filling up and this panic happened after the restart and during compaction. Deleting the `chunks_head` directory and restarting again fixed it, so, it's something to do with m-mapping (of course, as this part was introduced with that :))

**Comment by pstibrany** [comment]
In our case, this happened:

- Cortex ran out of disk space, because it was unable to cut new block from head (symbols issue).
- After restart, WAL replay was loading segments 23088 up to maxSegment=23717
- Everything went fine until `msg="WAL segment loaded" segment=23706 maxSegment=23717`

- Segment 23707 was corrupted:
```
caller=db.go:634 msg="Encountered WAL read error, attempting repair" err="read records: corruption in segment /data/tsdb/10428/wal/00023707 at 82231554: unexpected checksum b995b79, expected 59b7568b"
caller=wal.go:354 msg="Starting corruption repair" segment=23707 offset=82231554
```

Which then caused deletion of remaining (10) segments, and rewrite of corrupted one:
```
caller=wal.go:362 msg="Deleting all segments newer than corrupted segment" segment=23707
caller=wal.go:384 msg="Rewrite corrupted segment" segment=23707
```

- After that, compaction started. This successfully created many blocks, but the last block, which failed with the same panic. In our case, Prometheus go.mod version is  `v1.8.2-0.20200711170716-492061b24c00` (line numbers are different, but it is same `totalSamples += s.headChunk.chunk.NumSamples()` line).

- This panic happens every time we try to compact same TSDB.
- As @codesome wrote above, removing chunks_head directory helped. Force-compaction (using `userDB.CompactHead(tsdb.NewRangeHead(h, h.MinTime(), h.MaxTime()))`) cut the final block.

**Comment by codesome** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/7550
