### ISSUE TITLE
go routine leak in k8s tests

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7692]
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 660 in state chan receive, with k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop on top of the stack:
goroutine 660 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc0003f8cc0)
	/home/circleci/project/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0x149
created by k8s.io/client-go/util/workqueue.newQueue
	/home/circleci/project/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x28c

 Goroutine 658 in state chan receive, with k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop on top of the stack:
goroutine 658 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc0003f8c60)
	/home/circleci/project/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0x149
created by k8s.io/client-go/util/workqueue.newQueue
	/home/circleci/project/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x28c
]
FAIL	github.com/prometheus/prometheus/discovery/kubernetes	14.195s
```
In: master

**Comment by ClementIV** [comment]
I want to fix this bug.
could you give more info about this issues？
Q1: How to get this error？
Q2: Which branch is used？
