### ISSUE TITLE
nil panic for missing regexp in relabel config

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#787]
If you omit the regexp from a relabel config, prometheus starts and crashes because of nil pointer dereference:

```
goroutine 56 [running]:
github.com/prometheus/prometheus/retrieval.relabel(0xc20949aea0, 0xc2081886c0, 0xc20949aea0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/relabel.go:50 +0x62c
github.com/prometheus/prometheus/retrieval.Relabel(0xc20949ac90, 0xc20818a620, 0x3, 0x3, 0xc209285dc8, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/relabel.go:22 +0x1f1
```

**Comment by fabxc** [comment]
Thanks
