### ISSUE TITLE
panic - close of closed channel - after POST /-/quit

### ISSUE THREAD

**Issue by jamiecyber** [prometheus/prometheus#8144]
**What did you do?**

working on a lifecycle preStop hook -- something like:

date >> /dev/termination-log
echo Lifecycle preStop hook invoked >> /dev/termination-log
wget -S -T120 http://localhost:9090/-/quit >> /dev/termination-log

**What did you expect to see?**

relatively clean shutdown

**What did you see instead? Under which circumstances?**

```
/prometheus $ wget --post-data '' -T120 -S http://localhost:9090/-/quit
Requesting termination... Goodbye!

(golang panic appears in the container logs...)

/prometheus $ ps auwx
PID   USER     TIME  COMMAND
    1 nobody    1h29 /bin/prometheus --storage.tsdb.min-block-duration=15m --storage.tsdb.max-block-duration=2h --storage.tsdb.retention.time=7d --config.file=/etc/conf
   76 nobody    0:00 sh
  145 nobody    0:00 ps auwx

/prometheus $ kill -TERM 1
/prometheus $ ps auwx
PID   USER     TIME  COMMAND
    1 nobody    1h33 /bin/prometheus --storage.tsdb.min-block-duration=15m --storage.tsdb.max-block-duration=2h --storage.tsdb.retention.time=7d --config.file=/etc/conf
   76 nobody    0:00 sh
  147 nobody    0:00 ps auwx
```

**Environment**

* System information:

kubernetes v1.15.12
image: prom/prometheus:v2.22.0

/prometheus $ uname -srm
Linux 4.19.145-flatcar x86_64

* Prometheus version:

/prometheus $ prometheus --version
prometheus, version 2.22.0 (branch: HEAD, revision: 0a7fdd3b76960808c3a91d92267c3d815c1bc354)
  build user:       root@6321101b2c50
  build date:       20201015-12:29:59
  go version:       go1.15.3
  platform:         linux/amd64

* Alertmanager version:

N/A

* Prometheus configuration file:

N/A

* Alertmanager configuration file:

N/A

* Logs:
```
level=info ts=2020-11-03T05:53:37.854Z caller=main.go:353 msg="Starting Prometheus" version="(version=2.22.0, branch=HEAD, revision=0a7fdd3b76960808c3a91d92267c3d815c1bc354)"
level=info ts=2020-11-03T05:53:37.854Z caller=main.go:358 build_context="(go=go1.15.3, user=root@6321101b2c50, date=20201015-12:29:59)"
level=info ts=2020-11-03T05:53:37.854Z caller=main.go:359 host_details="(Linux 4.19.145-flatcar #1 SMP Mon Sep 14 17:52:28 -00 2020 x86_64 infra-prometheus-server-64f48b4448-fgmbh (none))"
level=info ts=2020-11-03T05:53:37.854Z caller=main.go:360 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-11-03T05:53:37.854Z caller=main.go:361 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-11-03T05:53:37.859Z caller=web.go:516 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-11-03T05:53:37.859Z caller=main.go:712 msg="Starting TSDB ..."
level=info ts=2020-11-03T05:53:37.861Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603800000000 maxt=1603864800000 ulid=01ENQ7YMZRPJ3T3B0Y7FBV3HY3
level=info ts=2020-11-03T05:53:37.861Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603886400000 maxt=1603893600000 ulid=01ENQVJ3C8X6584QNJWMQ4FZXN
level=info ts=2020-11-03T05:53:37.862Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603864800000 maxt=1603886400000 ulid=01ENQW1Q93YPJPHGJ4YED5S4S7
level=info ts=2020-11-03T05:53:37.862Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603893600000 maxt=1603900800000 ulid=01ENR2DTM52XQJYFQJP8XVBHPZ
level=info ts=2020-11-03T05:53:37.863Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603900800000 maxt=1603908000000 ulid=01ENR99HW6WPGPBQ9NJSH99NJE
level=info ts=2020-11-03T05:53:37.864Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603908000000 maxt=1603908900000 ulid=01EP3BMF71SCT6DTNF92NK23RN
level=info ts=2020-11-03T05:53:37.864Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603908900000 maxt=1603909800000 ulid=01EP3FF9397NYPGNWP1XP3NAQX
level=info ts=2020-11-03T05:53:37.865Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1603909800000 maxt=1603910700000 ulid=01EP3KNFSXR85XKJ73Y0520A8Y
level=info ts=2020-11-03T05:53:45.160Z caller=head.go:642 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=warn ts=2020-11-03T06:07:31.138Z caller=main.go:565 msg="Received termination request via web service, exiting gracefully..."
level=info ts=2020-11-03T06:07:31.138Z caller=main.go:585 msg="Stopping scrape discovery manager..."
level=info ts=2020-11-03T06:07:31.138Z caller=main.go:599 msg="Stopping notify discovery manager..."
level=info ts=2020-11-03T06:07:31.138Z caller=main.go:621 msg="Stopping scrape manager..."
level=info ts=2020-11-03T06:07:31.138Z caller=main.go:595 msg="Notify discovery manager stopped"
level=info ts=2020-11-03T06:07:31.138Z caller=main.go:581 msg="Scrape discovery manager stopped"
level=error ts=2020-11-03T06:07:58.703Z caller=web.go:96 component=web msg="panic while serving request" client=127.0.0.1:48804 url=/-/quit err="close of closed channel" stack="

goroutine 64 [running]:
github.com/prometheus/prometheus/web.withStackTracer.func1.1(0x30867c0, 0xc0011416e0, 0xc047f42400)
	/app/web/web.go:95 +0xba
panic(0x2563540, 0x3030f30)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1(0xc07e250420, 0x31092c0, 0x41fe980)
	/app/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:150 +0x191
panic(0x2563540, 0x3030f30)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/prometheus/prometheus/web.(*Handler).quit(...)
	/app/web/web.go:910
net/http.HandlerFunc.ServeHTTP(0xc0005244e0, 0x7f565c4fa280, 0xc00222e370, 0xc047f42700)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x7f565c4fa280, 0xc00222e320, 0xc047f42700) /app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:196 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc0002ff1a0, 0x7f565c4fa280, 0xc00222e320, 0xc047f42700)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x7f565c4fa280, 0xc00222e320, 0xc047f42700)
	/app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:76 +0xb2
net/http.HandlerFunc.ServeHTTP(0xc0002ffa40, 0x7f565c4fa280, 0xc00222e320, 0xc047f42700)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x30d0680, 0xc00222e2d0, 0xc047f42700)
	/app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
github.com/prometheus/prometheus/web.setPathWithPrefix.func1.1(0x30d0680, 0xc00222e2d0, 0xc047f42600)
	/app/web/web.go:1099 +0x1dc
github.com/prometheus/common/route.(*Router).handle.func1(0x30d0680, 0xc00222e2d0, 0xc047f42500, 0x0, 0x0, 0x0)
	/app/vendor/github.com/prometheus/common/route/route.go:83 +0x283
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00037aa20, 0x30d0680, 0xc00222e2d0, 0xc047f42500)
	/app/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xc7e
github.com/prometheus/common/route.(*Router).ServeHTTP(0xc001241540, 0x30d0680, 0xc00222e2d0, 0xc047f42500)
	/app/vendor/github.com/prometheus/common/route/route.go:121 +0x4c
net/http.(*ServeMux).ServeHTTP(0xc00118a380, 0x30d0680, 0xc00222e2d0, 0xc047f42500)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x30ceb40, 0xc0591be1c0, 0xc047f42400)
	/app/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154 +0x5e4
net/http.HandlerFunc.ServeHTTP(0xc00118ac80, 0x30ceb40, 0xc0591be1c0, 0xc047f42400)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/prometheus/prometheus/web.withStackTracer.func1(0x30ceb40, 0xc0591be1c0, 0xc047f42400)
	/app/web/web.go:100 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc0010f1140, 0x30ceb40, 0xc0591be1c0, 0xc047f42400)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc00019e000, 0x30ceb40, 0xc0591be1c0, 0xc047f42400)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00014c280, 0x30d8180, 0xc0594e8700)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c


level=error ts=2020-11-03T06:07:58.703Z caller=stdlib.go:89 component=web caller="http: panic serving 127.0.0.1:48804" msg="close of closed channel"
```

**Comment by roidelapluie** [comment]
It seems you are calling /-/quit simulaniously. I have open #8166 to fix this.

The real question is what was prometheus doing between 06:07:31 (when asked to stop) and 06:07:58 (when a second /-/quit was called).

**Comment by johejo** [comment]
This issue doesn't seem to be fixed.

In my env, the test that added in #8166 is flaky.

```
$ git log -n 1
commit a6e18916ab4090a21e222e040458b52ca5053cf7 (HEAD -> master, origin/master, origin/HEAD)
Author: johncming <johncming@yahoo.com>
Date:   Mon Nov 30 16:55:33 2020 +0800

    tsdb: Remove duplicate variables. (#8239)

    Signed-off-by: johncming <johncming@yahoo.com>
```

```
$ for i in `seq 10`; do go test ./web -run TestHandleMultipleQuitRequests -count=1 -v; done
=== RUN   TestHandleMultipleQuitRequests
--- PASS: TestHandleMultipleQuitRequests (5.00s)
PASS
ok      github.com/prometheus/prometheus/web    5.027s
=== RUN   TestHandleMultipleQuitRequests
--- PASS: TestHandleMultipleQuitRequests (5.00s)
PASS
ok      github.com/prometheus/prometheus/web    5.026s
=== RUN   TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
FAIL
FAIL    github.com/prometheus/prometheus/web    5.028s
FAIL
=== RUN   TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
FAIL
FAIL    github.com/prometheus/prometheus/web    5.026s
FAIL
=== RUN   TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
FAIL
FAIL    github.com/prometheus/prometheus/web    5.027s
FAIL
=== RUN   TestHandleMultipleQuitRequests
--- PASS: TestHandleMultipleQuitRequests (5.00s)
PASS
ok      github.com/prometheus/prometheus/web    5.024s
=== RUN   TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
FAIL
FAIL    github.com/prometheus/prometheus/web    5.027s
FAIL
=== RUN   TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
FAIL
FAIL    github.com/prometheus/prometheus/web    5.026s
FAIL
=== RUN   TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
FAIL
FAIL    github.com/prometheus/prometheus/web    5.026s
FAIL
=== RUN   TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
    web_test.go:492:
                Error Trace:    web_test.go:492
                                                        asm_amd64.s:1374
                Error:          Received unexpected error:
                                Post "http://localhost:9090/-/quit": EOF
                Test:           TestHandleMultipleQuitRequests
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
FAIL
FAIL    github.com/prometheus/prometheus/web    5.027s
FAIL
```
