### ISSUE TITLE
Prometheus crash with "unexpected fault address 0x7f16221ef000"

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#8350]
**Environment**

* System information:

	Linux 5.0.0-29-generic x86_64

* Prometheus version:

	version 2.15.2
```


* Logs:
```
unexpected fault address 0x7f16221ef000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f16221ef000 pc=0x460388]

goroutine 1 [running]:
runtime.throw(0x24e01c1, 0x5)
  /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0006cb3d8 sp=0xc0006cb3a8 pc=0x42f5d2
runtime.sigpanic()
  /usr/local/go/src/runtime/signal_unix.go:391 +0x455 fp=0xc0006cb408 sp=0xc0006cb3d8 pc=0x444c85
runtime.memmove(0x7f16221ef000, 0x24dd696, 0x1)
  /usr/local/go/src/runtime/memmove_amd64.s:146 +0x108 fp=0xc0006cb410 sp=0xc0006cb408 pc=0x460388
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffd72b9b18b, 0xb, 0x14, 0x2c66840, 0xc000771530, 0x2c66840)
  /home/golang/src/github.com/prometheus/prometheus/promql/query_logger.go:118 +0x362 fp=0xc0006cb558 sp=0xc0006cb410 pc=0x1c84722
main.main()
  /home/golang/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:383 +0x538f fp=0xc0006cbf60 sp=0xc0006cb558 pc=0x1dd3eaf
runtime.main()
  /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0006cbfe0 sp=0xc0006cbf60 pc=0x430f6e
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0006cbfe8 sp=0xc0006cbfe0 pc=0x45f0d1

goroutine 17 [syscall]:
os/signal.signal_recv(0x0)
  /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
  /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
  /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00013edc0)
  /home/golang/src/github.com/prometheus/prometheus/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
  /home/golang/src/github.com/prometheus/prometheus/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 102 [select]:
github.com/prometheus/prometheus/pkg/logging.(*Deduper).run(0xc00012d280)
  /home/golang/src/github.com/prometheus/prometheus/pkg/logging/dedupe.go:74 +0x1f3
created by github.com/prometheus/prometheus/pkg/logging.Dedupe
  /home/golang/src/github.com/prometheus/prometheus/pkg/logging/dedupe.go:60 +0xcf

goroutine 103 [chan receive]:
github.com/prometheus/prometheus/storage/remote.(*WriteStorage).run(0xc000122d20)
  /home/golang/src/github.com/prometheus/prometheus/storage/remote/write.go:79 +0xc7
created by github.com/prometheus/prometheus/storage/remote.NewWriteStorage
  /home/golang/src/github.com/prometheus/prometheus/storage/remote/write.go:72 +0x122
```

**Comment by fcddk** [comment]
! also encountered the same problem, and finally found out that the disk was full


df -h
root@mgt08:~# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/lma-monitor   20G   19G     0 100% /monitor
