### ISSUE TITLE
Test failure with Go 1.16 beta 1: goleak: Errors on successful test run: found unexpected goroutines

### ISSUE THREAD

**Issue by eclipseo** [prometheus/prometheus#8393]
**What did you do?**
run go test

**What did you expect to see?**
Tests success.

**What did you see instead? Under which circumstances?**

With Golang 1.16 beta 1

```
github.com/prometheus/prometheus/tsdb
level=info msg="Found healthy block" mint=0 maxt=3 ulid=01EWK81SZA70GH9HZWN67AE8KH
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=4.9Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=0
level=info msg="WAL replay completed" checkpoint_replay_duration=31.89Âµs wal_replay_duration=228.186Âµs total_replay_duration=277.792Âµs
level=info msg="write block" mint=3 maxt=10000 ulid=01EWK81T43FEVVG2NXC3YCYYHW duration=146.244387ms
level=info msg="Head GC completed" duration=982.403Âµs
level=info msg="Compactions disabled"
level=info msg="Found healthy block" mint=0 maxt=3 ulid=01EWK81SZA70GH9HZWN67AE8KH
level=info msg="Found healthy block" mint=3 maxt=10000 ulid=01EWK81T43FEVVG2NXC3YCYYHW
level=info msg="Found healthy block" mint=15005 maxt=15006 ulid=01EWK81TAHJKGKM0CN5P0NXT1S
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=7.669Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=2
level=info msg="WAL segment loaded" segment=1 maxSegment=2
level=info msg="WAL segment loaded" segment=2 maxSegment=2
level=info msg="WAL replay completed" checkpoint_replay_duration=41.693Âµs wal_replay_duration=717.448Âµs total_replay_duration=780.978Âµs
level=info msg="write block" mint=15006 maxt=20000 ulid=01EWK81TFE4PW1HVYVW53ZKV2B duration=145.659454ms
level=info msg="Head GC completed" duration=1.048735ms
level=info msg="Found healthy block" mint=10 maxt=12 ulid=01EWK81TNVNRNZY7RP3XZNYAWP
level=info msg="Found healthy block" mint=12 maxt=14 ulid=01EWK81TTQZXM8AWF7X41QX5RY
level=info msg="Found healthy block" mint=14 maxt=16 ulid=01EWK81TZC867B4H1N8TEDC724
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=4.523Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=1
level=info msg="WAL segment loaded" segment=1 maxSegment=1
level=info msg="WAL replay completed" checkpoint_replay_duration=34.964Âµs wal_replay_duration=478.285Âµs total_replay_duration=531.237Âµs
level=info msg="Compactions disabled"
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=3.591Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=1
level=info msg="WAL segment loaded" segment=1 maxSegment=1
level=info msg="WAL replay completed" checkpoint_replay_duration=34.767Âµs wal_replay_duration=540.646Âµs total_replay_duration=562.744Âµs
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=3.724Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=1
level=info msg="WAL segment loaded" segment=1 maxSegment=1
level=info msg="WAL replay completed" checkpoint_replay_duration=34.301Âµs wal_replay_duration=866.472Âµs total_replay_duration=1.293411ms
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=6.728Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=0
level=info msg="WAL replay completed" checkpoint_replay_duration=45.279Âµs wal_replay_duration=2.246931ms total_replay_duration=3.222193ms
level=info msg="Compactions disabled"
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=4.838Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=0
level=info msg="WAL replay completed" checkpoint_replay_duration=32.863Âµs wal_replay_duration=2.899549ms total_replay_duration=2.948444ms
level=info msg="write block" mint=0 maxt=1000 ulid=01EWK81V5KTQQ6W01BFJ2HXQJ7 duration=150.796756ms
level=info msg="Fixing broken block" mint=1511366400000 maxt=1511368200000 ulid=01BZJ9WJQPWHGNC2W4J9TA62KC
level=info msg="Found healthy block" mint=0 maxt=10 ulid=01EWK81VND30J61H9V29N3FADM
level=info msg="Found healthy block" mint=10 maxt=20 ulid=01EWK81VTA7SNH52R4DJ3YECJW
level=error msg="failed to read meta.json for a block during repair process; skipping" dir=/tmp/test205314014/01EWK81VZ145XHY05SJW299AW3 err="open /tmp/test205314014/01EWK81VZ145XHY05SJW299AW3/meta.json: no such file or directory"
level=info msg="Found healthy block" mint=50 maxt=60 ulid=01EWK81WDPNQGCWEJKKBWF4PVV
level=info msg="Found healthy block" mint=50 maxt=55 ulid=01EWK81WJHDDVRG9GHHZSP1JMQ
level=info msg="Found and deleted tmp block dir" dir=/tmp/test205314014/01EWK81W3YN4B5RZGV190RZM12.tmp-for-creation
level=info msg="Found and deleted tmp block dir" dir=/tmp/test205314014/01EWK81W8SJ8EJ5WRZ6SYWQ1GD.tmp-for-deletion
level=error msg="Failed to read meta.json for a block during reloadBlocks. Skipping" dir=/tmp/test205314014/01EWK81VZ145XHY05SJW299AW3 err="open /tmp/test205314014/01EWK81VZ145XHY05SJW299AW3/meta.json: no such file or directory"
level=info msg="Deleting obsolete block" block=01EWK81WJHDDVRG9GHHZSP1JMQ
level=info msg="Replaying on-disk memory mappable chunks if any"
level=info msg="On-disk memory mappable chunks replay completed" duration=5.014Âµs
level=info msg="Replaying WAL, this may take a while"
level=info msg="WAL segment loaded" segment=0 maxSegment=0
level=info msg="WAL replay completed" checkpoint_replay_duration=32.079Âµs wal_replay_duration=249.512Âµs total_replay_duration=298.36Âµs
level=warn msg="Invalid segment file detected, truncating WAL" err="invalid magic header 1020304 in \"/tmp/test_wal_log_restore572968636/000001\"" file=/tmp/test_wal_log_restore572968636/000001
level=error msg="WAL corruption detected; truncating" err="invalid checksum length 3" file=/tmp/test_corrupted043862763/000001 pos=44
level=error msg="WAL corruption detected; truncating" err="invalid entry body size 22" file=/tmp/test_corrupted904456014/000001 pos=44
level=error msg="WAL corruption detected; truncating" err="unexpected CRC32 checksum 1d4d95cc, want 7c1a52ff" file=/tmp/test_corrupted544144469/000001 pos=44
level=error msg="WAL corruption detected; truncating" err="unexpected CRC32 checksum 7c1a52ff, want 1020304" file=/tmp/test_corrupted742450096/000001 pos=44
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 10828 in state chan send, with github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut.func2 on top of the stack:
goroutine 10828 [chan send]:
github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut.func2(0xc002f244d0)
	/builddir/build/BUILD/prometheus-2.24.1/_build/src/github.com/prometheus/prometheus/tsdb/wal.go:600 +0x6f
created by github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut
	/builddir/build/BUILD/prometheus-2.24.1/_build/src/github.com/prometheus/prometheus/tsdb/wal.go:599 +0x12d
]
exit status 1
FAIL	github.com/prometheus/prometheus/tsdb	57.681s
```

**Environment**
* Fedora Rawhide
* Golang 1.16 beta 1 
* Prometheus version: 2.24.1 (e4487274853c587717006eeda8804e597d120340)

**Comment by eclipseo** [comment]
I've got another error following:

```
github.com/prometheus/prometheus/tsdb/chunks
--- FAIL: TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks (0.01s)
panic: runtime error: slice bounds out of range [:104326] with capacity 104293 [recovered]
	panic: runtime error: slice bounds out of range [:104326] with capacity 104293

goroutine 20 [running]:
testing.tRunner.func1.2(0x555db3ac0a40, 0xc0000d20d8)
	/usr/lib/golang/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000086900)
	/usr/lib/golang/src/testing/testing.go:1147 +0x4b6
panic(0x555db3ac0a40, 0xc0000d20d8)
	/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/prometheus/prometheus/tsdb/chunks.TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks(0xc000086900)
	/builddir/build/BUILD/prometheus-2.24.1/_build/src/github.com/prometheus/prometheus/tsdb/chunks/head_chunks_test.go:122 +0xc9c
testing.tRunner(0xc000086900, 0x555db3ad7188)
	/usr/lib/golang/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1239 +0x2b3
exit status 2
FAIL	github.com/prometheus/prometheus/tsdb/chunks	0.015s
```

**Comment by roidelapluie** [comment]
How frequently does that happen? Every time?

**Comment by eclipseo** [comment]
I tried two times and it failed both time.

**Comment by roidelapluie** [comment]
I have moved that in 2 different issues: #8403

**Comment by roidelapluie** [comment]
The first issue seems the same as #7672, closing this one as duplicate then.

#8403 tracks the second issue.

Thanks!
