### ISSUE TITLE
scaleway_sd_configs: invalid memory address or nil pointer dereference panic

### ISSUE THREAD

**Issue by sdurrheimer** [prometheus/prometheus#8736]
**What did you do?**

Add a new scrape config using the new Scaleway discovery.

**What did you expect to see?**

My Scaleway `fr-par-1` instances being scraped.

**What did you see instead? Under which circumstances?**

My Prometheus server panicking right after loading the configuration.

**Environment**

* System information:

`quay.io/prometheus/prometheus:v2.26.0` using the prometheus-operator.

* Prometheus version:

```
prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64
```

* Prometheus configuration file:
```
- job_name: scw/instances/fr-par-1
  scaleway_sd_configs:
  - role: instance
    project_id: <my_default_organization_project_id_same_as_the_organization_id>
    zone: fr-par-1
    access_key: <my_access_key>
    secret_key: <my_secret_key>
    refresh_interval: 1m
    port: 9100

  relabel_configs:
  # drop if monitoring_discovery tag is false
  - source_labels: [__meta_scaleway_instance_tags]
    separator: ;
    regex: ".*,monitoring_discovery=false,.*"
    # replacement: $1
    action: drop
  - source_labels: [__meta_scaleway_instance_public_ipv4]
    target_label: __address__
    replacement: "${1}:9100"
  - source_labels: [__meta_scaleway_instance_tags]
    regex: ",(.+),"
    target_label: tags
  - source_labels: [__meta_scaleway_instance_region]
    target_label: region
  - source_labels: [__meta_scaleway_instance_zone]
    target_label: zone
  - source_labels: [__meta_scaleway_instance_name]
    target_label: instance
  - source_labels: [__meta_scaleway_instance_tags]
    separator: ;
    regex: ".*,project=([^,]+),.*"
    action: replace
    target_label: project
    replacement: $1
  - source_labels: [__meta_scaleway_instance_tags]
    separator: ;
    regex: ".*,env=([^,]+),.*"
    action: replace
    target_label: env
    replacement: $1
  - source_labels: [__meta_scaleway_instance_tags]
    separator: ;
    regex: ".*,role=([^,]+),.*"
    action: replace
    target_label: role
    replacement: $1
  - source_labels: [__meta_scaleway_instance_tags]
    separator: ;
    regex: ".*,customer=([^,]+),.*"
    action: replace
    target_label: customer
    replacement: $1
  - source_labels: [__meta_scaleway_instance_tags]
    separator: ;
    regex: ".*,client=([^,]+),.*"
    action: replace
    target_label: customer
    replacement: $1
  metric_relabel_configs:
  - source_labels: [cycloid_tag_name]
    separator: ;
    regex: (.+)
    action: replace
    target_label: instance
    replacement: $1
  - source_labels: [cycloid_tag_project]
    separator: ;
    regex: (.+)
    action: replace
    target_label: project
    replacement: $1
  - source_labels: [cycloid_tag_env]
    separator: ;
    regex: (.+)
    action: replace
    target_label: env
    replacement: $1
  - source_labels: [cycloid_tag_role]
    separator: ;
    regex: (.+)
    action: replace
    target_label: role
    replacement: $1
  - source_labels: [cycloid_tag_customer]
    separator: ;
    regex: (.+)
    action: replace
    target_label: customer
    replacement: $1
  - source_labels: [cycloid_tag_region]
    separator: ;
    regex: (.+)
    action: replace
    target_label: region
    replacement: $1
  - source_labels: [cycloid_tag_zone]
    separator: ;
    regex: (.+)
    action: replace
    target_label: zone
    replacement: $1
  - separator: ;
    regex: cycloid_tag_.*
    action: labeldrop
```

* Logs:
```
prometheus level=info ts=2021-04-16T16:20:12.563Z caller=main.go:944 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
prometheus level=info ts=2021-04-16T16:20:12.587Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=info ts=2021-04-16T16:20:12.588Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=info ts=2021-04-16T16:20:12.589Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=info ts=2021-04-16T16:20:12.590Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=info ts=2021-04-16T16:20:12.591Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=info ts=2021-04-16T16:20:12.592Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=info ts=2021-04-16T16:20:12.593Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=info ts=2021-04-16T16:20:12.594Z caller=kubernetes.go:266 component="discovery manager notify" discovery=kubernetes msg="Using pod service account via in-cluster config"
prometheus level=error ts=2021-04-16T16:20:12.677Z caller=refresh.go:79 component="discovery manager scrape" discovery=scaleway msg="Unable to refresh target groups" err="scaleway-sdk-go: http error 501 Not Implemented: unknown service"
prometheus level=info ts=2021-04-16T16:20:12.751Z caller=main.go:975 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=188.455182ms remote_storage=2.585µs web_handler=972ns query_engine=1.784µs scrape=322.457µs scrape_sd=6.947145ms notify=17.964µs notify_sd=2.305969ms rules=155.182448ms
prometheus level=info ts=2021-04-16T16:20:12.752Z caller=main.go:767 msg="Server is ready to receive web requests."
prometheus panic: runtime error: invalid memory address or nil pointer dereference
prometheus [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1f623a1]
prometheus goroutine 521 [running[]:
prometheus github.com/prometheus/prometheus/discovery/scaleway.(*instanceDiscovery).refresh(0xc01f98b900, 0x32d6570, 0xc01fb3f0c0, 0x0, 0xc0168c2f236edbf9, 0x2b96aae23, 0x4421000, 0x263)
prometheus     /app/discovery/scaleway/instance.go:133 +0x381
prometheus github.com/prometheus/prometheus/discovery/refresh.(*Discovery).refresh(0xc01fa46e80, 0x32d6570, 0xc01fb3f0c0, 0x0, 0x0, 0x0, 0x0, 0x0)
prometheus     /app/discovery/refresh/refresh.go:117 +0x107
prometheus github.com/prometheus/prometheus/discovery/refresh.(*Discovery).Run(0xc01fa46e80, 0x32d6570, 0xc01fb3f0c0, 0xc01fb387e0)
prometheus     /app/discovery/refresh/refresh.go:76 +0x85
prometheus created by github.com/prometheus/prometheus/discovery.(*Manager).startProvider
prometheus     /app/discovery/manager.go:201 +0x367
```

**Comment by sdurrheimer** [comment]
Thanks @roidelapluie.

I tested the fix with the `:main` docker image, it's working fine, a `2.26.1` release would be welcome.

**Comment by roidelapluie** [comment]
A 2.26.1 is unlikely to happen but I invite you to test the 2.27.0-rc.0 which has the fix + the ability to read the scaleway secret from a file (if you need it).
