### ISSUE TITLE
Prometheus panics when checkpoint directory is empty

### ISSUE THREAD

**Issue by sthaha** [prometheus/prometheus#9605]
**What did you do?**
Run prometheus (deployed using Prometheus Operator in Kubernetes) using NFS for persistent storage. Although NFS is unsupported, it shouldn't result in prometheus crashing. 

**What did you expect to see?**
When prometheus start WAL replay and encounters an error, it should gracefully shutting down instead of crashing.

**What did you see instead? Under which circumstances?**
Prometheus crashes with the following log message

```
level=info ts=2021-10-05T01:41:12.530Z caller=head.go:716 component=tsdb msg="Replaying WAL, this may take a while"
panic: runtime error: index out of range [0] with length 0

goroutine 297 [running]:
github.com/prometheus/prometheus/tsdb/wal.NewSegmentBufReader(...)
    /go/src/github.com/prometheus/prometheus/tsdb/wal/wal.go:862
github.com/prometheus/prometheus/tsdb/wal.NewSegmentsRangeReader(0xc0012a9a50, 0x1, 0x1, 0x23, 0x4ef, 0x0, 0x0)
    /go/src/github.com/prometheus/prometheus/tsdb/wal/wal.go:844 +0x770
```

**Environment**

* System information:
  `Linux 4.18.0-305.10.2.el8_4.x86_64`
* Prometheus version:
        `version=2.26.1` 

* Logs:
```
level=info ts=2021-10-05T01:41:12.108Z caller=main.go:418 msg="Starting Prometheus" version="(version=2.26.1, branch=rhaos-4.8-rhel-8, revision=c052078834283fc9419d39dc92fa98deca2074dd)"
level=info ts=2021-10-05T01:41:12.108Z caller=main.go:423 build_context="(go=go1.16.6, user=root@22ba12e0d3d8, date=20210729-16:32:07)"
level=info ts=2021-10-05T01:41:12.109Z caller=main.go:424 host_details="(Linux 4.18.0-305.10.2.el8_4.x86_64 #1 SMP Mon Jul 12 04:43:18 EDT 2021 x86_64 prometheus-k8s-1 (none))"
level=info ts=2021-10-05T01:41:12.109Z caller=main.go:425 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-10-05T01:41:12.109Z caller=main.go:426 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-10-05T01:41:12.185Z caller=web.go:540 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=info ts=2021-10-05T01:41:12.186Z caller=main.go:795 msg="Starting TSDB ..."
level=info ts=2021-10-05T01:41:12.186Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
level=info ts=2021-10-05T01:41:12.210Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1631793600032 maxt=1631858400000 ulid=01FFSPM4CA77E4T8A8BE0B62N0
level=info ts=2021-10-05T01:41:12.212Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1631858400032 maxt=1631923200000 ulid=01FFVMDNYC3X486S79Q4E9HTKY
level=info ts=2021-10-05T01:41:12.213Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1631923200032 maxt=1631988000000 ulid=01FFXJ779WB4R2XK81T0W9H5GH
level=info ts=2021-10-05T01:41:12.214Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1631988000032 maxt=1632052800000 ulid=01FFZG0RMVS92P3BG9FV6D7ZCZ
level=info ts=2021-10-05T01:41:12.215Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632052800032 maxt=1632117600000 ulid=01FG1DT8NNX3QPJY3KMXCZ9GKE
level=info ts=2021-10-05T01:41:12.216Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632117600032 maxt=1632182400000 ulid=01FG3BKRYZY063P8EQ7XR6RPFX
level=info ts=2021-10-05T01:41:12.217Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632182400032 maxt=1632247200000 ulid=01FGBY8TQQFT44BD6MERRMCB7D
level=info ts=2021-10-05T01:41:12.218Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632471579722 maxt=1632506400000 ulid=01FGD0KJBTB0QETRQHNRE7W06N
level=info ts=2021-10-05T01:41:12.219Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632506400035 maxt=1632571200000 ulid=01FGNP29DT69EPKMDFKRBWE8W1
level=info ts=2021-10-05T01:41:12.220Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632571200033 maxt=1632592800000 ulid=01FGP0ZQ3DYZFK0EB3V030Z7RJ
level=info ts=2021-10-05T01:41:12.221Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632811744270 maxt=1632830400000 ulid=01FGPNJYN03ATA585HX6H4V4F5
level=info ts=2021-10-05T01:41:12.222Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632830400032 maxt=1632895200000 ulid=01FGRKCRY1SRA5ACCPFYVA38ZA
level=info ts=2021-10-05T01:41:12.224Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632895200032 maxt=1632960000000 ulid=01FGTH6CADDF4CMCPH0HYVHEWR
level=info ts=2021-10-05T01:41:12.225Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632960000032 maxt=1633024800000 ulid=01FGWEZTR3NTX1Y7BCEFSWJPR2
level=info ts=2021-10-05T01:41:12.226Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1633024800032 maxt=1633046400000 ulid=01FGX3JQFM8SC9W5YM85X52K2E
level=info ts=2021-10-05T01:41:12.226Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1633068000032 maxt=1633075200000 ulid=01FGXH9VNYYBDQ9CV2P03FWP8M
level=info ts=2021-10-05T01:41:12.228Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1633075200032 maxt=1633082400000 ulid=01FGXR5JXYT7DSEVFCDZW8ZQAG
level=info ts=2021-10-05T01:41:12.229Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1633046400032 maxt=1633068000000 ulid=01FGXR5XCKX9RN5DQZJ5MAJ57X
level=info ts=2021-10-05T01:41:12.230Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1633082400032 maxt=1633089600000 ulid=01FGXZ1A5XS06ZPQJFKAMRA2P6
level=info ts=2021-10-05T01:41:12.231Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1633089600032 maxt=1633096800000 ulid=01FGY5X1DX6QP29VEKVD5P8AQQ
level=info ts=2021-10-05T01:41:12.232Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1633096800032 maxt=1633104000000 ulid=01FGYCRRNWS18WA0YNTAXABFBR
level=info ts=2021-10-05T01:41:12.530Z caller=head.go:696 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-10-05T01:41:12.530Z caller=head.go:710 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=3.481µs
level=info ts=2021-10-05T01:41:12.530Z caller=head.go:716 component=tsdb msg="Replaying WAL, this may take a while"
panic: runtime error: index out of range [0] with length 0

goroutine 297 [running]:
github.com/prometheus/prometheus/tsdb/wal.NewSegmentBufReader(...)
    /go/src/github.com/prometheus/prometheus/tsdb/wal/wal.go:862
github.com/prometheus/prometheus/tsdb/wal.NewSegmentsRangeReader(0xc0012a9a50, 0x1, 0x1, 0x23, 0x4ef, 0x0, 0x0)
    /go/src/github.com/prometheus/prometheus/tsdb/wal/wal.go:844 +0x770
github.com/prometheus/prometheus/tsdb/wal.NewSegmentsReader(...)
    /go/src/github.com/prometheus/prometheus/tsdb/wal/wal.go:816
github.com/prometheus/prometheus/tsdb.(*Head).Init(0xc0003f8000, 0x17c3c957400, 0x0, 0x0)
    /go/src/github.com/prometheus/prometheus/tsdb/head.go:726 +0x13ed
github.com/prometheus/prometheus/tsdb.open(0x7fff974e5138, 0xb, 0x3290520, 0xc00097e0c0, 0x32c8a90, 0xc00014ed20, 0xc0011f6ea0, 0xc00128e000, 0x3, 0xa, ...)
    /go/src/github.com/prometheus/prometheus/tsdb/db.go:695 +0x858
github.com/prometheus/prometheus/tsdb.Open(0x7fff974e5138, 0xb, 0x3290520, 0xc00097e0c0, 0x32c8a90, 0xc00014ed20, 0xc0011f6ea0, 0xc000560e48, 0x7ac9e2, 0xc0004da9c0)
    /go/src/github.com/prometheus/prometheus/tsdb/db.go:540 +0xbc
main.openDBWithMetrics(0x7fff974e5138, 0xb, 0x3290520, 0xc00098cdb0, 0x32c8a90, 0xc00014ed20, 0xc0011f6ea0, 0x0, 0x0, 0x0)
    /go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:888 +0x10d
main.main.func20(0x0, 0x0)
    /go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:801 +0x1ff
github.com/oklog/run.(*Group).Run.func1(0xc0011f6f00, 0xc0005543c0, 0xc0011fd350)
    /go/src/github.com/prometheus/prometheus/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
    /go/src/github.com/prometheus/prometheus/vendor/github.com/oklog/run/group.go:37 +0xbb
```

**Comment by roidelapluie** [comment]
ping @codesome what should we do about this issue? thanks

**Comment by codesome** [comment]
If avoiding the crash would (1) require a ~small update in code (2) and _not_ assume a non-POSIX storage, then happy to accept contributions for that. Otherwise, I don't think it is worth updating the error handling for non-POSIX storage since that would fill the codebase with lots of code that assumes that storage can be non-POSIX (like every interaction with the storage?).

**Comment by codesome** [comment]
If #9606 fixes it, that looks like an acceptable patch (but needs some changes, like `NewSegmentBufReader` should not return an error for 0 segments, but rather the reader should return `io.EOF` error when tried to read)
