### ISSUE TITLE
open /prometheus/queries.active: permission denied

### ISSUE THREAD

**Issue by forging2012** [prometheus/prometheus#9704]
```
---
version: '3.1'

services:
  prometheus-1:
    image: prom/prometheus:v2.31.1
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data/prometheus1/data:/prometheus
```

```
quickstart-thanos-prometheus-1-1           | ts=2021-11-09T08:04:28.858Z caller=query_logger.go:87 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
quickstart-thanos-prometheus-1-1           | panic: Unable to create mmap-ed active query log
quickstart-thanos-prometheus-1-1           | 
quickstart-thanos-prometheus-1-1           | goroutine 1 [running]:
quickstart-thanos-prometheus-1-1           | github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffecc6f6ea1, 0xb}, 0x14, {0x34442c0, 0xc000148f50})
quickstart-thanos-prometheus-1-1           | 	/app/promql/query_logger.go:117 +0x3d7
quickstart-thanos-prometheus-1-1           | main.main()
quickstart-thanos-prometheus-1-1           | 	/app/cmd/prometheus/main.go:491 +0x6bbf
quickstart-thanos-thanos-bucket-web-1      | level=info ts=2021-11-09T08:04:28.913576878Z caller=fetcher.go:476 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=188.209048ms duration_ms=188 cached=3 returned=3 partial=0


```

```
docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by forging2012** [comment]
```
chmod 777 ./data/prometheus1/data
```

done.
