### ISSUE TITLE
Crash loop in NewActiveQueryTracker on disk full

### ISSUE THREAD

**Issue by discostur** [prometheus/prometheus#9923]
**What did you do?**
Upgraded prometheus via helm chart from v2.26.0 to 2.31.1 and everything was fine. Changed the config file today and did a re-deploy and prometheus keeps crashing all the time. 

* Logs:
```
ts=2021-12-02T09:23:08.830Z caller=main.go:444 level=info msg="Starting Prometheus" version="(version=2.31.1, branch=HEAD, revision=411021ada9ab41095923b8d2df9365b632fd40c3)"
ts=2021-12-02T09:23:08.830Z caller=main.go:449 level=info build_context="(go=go1.17.3, user=root@9419c9c2d4e0, date=20211105-20:35:02)"
ts=2021-12-02T09:23:08.830Z caller=main.go:450 level=info host_details="(Linux 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 prometheus-server-84944dbb5-77z89 (none))"
ts=2021-12-02T09:23:08.830Z caller=main.go:451 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2021-12-02T09:23:08.830Z caller=main.go:452 level=info vm_limits="(soft=unlimited, hard=unlimited)"
unexpected fault address 0x7f2c07c61000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f2c07c61000 pc=0x4698e2]
goroutine 1 [running]:
runtime.throw({0x2bda7d6, 0x0})
/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc000823148 sp=0xc000823118 pc=0x435651
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:732 +0x125 fp=0xc000823198 sp=0xc000823148 pc=0x44b865
runtime.memmove()
/usr/local/go/src/runtime/memmove_amd64.s:158 +0x102 fp=0xc0008231a0 sp=0xc000823198 pc=0x4698e2
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffd39f31a55, 0x5}, 0x14, {0x34442c0, 0xc00068f4f0})
/app/promql/query_logger.go:120 +0x227 fp=0xc0008232e0 sp=0xc0008231a0 pc=0x214e167
main.main()
/app/cmd/prometheus/main.go:491 +0x6bbf fp=0xc000823f80 sp=0xc0008232e0 pc=0x222433f
runtime.main()
/usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc000823fe0 sp=0xc000823f80 pc=0x437d27
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000823fe8 sp=0xc000823fe0 pc=0x468961
goroutine 50 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000128080)
/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92
goroutine 129 [select]:
github.com/prometheus/prometheus/pkg/logging.(*Deduper).run(0xc0000d6940)
/app/pkg/logging/dedupe.go:75 +0xee
created by github.com/prometheus/prometheus/pkg/logging.Dedupe
/app/pkg/logging/dedupe.go:61 +0x10f
goroutine 136 [chan receive]:
github.com/prometheus/prometheus/storage/remote.(*WriteStorage).run(0xc000a88f00)
/app/storage/remote/write.go:103 +0xa8
created by github.com/prometheus/prometheus/storage/remote.NewWriteStorage
/app/storage/remote/write.go:96 +0x448
```

Also tried to downgrade to an older version but the error doesn't change. Tried v2.29.x and 2.26.x ... 

Regards,
Kilian

**Comment by discostur** [comment]
Ok error seems to be related to our pvc which was full ... increased the storage size and prometheus is running again ;)

I'm not shure but i think in earlier versions there was a specifig error message if storage was full / no more space available. 

From my side you can close the ticket, not shure if you need it anymore.

Regards,
Kilian

**Comment by codesome** [comment]
Glad to know you found the issue. Crash message depends on what part of Prometheus ran into the space issue first. The "no more space available" comes from TSDB when it's writing, but this seems to be from remote write which only reads and might have hit a corruption because of disk space issues. Closing this since there is nothing actionable.

**Comment by bboreham** [comment]
Well I hit this today so I think Prometheus should behave better.
Printing out an error that the disk is full would be an improvement.

To work round it, since mine was only a test Prometheus, I temporarily changed `--storage.tsdb.path` to `/tmp/prometheus`, so it would start and I could shell into the container to delete some data.

**Comment by beorn7** [comment]
Hello from the bug scrub!

This is actively being worked on, see #14494  .

**Comment by bboreham** [comment]
Sadly the author of #14494 is no longer working on it.
Open to someone else to pick up - I think that solution was close.

**Comment by krajorama** [comment]
Hi, I think this has been fixed via #19092

**Comment by aknuds1** [comment]
Closing as fixed by #19092.
